"""Complete nonempty model registry, imported offline without creating connections."""

from app.models.authorization import (
    AdminAuditEvent,
    AuthorizationRevision,
    AuthPolicy,
    Menu,
    MenuPermission,
    OutboxEvent,
    PermissionCatalog,
    PermissionDependency,
    Role,
    RoleGrantBoundary,
    RoleInheritance,
    RolePermission,
    SeedVersion,
    UserRole,
)
from app.models.avatar import FileObject, UploadIntent
from app.models.base import Base, TimestampMixin
from app.models.identity import Library, User
from app.models.identity_security import (
    AuthChallenge,
    AuthChallengeDelivery,
    AuthSession,
    UserExtension,
    UserLanguage,
)
from app.models.learning_reference import (
    Card,
    CollectionItem,
    IdempotencyRecord,
    Material,
    MaterialContentBlock,
    MaterialRevision,
    MaterialSourceUnit,
    NovelChapter,
    NovelChapterBlock,
    SourceResultBinding,
)

__all__ = [
    "AdminAuditEvent",
    "AuthPolicy",
    "AuthChallenge",
    "AuthChallengeDelivery",
    "AuthSession",
    "AuthorizationRevision",
    "Base",
    "Card",
    "CollectionItem",
    "FileObject",
    "IdempotencyRecord",
    "Library",
    "Material",
    "MaterialContentBlock",
    "MaterialRevision",
    "MaterialSourceUnit",
    "Menu",
    "MenuPermission",
    "NovelChapter",
    "NovelChapterBlock",
    "OutboxEvent",
    "PermissionCatalog",
    "PermissionDependency",
    "Role",
    "RoleGrantBoundary",
    "RoleInheritance",
    "RolePermission",
    "SeedVersion",
    "SourceResultBinding",
    "TimestampMixin",
    "UploadIntent",
    "User",
    "UserExtension",
    "UserLanguage",
    "UserRole",
]
