"""Complete nonempty model registry, imported offline without creating connections."""

from app.models.authorization import (
    AdminAuditEvent,
    AuthorizationRevision,
    AuthPolicy,
    Menu,
    MenuPermission,
    OutboxEvent,
    PermissionCatalog,
    PermissionDependency,
    Role,
    RoleGrantBoundary,
    RoleInheritance,
    RolePermission,
    SeedVersion,
    UserRole,
)
from app.models.avatar import FileObject, UploadIntent
from app.models.base import Base, TimestampMixin
from app.models.identity import Library, User
from app.models.identity_security import (
    AuthChallenge,
    AuthChallengeDelivery,
    AuthSession,
    UserExtension,
    UserLanguage,
)
from app.models.learning_reference import (
    Card,
    CollectionItem,
    IdempotencyRecord,
    Material,
    MaterialContentBlock,
    MaterialRevision,
    MaterialSourceUnit,
    NovelChapter,
    NovelChapterBlock,
    SourceResultBinding,
)
from app.models.material_imports import (
    MaterialImport,
    MaterialImportIssue,
    MaterialSourceAsset,
    UserStorageReservation,
    UserStorageState,
)
from app.models.model_tasks import (
    AiRun,
    ExternalCallAttempt,
    InboxEvent,
    Job,
    JobStage,
    ModelCatalogEntry,
    ModelLimitPolicy,
    ProviderCredential,
)
from app.models.user_notifications import UserNotification

__all__ = [
    "MaterialImport",
    "MaterialImportIssue",
    "MaterialSourceAsset",
    "UserStorageReservation",
    "UserStorageState",
    "UserNotification",
    "AiRun",
    "ExternalCallAttempt",
    "InboxEvent",
    "Job",
    "JobStage",
    "ModelCatalogEntry",
    "ModelLimitPolicy",
    "ProviderCredential",
    "AdminAuditEvent",
    "AuthPolicy",
    "AuthChallenge",
    "AuthChallengeDelivery",
    "AuthSession",
    "AuthorizationRevision",
    "Base",
    "Card",
    "CollectionItem",
    "FileObject",
    "IdempotencyRecord",
    "Library",
    "Material",
    "MaterialContentBlock",
    "MaterialRevision",
    "MaterialSourceUnit",
    "Menu",
    "MenuPermission",
    "NovelChapter",
    "NovelChapterBlock",
    "OutboxEvent",
    "PermissionCatalog",
    "PermissionDependency",
    "Role",
    "RoleGrantBoundary",
    "RoleInheritance",
    "RolePermission",
    "SeedVersion",
    "SourceResultBinding",
    "TimestampMixin",
    "UploadIntent",
    "User",
    "UserExtension",
    "UserLanguage",
    "UserRole",
]
