// Mocks generated by Mockito from annotations
// in haruka/test/features/notifications/cached_notification_repository_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes

import 'dart:async' as _i4;

import 'package:dio/dio.dart' as _i6;
import 'package:haruka/core/cache/cache_coordinator.dart' as _i2;
import 'package:haruka/core/cache/cache_models.dart' as _i5;
import 'package:haruka/features/notifications/data/notification_repository.dart' as _i3;
import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i7;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: experimental_member_use
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

/// A class which mocks [CacheRemote].
///
/// See the documentation for Mockito's code generation for more information.
class MockNotificationRemote extends _i1.Mock
    implements _i2.CacheRemote<_i3.NotificationListSnapshot> {
  @override
  _i4.Future<_i5.CacheValidation> validate(
    _i5.CacheResource? resource,
    _i5.CacheVersion? known,
    _i6.CancelToken? cancel,
  ) => (super.noSuchMethod(
    Invocation.method(#validate, [resource, known, cancel]),
    returnValue: _i4.Future<_i5.CacheValidation>.value(
      _i7.dummyValue<_i5.CacheValidation>(
        this,
        Invocation.method(#validate, [resource, known, cancel]),
      ),
    ),
    returnValueForMissingStub: _i4.Future<_i5.CacheValidation>.value(
      _i7.dummyValue<_i5.CacheValidation>(
        this,
        Invocation.method(#validate, [resource, known, cancel]),
      ),
    ),
  ) as _i4.Future<_i5.CacheValidation>);

  @override
  _i4.Future<_i5.CachePayload<_i3.NotificationListSnapshot>> fetch(
    _i5.CacheResource? resource,
    _i6.CancelToken? cancel,
  ) => (super.noSuchMethod(
    Invocation.method(#fetch, [resource, cancel]),
    returnValue: _i4.Future<_i5.CachePayload<_i3.NotificationListSnapshot>>.value(
      _i7.dummyValue<_i5.CachePayload<_i3.NotificationListSnapshot>>(
        this,
        Invocation.method(#fetch, [resource, cancel]),
      ),
    ),
    returnValueForMissingStub: _i4.Future<_i5.CachePayload<_i3.NotificationListSnapshot>>.value(
      _i7.dummyValue<_i5.CachePayload<_i3.NotificationListSnapshot>>(
        this,
        Invocation.method(#fetch, [resource, cancel]),
      ),
    ),
  ) as _i4.Future<_i5.CachePayload<_i3.NotificationListSnapshot>>);
}
