"""Persistent owner model tasks, encrypted credentials and reliable event extension."""
from alembic import op
import sqlalchemy as sa
revision = "0010_model_tasks"
down_revision = "0009_governance_lookup"
branch_labels = None
depends_on = None


def upgrade() -> None:
    op.drop_constraint(op.f("ck_outbox_events_event_type"), "outbox_events", type_="check")
    op.drop_constraint(op.f("ck_outbox_events_authorization_revision_positive"), "outbox_events", type_="check")
    op.alter_column("outbox_events", "event_type", type_=sa.String(128), existing_type=sa.String(48))
    op.alter_column("outbox_events", "audit_event_id", existing_type=sa.UUID(), nullable=True)
    op.alter_column("outbox_events", "authorization_revision", existing_type=sa.BigInteger(), nullable=True)
    op.add_column("outbox_events", sa.Column("payload", sa.dialects.postgresql.JSONB(), nullable=False, server_default=sa.text("'{}'::jsonb"), comment="安全事件引用"))
    op.drop_constraint(op.f("ck_admin_audit_events_action"), "admin_audit_events", type_="check")
    op.create_check_constraint(op.f('ck_outbox_events_event_type'), 'outbox_events', "event_type IN ('authorization.changed', 'identity.security', 'model.job.accepted', 'model.job.updated', 'model.usage.updated')")
    op.create_check_constraint(op.f('ck_outbox_events_authorization_revision_positive'), 'outbox_events', "(event_type IN ('authorization.changed','identity.security') AND authorization_revision >= 1 AND audit_event_id IS NOT NULL) OR (event_type LIKE 'model.%' AND authorization_revision IS NULL AND audit_event_id IS NULL)")
    op.create_check_constraint(op.f('ck_admin_audit_events_action'), 'admin_audit_events', "action IN ('credential.created', 'credential.rotated', 'credential.deleted', 'model_catalog.updated', 'model_limits.updated', 'account.registered', 'admin.created', 'auth.login.denied', 'auth_policy.updated', 'authorization.denied', 'email.verified', 'grant_boundary.updated', 'menu.updated', 'password.changed', 'password.recovered', 'recovery.accepted', 'recovery.challenge_issued', 'recovery.completed', 'recovery.rejected', 'recovery.requested', 'recovery.verified', 'refresh.replayed', 'role.created', 'role.deleted', 'role.inheritance_changed', 'role.permission_assigned', 'role.updated', 'seed.applied', 'session.created', 'session.revoked', 'user.approved', 'user.created', 'user.disabled', 'user.enabled', 'user.rejected', 'user.role_assigned', 'user.role_removed', 'user.updated')")

    op.execute('\nCREATE TABLE ai_runs (\n\towner_user_id UUID NOT NULL, \n\tjob_id UUID NOT NULL, \n\tcredential_id UUID NOT NULL, \n\tcredential_version BIGINT NOT NULL, \n\tprovider VARCHAR(24) NOT NULL, \n\tmodel_id VARCHAR(256) NOT NULL, \n\tmodel_revision VARCHAR(128), \n\tcapability VARCHAR(12) NOT NULL, \n\tstate VARCHAR(24) NOT NULL, \n\tgeneration BIGINT NOT NULL, \n\tgeneration_config JSONB NOT NULL, \n\tfinished_at TIMESTAMP WITH TIME ZONE, \n\terror_code VARCHAR(96), \n\tid UUID NOT NULL, \n\tcreated_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL, \n\tupdated_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL, \n\tCONSTRAINT pk_ai_runs PRIMARY KEY (id)\n)\n\n')
    op.execute('CREATE INDEX ix_ai_runs_owner_credential_test ON ai_runs (owner_user_id, credential_id, credential_version, model_id, capability, finished_at)')
    op.execute("COMMENT ON TABLE ai_runs IS '本人模型测试运行安全事实'")
    op.execute("COMMENT ON COLUMN ai_runs.owner_user_id IS '本人'")
    op.execute("COMMENT ON COLUMN ai_runs.job_id IS '任务'")
    op.execute("COMMENT ON COLUMN ai_runs.credential_id IS '凭据身份'")
    op.execute("COMMENT ON COLUMN ai_runs.credential_version IS '秘密代次'")
    op.execute("COMMENT ON COLUMN ai_runs.provider IS '供应商'")
    op.execute("COMMENT ON COLUMN ai_runs.model_id IS '精确模型'")
    op.execute("COMMENT ON COLUMN ai_runs.model_revision IS '已观测修订未知NULL'")
    op.execute("COMMENT ON COLUMN ai_runs.capability IS '单能力'")
    op.execute("COMMENT ON COLUMN ai_runs.state IS '运行状态'")
    op.execute("COMMENT ON COLUMN ai_runs.generation IS '运行代次'")
    op.execute("COMMENT ON COLUMN ai_runs.generation_config IS '冻结模型及调用上限'")
    op.execute("COMMENT ON COLUMN ai_runs.finished_at IS '测试时间'")
    op.execute("COMMENT ON COLUMN ai_runs.error_code IS '安全错误'")
    op.execute("COMMENT ON COLUMN ai_runs.id IS '服务端生成的稳定标识'")
    op.execute("COMMENT ON COLUMN ai_runs.created_at IS '本行创建时间，UTC'")
    op.execute("COMMENT ON COLUMN ai_runs.updated_at IS '本行最近一次实际更新的时间，UTC'")
    op.execute("\nCREATE TABLE external_call_attempts (\n\towner_user_id UUID NOT NULL, \n\tjob_id UUID NOT NULL, \n\tai_run_id UUID NOT NULL, \n\tcredential_id UUID NOT NULL, \n\tcredential_version BIGINT NOT NULL, \n\tprovider VARCHAR(24) NOT NULL, \n\tmodel_id VARCHAR(256) NOT NULL, \n\tcapability VARCHAR(12) NOT NULL, \n\toperation_kind VARCHAR(64) NOT NULL, \n\tattempt_no INTEGER NOT NULL, \n\tstatus VARCHAR(16) NOT NULL, \n\tusage_status VARCHAR(16) DEFAULT 'unavailable' NOT NULL, \n\tusage JSONB DEFAULT '{}'::jsonb NOT NULL, \n\tprovider_usage_schema VARCHAR(64), \n\tsimulated BOOLEAN NOT NULL, \n\taggregation_revision BIGINT DEFAULT 0 NOT NULL, \n\tstarted_at TIMESTAMP WITH TIME ZONE NOT NULL, \n\tfinished_at TIMESTAMP WITH TIME ZONE, \n\terror_code VARCHAR(96), \n\tinput_tokens BIGINT, \n\toutput_tokens BIGINT, \n\ttotal_tokens BIGINT, \n\tcache_read_tokens BIGINT, \n\tcache_write_tokens BIGINT, \n\treasoning_tokens BIGINT, \n\tinput_audio_tokens BIGINT, \n\toutput_audio_tokens BIGINT, \n\tinput_images BIGINT, \n\tinput_characters BIGINT, \n\tid UUID NOT NULL, \n\tcreated_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL, \n\tupdated_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL, \n\tCONSTRAINT pk_external_call_attempts PRIMARY KEY (id), \n\tCONSTRAINT uq_external_call_attempts_owner_user_id_ai_run_id_attempt_no UNIQUE (owner_user_id, ai_run_id, attempt_no), \n\tCONSTRAINT ck_external_call_attempts_status CHECK (status IN ('started','succeeded','failed','unknown')), \n\tCONSTRAINT ck_external_call_attempts_usage_status CHECK (usage_status IN ('complete','partial','unavailable'))\n)\n\n")
    op.execute('CREATE INDEX ix_external_call_attempts_owner_started ON external_call_attempts (owner_user_id, started_at, id)')
    op.execute("COMMENT ON TABLE external_call_attempts IS '实际attempt与用量唯一权威事实'")
    op.execute("COMMENT ON COLUMN external_call_attempts.owner_user_id IS '本人'")
    op.execute("COMMENT ON COLUMN external_call_attempts.job_id IS '任务'")
    op.execute("COMMENT ON COLUMN external_call_attempts.ai_run_id IS '运行'")
    op.execute("COMMENT ON COLUMN external_call_attempts.credential_id IS '凭据'")
    op.execute("COMMENT ON COLUMN external_call_attempts.credential_version IS '实际秘密代次'")
    op.execute("COMMENT ON COLUMN external_call_attempts.provider IS '供应商'")
    op.execute("COMMENT ON COLUMN external_call_attempts.model_id IS '精确模型'")
    op.execute("COMMENT ON COLUMN external_call_attempts.capability IS '能力'")
    op.execute("COMMENT ON COLUMN external_call_attempts.operation_kind IS '动作'")
    op.execute("COMMENT ON COLUMN external_call_attempts.attempt_no IS '真实调用序号'")
    op.execute("COMMENT ON COLUMN external_call_attempts.status IS '外部执行事实'")
    op.execute("COMMENT ON COLUMN external_call_attempts.usage_status IS '用量完整性'")
    op.execute("COMMENT ON COLUMN external_call_attempts.usage IS '白名单数字及未知NULL'")
    op.execute("COMMENT ON COLUMN external_call_attempts.provider_usage_schema IS '用量口径版本'")
    op.execute("COMMENT ON COLUMN external_call_attempts.simulated IS '受控模拟事实'")
    op.execute("COMMENT ON COLUMN external_call_attempts.aggregation_revision IS '补全版本'")
    op.execute("COMMENT ON COLUMN external_call_attempts.started_at IS '调用前落盘'")
    op.execute("COMMENT ON COLUMN external_call_attempts.finished_at IS '外部结束'")
    op.execute("COMMENT ON COLUMN external_call_attempts.error_code IS '受控错误'")
    op.execute("COMMENT ON COLUMN external_call_attempts.input_tokens IS '输入Token；未知NULL'")
    op.execute("COMMENT ON COLUMN external_call_attempts.output_tokens IS '输出Token；未知NULL'")
    op.execute("COMMENT ON COLUMN external_call_attempts.total_tokens IS '供应商总Token；未知NULL'")
    op.execute("COMMENT ON COLUMN external_call_attempts.cache_read_tokens IS '缓存读取Token；未知NULL'")
    op.execute("COMMENT ON COLUMN external_call_attempts.cache_write_tokens IS '缓存写入Token；未知NULL'")
    op.execute("COMMENT ON COLUMN external_call_attempts.reasoning_tokens IS '推理Token；未知NULL'")
    op.execute("COMMENT ON COLUMN external_call_attempts.input_audio_tokens IS '输入音频Token；未知NULL'")
    op.execute("COMMENT ON COLUMN external_call_attempts.output_audio_tokens IS '输出音频Token；未知NULL'")
    op.execute("COMMENT ON COLUMN external_call_attempts.input_images IS '输入图片数；未知NULL'")
    op.execute("COMMENT ON COLUMN external_call_attempts.input_characters IS '输入字符数；未知NULL'")
    op.execute("COMMENT ON COLUMN external_call_attempts.id IS '服务端生成的稳定标识'")
    op.execute("COMMENT ON COLUMN external_call_attempts.created_at IS '本行创建时间，UTC'")
    op.execute("COMMENT ON COLUMN external_call_attempts.updated_at IS '本行最近一次实际更新的时间，UTC'")
    op.execute('\nCREATE TABLE inbox_events (\n\tconsumer_name VARCHAR(96) NOT NULL, \n\tevent_id UUID NOT NULL, \n\tpayload_digest BYTEA NOT NULL, \n\tprocessed_at TIMESTAMP WITH TIME ZONE NOT NULL, \n\tid UUID NOT NULL, \n\tcreated_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL, \n\tupdated_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL, \n\tCONSTRAINT pk_inbox_events PRIMARY KEY (id), \n\tCONSTRAINT uq_inbox_events_consumer_name_event_id UNIQUE (consumer_name, event_id)\n)\n\n')
    op.execute("COMMENT ON TABLE inbox_events IS '业务提交后消费去重事实'")
    op.execute("COMMENT ON COLUMN inbox_events.consumer_name IS '固定消费者'")
    op.execute("COMMENT ON COLUMN inbox_events.event_id IS '发布事件'")
    op.execute("COMMENT ON COLUMN inbox_events.payload_digest IS '事件安全摘要'")
    op.execute("COMMENT ON COLUMN inbox_events.processed_at IS '提交时点'")
    op.execute("COMMENT ON COLUMN inbox_events.id IS '服务端生成的稳定标识'")
    op.execute("COMMENT ON COLUMN inbox_events.created_at IS '本行创建时间，UTC'")
    op.execute("COMMENT ON COLUMN inbox_events.updated_at IS '本行最近一次实际更新的时间，UTC'")
    op.execute('\nCREATE TABLE job_stages (\n\towner_user_id UUID NOT NULL, \n\tjob_id UUID NOT NULL, \n\tjob_generation BIGINT NOT NULL, \n\tstage_key VARCHAR(96) NOT NULL, \n\tstate VARCHAR(24) NOT NULL, \n\tfence BIGINT DEFAULT 0 NOT NULL, \n\tresult_refs JSONB, \n\tid UUID NOT NULL, \n\tcreated_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL, \n\tupdated_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL, \n\tCONSTRAINT pk_job_stages PRIMARY KEY (id), \n\tCONSTRAINT uq_job_stages_job_id_job_generation_stage_key UNIQUE (job_id, job_generation, stage_key)\n)\n\n')
    op.execute("COMMENT ON TABLE job_stages IS '已提交安全阶段恢复点'")
    op.execute("COMMENT ON COLUMN job_stages.owner_user_id IS '本人'")
    op.execute("COMMENT ON COLUMN job_stages.job_id IS '父任务'")
    op.execute("COMMENT ON COLUMN job_stages.job_generation IS '任务代次'")
    op.execute("COMMENT ON COLUMN job_stages.stage_key IS '注册阶段'")
    op.execute("COMMENT ON COLUMN job_stages.state IS '阶段状态'")
    op.execute("COMMENT ON COLUMN job_stages.fence IS '领取栅栏'")
    op.execute("COMMENT ON COLUMN job_stages.result_refs IS '安全恢复成品'")
    op.execute("COMMENT ON COLUMN job_stages.id IS '服务端生成的稳定标识'")
    op.execute("COMMENT ON COLUMN job_stages.created_at IS '本行创建时间，UTC'")
    op.execute("COMMENT ON COLUMN job_stages.updated_at IS '本行最近一次实际更新的时间，UTC'")
    op.execute("\nCREATE TABLE jobs (\n\towner_user_id UUID NOT NULL, \n\tactor_user_id UUID NOT NULL, \n\tsession_id UUID NOT NULL, \n\ttransport VARCHAR(16) NOT NULL, \n\taudience VARCHAR(16) NOT NULL, \n\tcredential_id UUID NOT NULL, \n\trun_id UUID NOT NULL, \n\toperation_kind VARCHAR(64) NOT NULL, \n\toperation_id UUID NOT NULL, \n\trequest_id UUID NOT NULL, \n\tinput_refs JSONB NOT NULL, \n\tinput_digest BYTEA NOT NULL, \n\tidempotency_digest BYTEA NOT NULL, \n\tstate VARCHAR(24) DEFAULT 'queued' NOT NULL, \n\trevision BIGINT DEFAULT 1 NOT NULL, \n\tgeneration BIGINT DEFAULT 1 NOT NULL, \n\tprogress_seq BIGINT DEFAULT 0 NOT NULL, \n\tfence BIGINT DEFAULT 0 NOT NULL, \n\tlease_owner VARCHAR(128), \n\tlease_expires_at TIMESTAMP WITH TIME ZONE, \n\theartbeat_at TIMESTAMP WITH TIME ZONE, \n\terror_code VARCHAR(96), \n\tfinished_at TIMESTAMP WITH TIME ZONE, \n\tid UUID NOT NULL, \n\tcreated_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL, \n\tupdated_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL, \n\tCONSTRAINT pk_jobs PRIMARY KEY (id), \n\tCONSTRAINT ck_jobs_versions CHECK (generation >= 1 AND revision >= 1 AND fence >= 0 AND progress_seq >= 0), \n\tCONSTRAINT ck_jobs_state CHECK (state IN ('queued','running','retry_wait','blocked','succeeded','failed','cancel_requested','cancelled')), \n\tCONSTRAINT uq_jobs_owner_user_id_idempotency_digest UNIQUE (owner_user_id, idempotency_digest)\n)\n\n")
    op.execute('CREATE INDEX ix_jobs_lease ON jobs (state, lease_expires_at)')
    op.execute('CREATE INDEX ix_jobs_owner_state ON jobs (owner_user_id, state, created_at, id)')
    op.execute("COMMENT ON TABLE jobs IS '本人持久模型任务及租约栅栏'")
    op.execute("COMMENT ON COLUMN jobs.owner_user_id IS '本人归属'")
    op.execute("COMMENT ON COLUMN jobs.actor_user_id IS '发起人'")
    op.execute("COMMENT ON COLUMN jobs.session_id IS '受理会话'")
    op.execute("COMMENT ON COLUMN jobs.transport IS '受理传输'")
    op.execute("COMMENT ON COLUMN jobs.audience IS '受理受众'")
    op.execute("COMMENT ON COLUMN jobs.credential_id IS '本人凭据引用'")
    op.execute("COMMENT ON COLUMN jobs.run_id IS '运行引用'")
    op.execute("COMMENT ON COLUMN jobs.operation_kind IS '受控动作'")
    op.execute("COMMENT ON COLUMN jobs.operation_id IS '操作关联'")
    op.execute("COMMENT ON COLUMN jobs.request_id IS '请求关联'")
    op.execute("COMMENT ON COLUMN jobs.input_refs IS '安全固定样本及配置版本引用'")
    op.execute("COMMENT ON COLUMN jobs.input_digest IS '输入摘要'")
    op.execute("COMMENT ON COLUMN jobs.idempotency_digest IS '本人意图摘要'")
    op.execute("COMMENT ON COLUMN jobs.state IS '任务状态'")
    op.execute("COMMENT ON COLUMN jobs.revision IS '任务CAS'")
    op.execute("COMMENT ON COLUMN jobs.generation IS '执行代次'")
    op.execute("COMMENT ON COLUMN jobs.progress_seq IS '持久进度序号'")
    op.execute("COMMENT ON COLUMN jobs.fence IS '领取栅栏'")
    op.execute("COMMENT ON COLUMN jobs.lease_owner IS 'Worker标识'")
    op.execute("COMMENT ON COLUMN jobs.lease_expires_at IS '租约期限'")
    op.execute("COMMENT ON COLUMN jobs.heartbeat_at IS '心跳'")
    op.execute("COMMENT ON COLUMN jobs.error_code IS '受控错误'")
    op.execute("COMMENT ON COLUMN jobs.finished_at IS '任务终态时间'")
    op.execute("COMMENT ON COLUMN jobs.id IS '服务端生成的稳定标识'")
    op.execute("COMMENT ON COLUMN jobs.created_at IS '本行创建时间，UTC'")
    op.execute("COMMENT ON COLUMN jobs.updated_at IS '本行最近一次实际更新的时间，UTC'")
    op.execute('\nCREATE TABLE model_catalog_entries (\n\tprovider VARCHAR(24) NOT NULL, \n\tmodel_code VARCHAR(256) NOT NULL, \n\tdisplay_name VARCHAR(100) NOT NULL, \n\tcapabilities JSONB NOT NULL, \n\tenabled BOOLEAN DEFAULT false NOT NULL, \n\tverified_at TIMESTAMP WITH TIME ZONE, \n\trevision BIGINT DEFAULT 1 NOT NULL, \n\tadapter_code VARCHAR(128), \n\tid UUID NOT NULL, \n\tcreated_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL, \n\tupdated_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL, \n\tCONSTRAINT pk_model_catalog_entries PRIMARY KEY (id), \n\tCONSTRAINT uq_model_catalog_entries_provider_model_code UNIQUE (provider, model_code), \n\tCONSTRAINT ck_model_catalog_entries_revision CHECK (revision >= 1)\n)\n\n')
    op.execute("COMMENT ON TABLE model_catalog_entries IS '发布注册精确模型能力'")
    op.execute("COMMENT ON COLUMN model_catalog_entries.provider IS '发布供应商'")
    op.execute("COMMENT ON COLUMN model_catalog_entries.model_code IS '精确模型'")
    op.execute("COMMENT ON COLUMN model_catalog_entries.display_name IS '显示名'")
    op.execute("COMMENT ON COLUMN model_catalog_entries.capabilities IS '已支持能力'")
    op.execute("COMMENT ON COLUMN model_catalog_entries.enabled IS '新调用启停'")
    op.execute("COMMENT ON COLUMN model_catalog_entries.verified_at IS '真实协议验证时间'")
    op.execute("COMMENT ON COLUMN model_catalog_entries.revision IS '目录版本'")
    op.execute("COMMENT ON COLUMN model_catalog_entries.adapter_code IS '精确TTS适配器'")
    op.execute("COMMENT ON COLUMN model_catalog_entries.id IS '服务端生成的稳定标识'")
    op.execute("COMMENT ON COLUMN model_catalog_entries.created_at IS '本行创建时间，UTC'")
    op.execute("COMMENT ON COLUMN model_catalog_entries.updated_at IS '本行最近一次实际更新的时间，UTC'")
    op.execute('\nCREATE TABLE runtime_limit_policies (\n\tsubject_kind VARCHAR(24) NOT NULL, \n\tlimit_code VARCHAR(64) NOT NULL, \n\tvalue_limit BIGINT NOT NULL, \n\twindow_seconds INTEGER, \n\tenabled BOOLEAN DEFAULT true NOT NULL, \n\trevision BIGINT DEFAULT 1 NOT NULL, \n\tid UUID NOT NULL, \n\tcreated_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL, \n\tupdated_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL, \n\tCONSTRAINT pk_runtime_limit_policies PRIMARY KEY (id), \n\tCONSTRAINT uq_runtime_limit_policies_subject_kind_limit_code UNIQUE (subject_kind, limit_code), \n\tCONSTRAINT ck_runtime_limit_policies_limits CHECK (value_limit >= 0 AND revision >= 1)\n)\n\n')
    op.execute("COMMENT ON TABLE runtime_limit_policies IS '受控模型技术上限'")
    op.execute("COMMENT ON COLUMN runtime_limit_policies.subject_kind IS 'user_default或instance'")
    op.execute("COMMENT ON COLUMN runtime_limit_policies.limit_code IS '注册限制维度'")
    op.execute("COMMENT ON COLUMN runtime_limit_policies.value_limit IS '0禁止新动作'")
    op.execute("COMMENT ON COLUMN runtime_limit_policies.window_seconds IS '窗口秒数'")
    op.execute("COMMENT ON COLUMN runtime_limit_policies.enabled IS '策略启停'")
    op.execute("COMMENT ON COLUMN runtime_limit_policies.revision IS '策略CAS'")
    op.execute("COMMENT ON COLUMN runtime_limit_policies.id IS '服务端生成的稳定标识'")
    op.execute("COMMENT ON COLUMN runtime_limit_policies.created_at IS '本行创建时间，UTC'")
    op.execute("COMMENT ON COLUMN runtime_limit_policies.updated_at IS '本行最近一次实际更新的时间，UTC'")
    op.execute("\nCREATE TABLE user_model_bindings (\n\tuser_id UUID NOT NULL, \n\tcapability VARCHAR(12) NOT NULL, \n\tcredential_id UUID NOT NULL, \n\tmodel_catalog_entry_id UUID NOT NULL, \n\tparameters_schema_version INTEGER DEFAULT 1 NOT NULL, \n\tparameters JSONB DEFAULT '{}'::jsonb NOT NULL, \n\tid UUID NOT NULL, \n\tcreated_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL, \n\tupdated_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL, \n\tCONSTRAINT pk_user_model_bindings PRIMARY KEY (id), \n\tCONSTRAINT uq_user_model_bindings_user_id_capability UNIQUE (user_id, capability)\n)\n\n")
    op.execute('CREATE INDEX ix_user_model_bindings_user_credential ON user_model_bindings (user_id, credential_id)')
    op.execute("COMMENT ON TABLE user_model_bindings IS '本人模型选择；settings_revision保护'")
    op.execute("COMMENT ON COLUMN user_model_bindings.user_id IS '本人'")
    op.execute("COMMENT ON COLUMN user_model_bindings.capability IS '能力'")
    op.execute("COMMENT ON COLUMN user_model_bindings.credential_id IS '本人凭据'")
    op.execute("COMMENT ON COLUMN user_model_bindings.model_catalog_entry_id IS '发布模型'")
    op.execute("COMMENT ON COLUMN user_model_bindings.parameters_schema_version IS '参数schema'")
    op.execute("COMMENT ON COLUMN user_model_bindings.parameters IS '有界合成参数'")
    op.execute("COMMENT ON COLUMN user_model_bindings.id IS '服务端生成的稳定标识'")
    op.execute("COMMENT ON COLUMN user_model_bindings.created_at IS '本行创建时间，UTC'")
    op.execute("COMMENT ON COLUMN user_model_bindings.updated_at IS '本行最近一次实际更新的时间，UTC'")
    op.execute("\nCREATE TABLE user_provider_credentials (\n\tuser_id UUID NOT NULL, \n\tprovider VARCHAR(24) NOT NULL, \n\tdisplay_label VARCHAR(100) NOT NULL, \n\tencrypted_secret BYTEA, \n\tencryption_key_version VARCHAR(64) NOT NULL, \n\tmasked_hint VARCHAR(32) NOT NULL, \n\tcredential_version BIGINT DEFAULT 1 NOT NULL, \n\trevision BIGINT DEFAULT 1 NOT NULL, \n\tstate VARCHAR(16) DEFAULT 'active' NOT NULL, \n\trevoked_at TIMESTAMP WITH TIME ZONE, \n\tid UUID NOT NULL, \n\tcreated_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL, \n\tupdated_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL, \n\tCONSTRAINT pk_user_provider_credentials PRIMARY KEY (id), \n\tCONSTRAINT ck_user_provider_credentials_provider CHECK (provider IN ('openrouter','gemini')), \n\tCONSTRAINT ck_user_provider_credentials_versions CHECK (revision >= 1 AND credential_version >= 1), \n\tCONSTRAINT ck_user_provider_credentials_state CHECK (state IN ('active','revoked') AND ((state='active' AND encrypted_secret IS NOT NULL AND revoked_at IS NULL) OR (state='revoked' AND encrypted_secret IS NULL AND revoked_at IS NOT NULL)))\n)\n\n")
    op.execute('CREATE INDEX ix_user_provider_credentials_user_state ON user_provider_credentials (user_id, state, created_at, id)')
    op.execute("COMMENT ON TABLE user_provider_credentials IS '本人供应商凭据密文与独立代次'")
    op.execute("COMMENT ON COLUMN user_provider_credentials.user_id IS '认证绑定本人'")
    op.execute("COMMENT ON COLUMN user_provider_credentials.provider IS '供应商'")
    op.execute("COMMENT ON COLUMN user_provider_credentials.display_label IS '本人标签'")
    op.execute("COMMENT ON COLUMN user_provider_credentials.encrypted_secret IS '独立部署密钥封装'")
    op.execute("COMMENT ON COLUMN user_provider_credentials.encryption_key_version IS '部署加密版本'")
    op.execute("COMMENT ON COLUMN user_provider_credentials.masked_hint IS '安全掩码'")
    op.execute("COMMENT ON COLUMN user_provider_credentials.credential_version IS '供应商秘密代次'")
    op.execute("COMMENT ON COLUMN user_provider_credentials.revision IS '行CAS版本'")
    op.execute("COMMENT ON COLUMN user_provider_credentials.state IS '使用状态'")
    op.execute("COMMENT ON COLUMN user_provider_credentials.revoked_at IS '撤销提交时间'")
    op.execute("COMMENT ON COLUMN user_provider_credentials.id IS '服务端生成的稳定标识'")
    op.execute("COMMENT ON COLUMN user_provider_credentials.created_at IS '本行创建时间，UTC'")
    op.execute("COMMENT ON COLUMN user_provider_credentials.updated_at IS '本行最近一次实际更新的时间，UTC'")
    op.execute('\nCREATE TABLE user_runtime_limits (\n\tuser_id UUID NOT NULL, \n\trevision BIGINT DEFAULT 1 NOT NULL, \n\tlimit_code VARCHAR(64) NOT NULL, \n\tvalue_limit BIGINT NOT NULL, \n\twindow_seconds INTEGER, \n\tid UUID NOT NULL, \n\tcreated_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL, \n\tupdated_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL, \n\tCONSTRAINT pk_user_runtime_limits PRIMARY KEY (id), \n\tCONSTRAINT uq_user_runtime_limits_user_id_limit_code UNIQUE (user_id, limit_code), \n\tCONSTRAINT ck_user_runtime_limits_limits CHECK (value_limit >= 0 AND revision >= 1)\n)\n\n')
    op.execute("COMMENT ON TABLE user_runtime_limits IS '本人技术保护覆盖；管理元数据'")
    op.execute("COMMENT ON COLUMN user_runtime_limits.user_id IS '目标账号'")
    op.execute("COMMENT ON COLUMN user_runtime_limits.revision IS '覆盖CAS'")
    op.execute("COMMENT ON COLUMN user_runtime_limits.limit_code IS '注册维度'")
    op.execute("COMMENT ON COLUMN user_runtime_limits.value_limit IS '个人限制；0拒新动作'")
    op.execute("COMMENT ON COLUMN user_runtime_limits.window_seconds IS '窗口秒数'")
    op.execute("COMMENT ON COLUMN user_runtime_limits.id IS '服务端生成的稳定标识'")
    op.execute("COMMENT ON COLUMN user_runtime_limits.created_at IS '本行创建时间，UTC'")
    op.execute("COMMENT ON COLUMN user_runtime_limits.updated_at IS '本行最近一次实际更新的时间，UTC'")
    op.execute('\nCREATE TABLE voice_catalog_entries (\n\tmodel_catalog_entry_id UUID NOT NULL, \n\tvoice_code VARCHAR(128) NOT NULL, \n\tlanguage_tag VARCHAR(35) NOT NULL, \n\tdisplay_name VARCHAR(100) NOT NULL, \n\tenabled BOOLEAN DEFAULT false NOT NULL, \n\tverified_at TIMESTAMP WITH TIME ZONE, \n\trevision BIGINT DEFAULT 1 NOT NULL, \n\tid UUID NOT NULL, \n\tcreated_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL, \n\tupdated_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL, \n\tCONSTRAINT pk_voice_catalog_entries PRIMARY KEY (id), \n\tCONSTRAINT uq_voice_catalog_entries_model_catalog_entry_id_vo_c0f0ccd30027 UNIQUE (model_catalog_entry_id, voice_code, language_tag)\n)\n\n')
    op.execute("COMMENT ON TABLE voice_catalog_entries IS '发布准确声音目录'")
    op.execute("COMMENT ON COLUMN voice_catalog_entries.model_catalog_entry_id IS '模型根'")
    op.execute("COMMENT ON COLUMN voice_catalog_entries.voice_code IS '声音标识'")
    op.execute("COMMENT ON COLUMN voice_catalog_entries.language_tag IS '语言'")
    op.execute("COMMENT ON COLUMN voice_catalog_entries.display_name IS '声音显示名'")
    op.execute("COMMENT ON COLUMN voice_catalog_entries.enabled IS '允许新合成'")
    op.execute("COMMENT ON COLUMN voice_catalog_entries.verified_at IS '真实协议证据'")
    op.execute("COMMENT ON COLUMN voice_catalog_entries.revision IS '目录版本'")
    op.execute("COMMENT ON COLUMN voice_catalog_entries.id IS '服务端生成的稳定标识'")
    op.execute("COMMENT ON COLUMN voice_catalog_entries.created_at IS '本行创建时间，UTC'")
    op.execute("COMMENT ON COLUMN voice_catalog_entries.updated_at IS '本行最近一次实际更新的时间，UTC'")
    op.execute('INSERT INTO model_catalog_entries (id,provider,model_code,display_name,capabilities,enabled,revision,adapter_code) VALUES (\'8e7fc0bc-1e65-5544-8629-cb594a74c8a1\',\'openrouter\',\'google/gemini-2.5-flash\',\'google/gemini-2.5-flash\',\'["text", "vision"]\'::jsonb,true,1,NULL)')
    op.execute('INSERT INTO model_catalog_entries (id,provider,model_code,display_name,capabilities,enabled,revision,adapter_code) VALUES (\'d0a1602b-55ce-579e-b623-789630cbee33\',\'openrouter\',\'google/gemini-3.8-flash-lite-tts\',\'google/gemini-3.8-flash-lite-tts\',\'["tts"]\'::jsonb,true,1,\'openrouter-gemini-speech-v1\')')
    op.execute('INSERT INTO model_catalog_entries (id,provider,model_code,display_name,capabilities,enabled,revision,adapter_code) VALUES (\'edd1190d-8903-59be-a7ae-f486fe44e050\',\'gemini\',\'gemini-2.5-flash\',\'gemini-2.5-flash\',\'["text", "vision"]\'::jsonb,false,1,NULL)')
    op.execute("INSERT INTO runtime_limit_policies (id,subject_kind,limit_code,value_limit,enabled,revision) VALUES ('dc4eda17-21bf-51bc-9694-e106f99883ec','user_default','max_credentials',10,true,1)")
    op.execute("INSERT INTO runtime_limit_policies (id,subject_kind,limit_code,value_limit,enabled,revision) VALUES ('5e4a6fa4-3d91-5b2b-a929-abf8c0130491','user_default','max_concurrent_jobs',1,true,1)")
    op.execute("INSERT INTO runtime_limit_policies (id,subject_kind,limit_code,value_limit,enabled,revision) VALUES ('1d6b3fc8-c17a-5580-b78b-a38ff8df7522','instance','instance_concurrent_jobs',4,true,1)")
    op.execute("INSERT INTO runtime_limit_policies (id,subject_kind,limit_code,value_limit,enabled,revision) VALUES ('f863744d-6ff6-59dd-82a3-969477fa28a5','user_default','max_model_calls',1,true,1)")
    op.execute("INSERT INTO runtime_limit_policies (id,subject_kind,limit_code,value_limit,enabled,revision) VALUES ('fbd43647-779d-591f-9371-2553672e021e','user_default','max_output_tokens',128,true,1)")
    op.execute("INSERT INTO runtime_limit_policies (id,subject_kind,limit_code,value_limit,enabled,revision) VALUES ('2fb2dea9-5567-5f60-908a-f92b75370b81','user_default','timeout_seconds',60,true,1)")
    op.execute("INSERT INTO runtime_limit_policies (id,subject_kind,limit_code,value_limit,enabled,revision) VALUES ('1676c663-5a3e-560f-b0c7-b3a66c227d84','user_default','tts_timeout_seconds',90,true,1)")
    op.execute("INSERT INTO runtime_limit_policies (id,subject_kind,limit_code,value_limit,enabled,revision) VALUES ('18577363-73a6-517d-ae8f-c082352074e6','user_default','max_test_image_bytes',4096,true,1)")
    op.execute("INSERT INTO runtime_limit_policies (id,subject_kind,limit_code,value_limit,enabled,revision) VALUES ('63d82931-e587-508b-a423-74bc4cefda3b','user_default','max_tts_characters',32,true,1)")
    op.execute("INSERT INTO runtime_limit_policies (id,subject_kind,limit_code,value_limit,enabled,revision) VALUES ('6cb071f9-1554-5333-8aca-221ff25a3ebd','user_default','websocket_max_jobs',100,true,1)")
    op.execute("INSERT INTO voice_catalog_entries (id,model_catalog_entry_id,voice_code,language_tag,display_name,enabled,revision) VALUES ('70236b47-d6fc-56b1-bbf4-f2ce5b7dd704','d0a1602b-55ce-579e-b623-789630cbee33','Kore','ja','Kore',true,1)")
    op.execute("INSERT INTO voice_catalog_entries (id,model_catalog_entry_id,voice_code,language_tag,display_name,enabled,revision) VALUES ('4fd8c1f4-9634-5648-8090-9e5912c424f8','d0a1602b-55ce-579e-b623-789630cbee33','Kore','en','Kore',true,1)")


def downgrade() -> None:
    raise RuntimeError("restore a matching backup; model attempts and secret history must not be discarded")
