"""Compatible private material sources, deterministic jobs and notification roots."""

import re

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision = "0014_material_sources"
down_revision = "0013_outbox_delivery_lease"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "material_import_issues",
        sa.Column("material_id", sa.UUID(), nullable=False, comment="共同材料父根"),
        sa.Column("material_revision_id", sa.UUID(), nullable=False, comment="待发布源版本"),
        sa.Column("file_object_id", sa.UUID(), nullable=False, comment="确切不可变原件"),
        sa.Column("job_id", sa.UUID(), nullable=False, comment="已受理无模型Job"),
        sa.Column("job_generation", sa.BigInteger(), nullable=False, comment="判断阶段代次"),
        sa.Column(
            "input_delete_generation", sa.BigInteger(), nullable=False, comment="输入材料删除代次"
        ),
        sa.Column("input_digest", sa.LargeBinary(), nullable=False, comment="确切判断输入摘要"),
        sa.Column("stage_code", sa.String(length=64), nullable=False, comment="注册语言判断阶段"),
        sa.Column("kind", sa.String(length=64), nullable=False, comment="语言确认原因种类"),
        sa.Column("severity", sa.String(length=16), nullable=False, comment="当前仅blocking"),
        sa.Column("status", sa.String(length=24), nullable=False, comment="open resolved accepted"),
        sa.Column(
            "source_refs",
            postgresql.JSONB(astext_type=sa.Text()),
            nullable=False,
            comment="有界出处与已保存提取结果引用，不含原文",
        ),
        sa.Column("schema_version", sa.Integer(), nullable=False, comment="Issue载荷版本1"),
        sa.Column(
            "revision",
            sa.BigInteger(),
            server_default=sa.text("1"),
            nullable=False,
            comment="确认CAS版本",
        ),
        sa.Column(
            "resolution_code", sa.String(length=64), nullable=True, comment="明确确认或确定修订代码"
        ),
        sa.Column(
            "resolved_by_user_id",
            sa.UUID(),
            nullable=True,
            comment="实际本人确认者，确定性修复可为空",
        ),
        sa.Column("resolved_at", sa.DateTime(timezone=True), nullable=True, comment="关闭提交UTC"),
        sa.Column("id", sa.UUID(), nullable=False, comment="服务端生成的稳定标识"),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
            comment="本行创建时间，UTC",
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
            comment="本行最近一次实际更新的时间，UTC",
        ),
        sa.Column("owner_user_id", sa.UUID(), nullable=False, comment="本人账号归属"),
        sa.Column("library_id", sa.UUID(), nullable=False, comment="本人资料库归属"),
        sa.CheckConstraint(
            "(status = 'open' AND resolution_code IS NULL AND resolved_by_user_id IS NULL AND resolved_at IS NULL) OR (status IN ('resolved','accepted') AND resolution_code IS NOT NULL AND resolved_at IS NOT NULL)",
            name=op.f("ck_material_import_issues_resolution"),
        ),
        sa.CheckConstraint(
            "kind = 'language_confirmation_required' AND stage_code = 'language_assessment' AND severity = 'blocking'",
            name=op.f("ck_material_import_issues_language_gate"),
        ),
        sa.CheckConstraint(
            "revision >= 1 AND schema_version = 1 AND job_generation >= 1 AND input_delete_generation >= 0 AND octet_length(input_digest) = 32",
            name=op.f("ck_material_import_issues_versions"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_material_import_issues")),
        comment="未发布源版本的语言确认Issue与实际输入检查点",
        info={
            "scope_kind": "library_owned",
            "owner_column": "owner_user_id",
            "lifecycle": "mutable",
            "allowed_entrances": ["authorized material import", "fenced source worker"],
            "deletion_policy": "release uncommitted reservation only after fencing publication; preserve accepted source references",
            "logical_relations": [
                {
                    "column": "owner_user_id",
                    "target": "users.id",
                    "nullable": False,
                    "scope_rule": "resolve from the authenticated owner; never trust a client owner identifier",
                    "state_rule": "check active parent and matching owner inside the write transaction",
                    "parent_lock": "current identity, users, user_storage_states, reservation, library, import, material, upload intent; same-kind parents by UUID",
                    "deletion": "restrict or explicitly detach",
                    "service": "app.services.material_imports",
                    "tests": "tests/integration/test_material_imports.py",
                },
                {
                    "column": "library_id",
                    "target": "libraries.id",
                    "nullable": False,
                    "scope_rule": "resolve from the authenticated owner; never trust a client owner identifier",
                    "state_rule": "check active parent and matching owner inside the write transaction",
                    "parent_lock": "current identity, users, user_storage_states, reservation, library, import, material, upload intent; same-kind parents by UUID",
                    "deletion": "restrict or explicitly detach",
                    "service": "app.services.material_imports",
                    "tests": "tests/integration/test_material_imports.py",
                },
                {
                    "column": "material_id",
                    "target": "materials.id",
                    "nullable": False,
                    "scope_rule": "resolve from the authenticated owner; never trust a client owner identifier",
                    "state_rule": "check active parent and matching owner inside the write transaction",
                    "parent_lock": "current identity, users, user_storage_states, reservation, library, import, material, upload intent; same-kind parents by UUID",
                    "deletion": "restrict or explicitly detach",
                    "service": "app.services.material_imports",
                    "tests": "tests/integration/test_material_imports.py",
                },
                {
                    "column": "material_revision_id",
                    "target": "material_revisions.id",
                    "nullable": False,
                    "scope_rule": "resolve from the authenticated owner; never trust a client owner identifier",
                    "state_rule": "check active parent and matching owner inside the write transaction",
                    "parent_lock": "current identity, users, user_storage_states, reservation, library, import, material, upload intent; same-kind parents by UUID",
                    "deletion": "restrict or explicitly detach",
                    "service": "app.services.material_imports",
                    "tests": "tests/integration/test_material_imports.py",
                },
                {
                    "column": "file_object_id",
                    "target": "file_objects.id",
                    "nullable": False,
                    "scope_rule": "resolve from the authenticated owner; never trust a client owner identifier",
                    "state_rule": "check active parent and matching owner inside the write transaction",
                    "parent_lock": "current identity, users, user_storage_states, reservation, library, import, material, upload intent; same-kind parents by UUID",
                    "deletion": "restrict or explicitly detach",
                    "service": "app.services.material_imports",
                    "tests": "tests/integration/test_material_imports.py",
                },
                {
                    "column": "job_id",
                    "target": "jobs.id",
                    "nullable": False,
                    "scope_rule": "resolve from the authenticated owner; never trust a client owner identifier",
                    "state_rule": "check active parent and matching owner inside the write transaction",
                    "parent_lock": "current identity, users, user_storage_states, reservation, library, import, material, upload intent; same-kind parents by UUID",
                    "deletion": "restrict or explicitly detach",
                    "service": "app.services.material_imports",
                    "tests": "tests/integration/test_material_imports.py",
                },
                {
                    "column": "resolved_by_user_id",
                    "target": "users.id",
                    "nullable": True,
                    "scope_rule": "resolve from the authenticated owner; never trust a client owner identifier",
                    "state_rule": "check active parent and matching owner inside the write transaction",
                    "parent_lock": "current identity, users, user_storage_states, reservation, library, import, material, upload intent; same-kind parents by UUID",
                    "deletion": "restrict or explicitly detach",
                    "service": "app.services.material_imports",
                    "tests": "tests/integration/test_material_imports.py",
                },
            ],
            "module": "material_imports",
        },
    )
    op.create_index(
        "ix_material_import_issues_owner_version_status",
        "material_import_issues",
        ["owner_user_id", "library_id", "material_revision_id", "status", "severity", "id"],
        unique=False,
    )
    op.create_table(
        "material_imports",
        sa.Column("material_type", sa.String(length=16), nullable=False, comment="固定材料类型"),
        sa.Column(
            "target_language",
            sa.String(length=35),
            nullable=False,
            comment="声明日语或英语；发布前重验",
        ),
        sa.Column("requested_title", sa.Text(), nullable=True, comment="用户显式标题"),
        sa.Column("reused_material_id", sa.UUID(), nullable=True, comment="本人被复用的来源材料根"),
        sa.Column(
            "reused_file_object_id", sa.UUID(), nullable=True, comment="源根锁内验证的不可变原件"
        ),
        sa.Column("primary_upload_intent_id", sa.UUID(), nullable=True, comment="本次原件上传意图"),
        sa.Column("schema_version", sa.Integer(), nullable=False, comment="载荷版本1"),
        sa.Column(
            "requested_stages",
            postgresql.JSONB(astext_type=sa.Text()),
            nullable=False,
            comment="明确仅确定性提取，无模型分析",
        ),
        sa.Column("status", sa.String(length=24), nullable=False, comment="导入意图状态"),
        sa.Column(
            "revision",
            sa.BigInteger(),
            server_default=sa.text("1"),
            nullable=False,
            comment="导入并发版本",
        ),
        sa.Column("idempotency_record_id", sa.UUID(), nullable=False, comment="本人动作幂等回执"),
        sa.Column("material_id", sa.UUID(), nullable=True, comment="原件验证后材料根"),
        sa.Column("initial_job_id", sa.UUID(), nullable=True, comment="无模型来源Job"),
        sa.Column(
            "expires_at", sa.DateTime(timezone=True), nullable=False, comment="待上传截止UTC"
        ),
        sa.Column("id", sa.UUID(), nullable=False, comment="服务端生成的稳定标识"),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
            comment="本行创建时间，UTC",
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
            comment="本行最近一次实际更新的时间，UTC",
        ),
        sa.Column("owner_user_id", sa.UUID(), nullable=False, comment="本人账号归属"),
        sa.Column("library_id", sa.UUID(), nullable=False, comment="本人资料库归属"),
        sa.CheckConstraint(
            "(material_id IS NULL AND initial_job_id IS NULL AND status != 'accepted') OR (material_id IS NOT NULL AND initial_job_id IS NOT NULL AND status = 'accepted')",
            name=op.f("ck_material_imports_accepted_results"),
        ),
        sa.CheckConstraint(
            "material_type IN ('novel','textbook','exam') AND target_language IN ('ja','en')",
            name=op.f("ck_material_imports_type_language"),
        ),
        sa.CheckConstraint(
            "status IN ('awaiting_upload','verifying','accepted','expired','cancelled','rejected')",
            name=op.f("ck_material_imports_status"),
        ),
        sa.CheckConstraint(
            "(primary_upload_intent_id IS NOT NULL AND reused_material_id IS NULL AND reused_file_object_id IS NULL) OR (primary_upload_intent_id IS NULL AND reused_material_id IS NOT NULL AND reused_file_object_id IS NOT NULL)",
            name=op.f("ck_material_imports_source_choice"),
        ),
        sa.CheckConstraint(
            'requested_stages = \'{"extract": true, "analyze": false}\'::jsonb',
            name=op.f("ck_material_imports_requested_stages"),
        ),
        sa.CheckConstraint(
            "revision >= 1 AND schema_version = 1", name=op.f("ck_material_imports_versions")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_material_imports")),
        sa.UniqueConstraint(
            "owner_user_id",
            "idempotency_record_id",
            name=op.f("uq_material_imports_owner_user_id_idempotency_record_id"),
        ),
        comment="三类材料的显式无模型源导入意图",
        info={
            "scope_kind": "library_owned",
            "owner_column": "owner_user_id",
            "lifecycle": "mutable",
            "allowed_entrances": ["authorized material import", "fenced source worker"],
            "deletion_policy": "release uncommitted reservation only after fencing publication; preserve accepted source references",
            "logical_relations": [
                {
                    "column": "owner_user_id",
                    "target": "users.id",
                    "nullable": False,
                    "scope_rule": "resolve from the authenticated owner; never trust a client owner identifier",
                    "state_rule": "check active parent and matching owner inside the write transaction",
                    "parent_lock": "current identity, users, user_storage_states, reservation, library, import, material, upload intent; same-kind parents by UUID",
                    "deletion": "restrict or explicitly detach",
                    "service": "app.services.material_imports",
                    "tests": "tests/integration/test_material_imports.py",
                },
                {
                    "column": "library_id",
                    "target": "libraries.id",
                    "nullable": False,
                    "scope_rule": "resolve from the authenticated owner; never trust a client owner identifier",
                    "state_rule": "check active parent and matching owner inside the write transaction",
                    "parent_lock": "current identity, users, user_storage_states, reservation, library, import, material, upload intent; same-kind parents by UUID",
                    "deletion": "restrict or explicitly detach",
                    "service": "app.services.material_imports",
                    "tests": "tests/integration/test_material_imports.py",
                },
                {
                    "column": "primary_upload_intent_id",
                    "target": "upload_intents.id",
                    "nullable": True,
                    "scope_rule": "resolve from the authenticated owner; never trust a client owner identifier",
                    "state_rule": "check active parent and matching owner inside the write transaction",
                    "parent_lock": "current identity, users, user_storage_states, reservation, library, import, material, upload intent; same-kind parents by UUID",
                    "deletion": "restrict or explicitly detach",
                    "service": "app.services.material_imports",
                    "tests": "tests/integration/test_material_imports.py",
                },
                {
                    "column": "reused_material_id",
                    "target": "materials.id",
                    "nullable": True,
                    "scope_rule": "resolve from the authenticated owner; never trust a client owner identifier",
                    "state_rule": "check active parent and matching owner inside the write transaction",
                    "parent_lock": "current identity, users, user_storage_states, reservation, library, import, material, upload intent; same-kind parents by UUID",
                    "deletion": "restrict or explicitly detach",
                    "service": "app.services.material_imports",
                    "tests": "tests/integration/test_material_imports.py",
                },
                {
                    "column": "reused_file_object_id",
                    "target": "file_objects.id",
                    "nullable": True,
                    "scope_rule": "resolve from the authenticated owner; never trust a client owner identifier",
                    "state_rule": "check active parent and matching owner inside the write transaction",
                    "parent_lock": "current identity, users, user_storage_states, reservation, library, import, material, upload intent; same-kind parents by UUID",
                    "deletion": "restrict or explicitly detach",
                    "service": "app.services.material_imports",
                    "tests": "tests/integration/test_material_imports.py",
                },
                {
                    "column": "idempotency_record_id",
                    "target": "idempotency_records.id",
                    "nullable": False,
                    "scope_rule": "resolve from the authenticated owner; never trust a client owner identifier",
                    "state_rule": "check active parent and matching owner inside the write transaction",
                    "parent_lock": "current identity, users, user_storage_states, reservation, library, import, material, upload intent; same-kind parents by UUID",
                    "deletion": "restrict or explicitly detach",
                    "service": "app.services.material_imports",
                    "tests": "tests/integration/test_material_imports.py",
                },
                {
                    "column": "material_id",
                    "target": "materials.id",
                    "nullable": True,
                    "scope_rule": "resolve from the authenticated owner; never trust a client owner identifier",
                    "state_rule": "check active parent and matching owner inside the write transaction",
                    "parent_lock": "current identity, users, user_storage_states, reservation, library, import, material, upload intent; same-kind parents by UUID",
                    "deletion": "restrict or explicitly detach",
                    "service": "app.services.material_imports",
                    "tests": "tests/integration/test_material_imports.py",
                },
                {
                    "column": "initial_job_id",
                    "target": "jobs.id",
                    "nullable": True,
                    "scope_rule": "resolve from the authenticated owner; never trust a client owner identifier",
                    "state_rule": "check active parent and matching owner inside the write transaction",
                    "parent_lock": "current identity, users, user_storage_states, reservation, library, import, material, upload intent; same-kind parents by UUID",
                    "deletion": "restrict or explicitly detach",
                    "service": "app.services.material_imports",
                    "tests": "tests/integration/test_material_imports.py",
                },
            ],
            "module": "material_imports",
        },
    )
    op.create_index(
        "ix_material_imports_owner_status",
        "material_imports",
        ["owner_user_id", "library_id", "status", "created_at", "id"],
        unique=False,
    )
    op.create_table(
        "material_source_assets",
        sa.Column("material_id", sa.UUID(), nullable=False, comment="共同材料父根"),
        sa.Column(
            "material_revision_id", sa.UUID(), nullable=False, comment="确切候选或发布源版本"
        ),
        sa.Column("file_object_id", sa.UUID(), nullable=False, comment="本人的不可变已验证原件"),
        sa.Column("purpose", sa.String(length=40), nullable=False, comment="当前主文档资产角色"),
        sa.Column("ordinal", sa.Integer(), nullable=False, comment="版本内资产正序号"),
        sa.Column(
            "source_locator",
            postgresql.JSONB(astext_type=sa.Text()),
            nullable=True,
            comment="仅验证过的原件位置",
        ),
        sa.Column("pixel_width", sa.Integer(), nullable=True, comment="实际图像宽；文字源为空"),
        sa.Column("pixel_height", sa.Integer(), nullable=True, comment="实际图像高；文字源为空"),
        sa.Column(
            "duration_ms", sa.BigInteger(), nullable=True, comment="实际媒体时长；主文档为空"
        ),
        sa.Column("id", sa.UUID(), nullable=False, comment="服务端生成的稳定标识"),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
            comment="本行创建时间，UTC",
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
            comment="本行最近一次实际更新的时间，UTC",
        ),
        sa.Column("owner_user_id", sa.UUID(), nullable=False, comment="本人账号归属"),
        sa.Column("library_id", sa.UUID(), nullable=False, comment="本人资料库归属"),
        sa.CheckConstraint(
            "ordinal > 0 AND purpose = 'primary_document'",
            name=op.f("ck_material_source_assets_source_role"),
        ),
        sa.CheckConstraint(
            "(pixel_width IS NULL AND pixel_height IS NULL) OR (pixel_width IS NOT NULL AND pixel_height IS NOT NULL AND pixel_width > 0 AND pixel_height > 0)",
            name=op.f("ck_material_source_assets_pixels"),
        ),
        sa.CheckConstraint(
            "duration_ms IS NULL OR duration_ms >= 0",
            name=op.f("ck_material_source_assets_duration"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_material_source_assets")),
        sa.UniqueConstraint(
            "owner_user_id",
            "library_id",
            "material_revision_id",
            "ordinal",
            name="uq_material_source_asset_version_ordinal",
        ),
        comment="确切源版本的本人不可变主文档资产",
        info={
            "scope_kind": "library_owned",
            "owner_column": "owner_user_id",
            "lifecycle": "mutable",
            "allowed_entrances": ["authorized material import", "fenced source worker"],
            "deletion_policy": "release uncommitted reservation only after fencing publication; preserve accepted source references",
            "logical_relations": [
                {
                    "column": "owner_user_id",
                    "target": "users.id",
                    "nullable": False,
                    "scope_rule": "resolve from the authenticated owner; never trust a client owner identifier",
                    "state_rule": "check active parent and matching owner inside the write transaction",
                    "parent_lock": "current identity, users, user_storage_states, reservation, library, import, material, upload intent; same-kind parents by UUID",
                    "deletion": "restrict or explicitly detach",
                    "service": "app.services.material_imports",
                    "tests": "tests/integration/test_material_imports.py",
                },
                {
                    "column": "library_id",
                    "target": "libraries.id",
                    "nullable": False,
                    "scope_rule": "resolve from the authenticated owner; never trust a client owner identifier",
                    "state_rule": "check active parent and matching owner inside the write transaction",
                    "parent_lock": "current identity, users, user_storage_states, reservation, library, import, material, upload intent; same-kind parents by UUID",
                    "deletion": "restrict or explicitly detach",
                    "service": "app.services.material_imports",
                    "tests": "tests/integration/test_material_imports.py",
                },
                {
                    "column": "material_id",
                    "target": "materials.id",
                    "nullable": False,
                    "scope_rule": "resolve from the authenticated owner; never trust a client owner identifier",
                    "state_rule": "check active parent and matching owner inside the write transaction",
                    "parent_lock": "current identity, users, user_storage_states, reservation, library, import, material, upload intent; same-kind parents by UUID",
                    "deletion": "restrict or explicitly detach",
                    "service": "app.services.material_imports",
                    "tests": "tests/integration/test_material_imports.py",
                },
                {
                    "column": "material_revision_id",
                    "target": "material_revisions.id",
                    "nullable": False,
                    "scope_rule": "resolve from the authenticated owner; never trust a client owner identifier",
                    "state_rule": "check active parent and matching owner inside the write transaction",
                    "parent_lock": "current identity, users, user_storage_states, reservation, library, import, material, upload intent; same-kind parents by UUID",
                    "deletion": "restrict or explicitly detach",
                    "service": "app.services.material_imports",
                    "tests": "tests/integration/test_material_imports.py",
                },
                {
                    "column": "file_object_id",
                    "target": "file_objects.id",
                    "nullable": False,
                    "scope_rule": "resolve from the authenticated owner; never trust a client owner identifier",
                    "state_rule": "check active parent and matching owner inside the write transaction",
                    "parent_lock": "current identity, users, user_storage_states, reservation, library, import, material, upload intent; same-kind parents by UUID",
                    "deletion": "restrict or explicitly detach",
                    "service": "app.services.material_imports",
                    "tests": "tests/integration/test_material_imports.py",
                },
            ],
            "module": "material_imports",
        },
    )
    op.create_index(
        "ix_material_source_assets_owner_file",
        "material_source_assets",
        ["owner_user_id", "library_id", "file_object_id", "id"],
        unique=False,
    )
    op.create_table(
        "user_notifications",
        sa.Column("source_event_id", sa.UUID(), nullable=False, comment="已提交源事件"),
        sa.Column("job_id", sa.UUID(), nullable=False, comment="本人材料任务"),
        sa.Column(
            "notification_kind",
            sa.String(length=24),
            nullable=False,
            comment="completed failed needs_review",
        ),
        sa.Column("resource_kind", sa.String(length=32), nullable=False, comment="当前仅material"),
        sa.Column("resource_id", sa.UUID(), nullable=False, comment="本人材料根"),
        sa.Column(
            "resource_version", sa.BigInteger(), nullable=False, comment="事件提交时资源版本"
        ),
        sa.Column(
            "message_code", sa.String(length=96), nullable=False, comment="注册的提示文案代码"
        ),
        sa.Column("schema_version", sa.Integer(), nullable=False, comment="安全载荷版本1"),
        sa.Column(
            "safe_parameters",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default=sa.text("'{}'::jsonb"),
            nullable=False,
            comment="当前不含正文标题或任意参数",
        ),
        sa.Column("sequence", sa.BigInteger(), nullable=False, comment="同库根锁内分配的提交序号"),
        sa.Column(
            "read_at", sa.DateTime(timezone=True), nullable=True, comment="首次实际已读提交UTC"
        ),
        sa.Column(
            "revision",
            sa.BigInteger(),
            server_default=sa.text("1"),
            nullable=False,
            comment="消息状态版本",
        ),
        sa.Column("id", sa.UUID(), nullable=False, comment="服务端生成的稳定标识"),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
            comment="本行创建时间，UTC",
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
            comment="本行最近一次实际更新的时间，UTC",
        ),
        sa.Column("owner_user_id", sa.UUID(), nullable=False, comment="本人账号归属"),
        sa.Column("library_id", sa.UUID(), nullable=False, comment="本人资料库归属"),
        sa.CheckConstraint(
            "notification_kind IN ('completed','failed','needs_review') AND resource_kind = 'material'",
            name=op.f("ck_user_notifications_kind"),
        ),
        sa.CheckConstraint(
            "safe_parameters = '{}'::jsonb", name=op.f("ck_user_notifications_safe_parameters")
        ),
        sa.CheckConstraint(
            "revision >= 1 AND resource_version >= 1 AND sequence > 0 AND schema_version = 1",
            name=op.f("ck_user_notifications_versions"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_user_notifications")),
        sa.UniqueConstraint(
            "owner_user_id", "sequence", name=op.f("uq_user_notifications_owner_user_id_sequence")
        ),
        sa.UniqueConstraint(
            "owner_user_id",
            "source_event_id",
            "notification_kind",
            name="uq_user_notification_owner_event_kind",
        ),
        comment="仅已提交本人材料任务的安全提示",
        info={
            "scope_kind": "library_owned",
            "owner_column": "owner_user_id",
            "lifecycle": "mutable",
            "allowed_entrances": [
                "committed job event consumer",
                "authorized private notification API",
            ],
            "deletion_policy": "retain private safe receipt; never revive unavailable resource",
            "logical_relations": [
                {
                    "column": "owner_user_id",
                    "target": "users.id",
                    "nullable": False,
                    "scope_rule": "resolve from the authenticated owner; never trust a client owner identifier",
                    "state_rule": "check active parent and matching owner inside the write transaction",
                    "parent_lock": "current identity then library root, material root, job; same-kind parents by UUID",
                    "deletion": "restrict or explicitly detach",
                    "service": "app.services.user_notifications",
                    "tests": "tests/integration/test_user_notifications.py",
                },
                {
                    "column": "library_id",
                    "target": "libraries.id",
                    "nullable": False,
                    "scope_rule": "resolve from the authenticated owner; never trust a client owner identifier",
                    "state_rule": "check active parent and matching owner inside the write transaction",
                    "parent_lock": "current identity then library root, material root, job; same-kind parents by UUID",
                    "deletion": "restrict or explicitly detach",
                    "service": "app.services.user_notifications",
                    "tests": "tests/integration/test_user_notifications.py",
                },
                {
                    "column": "job_id",
                    "target": "jobs.id",
                    "nullable": False,
                    "scope_rule": "resolve from the authenticated owner; never trust a client owner identifier",
                    "state_rule": "check active parent and matching owner inside the write transaction",
                    "parent_lock": "current identity then library root, material root, job; same-kind parents by UUID",
                    "deletion": "restrict or explicitly detach",
                    "service": "app.services.user_notifications",
                    "tests": "tests/integration/test_user_notifications.py",
                },
                {
                    "column": "resource_id",
                    "target": "materials.id",
                    "nullable": False,
                    "scope_rule": "resolve from the authenticated owner; never trust a client owner identifier",
                    "state_rule": "check active parent and matching owner inside the write transaction",
                    "parent_lock": "current identity then library root, material root, job; same-kind parents by UUID",
                    "deletion": "restrict or explicitly detach",
                    "service": "app.services.user_notifications",
                    "tests": "tests/integration/test_user_notifications.py",
                },
                {
                    "column": "source_event_id",
                    "target": "outbox_events.id",
                    "nullable": False,
                    "scope_rule": "resolve from the authenticated owner; never trust a client owner identifier",
                    "state_rule": "check active parent and matching owner inside the write transaction",
                    "parent_lock": "current identity then library root, material root, job; same-kind parents by UUID",
                    "deletion": "restrict or explicitly detach",
                    "service": "app.services.user_notifications",
                    "tests": "tests/integration/test_user_notifications.py",
                },
            ],
            "module": "user_notifications",
        },
    )
    op.create_index(
        "ix_user_notifications_owner_created",
        "user_notifications",
        ["owner_user_id", "created_at", "id"],
        unique=False,
    )
    op.create_index(
        "ix_user_notifications_owner_unread",
        "user_notifications",
        ["owner_user_id", "read_at", "sequence"],
        unique=False,
        postgresql_where=sa.text("read_at IS NULL"),
    )
    op.create_table(
        "user_storage_reservations",
        sa.Column("user_id", sa.UUID(), nullable=False, comment="当前账号"),
        sa.Column("target_kind", sa.String(length=40), nullable=False, comment="上传意图目标"),
        sa.Column("target_resource_id", sa.UUID(), nullable=False, comment="本人上传意图"),
        sa.Column("reserved_bytes", sa.BigInteger(), nullable=False, comment="承诺字节"),
        sa.Column(
            "committed_bytes",
            sa.BigInteger(),
            server_default=sa.text("0"),
            nullable=False,
            comment="发布后结算字节",
        ),
        sa.Column(
            "status", sa.String(length=24), nullable=False, comment="reserved committed released"
        ),
        sa.Column(
            "revision",
            sa.BigInteger(),
            server_default=sa.text("1"),
            nullable=False,
            comment="预留版本",
        ),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=False, comment="预留截止UTC"),
        sa.Column("id", sa.UUID(), nullable=False, comment="服务端生成的稳定标识"),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
            comment="本行创建时间，UTC",
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
            comment="本行最近一次实际更新的时间，UTC",
        ),
        sa.CheckConstraint(
            "(status = 'committed' AND committed_bytes > 0) OR (status != 'committed' AND committed_bytes = 0)",
            name=op.f("ck_user_storage_reservations_settlement"),
        ),
        sa.CheckConstraint(
            "status IN ('reserved','committed','released')",
            name=op.f("ck_user_storage_reservations_status"),
        ),
        sa.CheckConstraint(
            "target_kind = 'upload_intent'", name=op.f("ck_user_storage_reservations_target_kind")
        ),
        sa.CheckConstraint(
            "reserved_bytes > 0 AND committed_bytes >= 0 AND revision >= 1",
            name=op.f("ck_user_storage_reservations_counts"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_user_storage_reservations")),
        sa.UniqueConstraint(
            "user_id",
            "target_kind",
            "target_resource_id",
            name="uq_storage_reservation_owner_target",
        ),
        comment="一次上传意图的本人幂等容量预留",
        info={
            "scope_kind": "user_owned",
            "owner_column": "user_id",
            "lifecycle": "mutable",
            "allowed_entrances": ["authorized material import", "fenced source worker"],
            "deletion_policy": "release uncommitted reservation only after fencing publication; preserve accepted source references",
            "logical_relations": [
                {
                    "column": "user_id",
                    "target": "users.id",
                    "nullable": False,
                    "scope_rule": "resolve from the authenticated owner; never trust a client owner identifier",
                    "state_rule": "check active parent and matching owner inside the write transaction",
                    "parent_lock": "current identity, users, user_storage_states, reservation, library, import, material, upload intent; same-kind parents by UUID",
                    "deletion": "restrict or explicitly detach",
                    "service": "app.services.material_imports",
                    "tests": "tests/integration/test_material_imports.py",
                },
                {
                    "column": "target_resource_id",
                    "target": "upload_intents.id",
                    "nullable": False,
                    "scope_rule": "resolve from the authenticated owner; never trust a client owner identifier",
                    "state_rule": "check active parent and matching owner inside the write transaction",
                    "parent_lock": "current identity, users, user_storage_states, reservation, library, import, material, upload intent; same-kind parents by UUID",
                    "deletion": "restrict or explicitly detach",
                    "service": "app.services.material_imports",
                    "tests": "tests/integration/test_material_imports.py",
                },
            ],
            "module": "material_imports",
        },
    )
    op.create_index(
        "ix_user_storage_reservations_owner_status",
        "user_storage_reservations",
        ["user_id", "status", "expires_at", "id"],
        unique=False,
    )
    op.create_table(
        "user_storage_states",
        sa.Column("user_id", sa.UUID(), nullable=False, comment="当前账号"),
        sa.Column(
            "used_bytes",
            sa.BigInteger(),
            server_default=sa.text("0"),
            nullable=False,
            comment="保留的已发布实际字节",
        ),
        sa.Column(
            "reserved_bytes",
            sa.BigInteger(),
            server_default=sa.text("0"),
            nullable=False,
            comment="尚未结算的承诺字节",
        ),
        sa.Column(
            "revision",
            sa.BigInteger(),
            server_default=sa.text("1"),
            nullable=False,
            comment="容量计数版本",
        ),
        sa.Column("id", sa.UUID(), nullable=False, comment="服务端生成的稳定标识"),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
            comment="本行创建时间，UTC",
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
            comment="本行最近一次实际更新的时间，UTC",
        ),
        sa.CheckConstraint(
            "used_bytes >= 0 AND reserved_bytes >= 0 AND revision >= 1",
            name=op.f("ck_user_storage_states_counts"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_user_storage_states")),
        sa.UniqueConstraint("user_id", name=op.f("uq_user_storage_states_user_id")),
        comment="本人已发布字节及在途容量的锁根",
        info={
            "scope_kind": "user_owned",
            "owner_column": "user_id",
            "lifecycle": "mutable",
            "allowed_entrances": ["authorized material import", "fenced source worker"],
            "deletion_policy": "release uncommitted reservation only after fencing publication; preserve accepted source references",
            "logical_relations": [
                {
                    "column": "user_id",
                    "target": "users.id",
                    "nullable": False,
                    "scope_rule": "resolve from the authenticated owner; never trust a client owner identifier",
                    "state_rule": "check active parent and matching owner inside the write transaction",
                    "parent_lock": "current identity, users, user_storage_states, reservation, library, import, material, upload intent; same-kind parents by UUID",
                    "deletion": "restrict or explicitly detach",
                    "service": "app.services.material_imports",
                    "tests": "tests/integration/test_material_imports.py",
                }
            ],
            "module": "material_imports",
        },
    )
    op.add_column(
        "file_objects",
        sa.Column("bucket_name", sa.Text(), nullable=True, comment="材料私有bucket，旧头像为空"),
    )
    op.add_column(
        "file_objects",
        sa.Column("object_key", sa.Text(), nullable=True, comment="只有服务端可写的材料final键"),
    )
    op.alter_column(
        "file_objects",
        "pixel_width",
        existing_type=sa.INTEGER(),
        nullable=True,
        existing_comment="成品正方形边长",
    )
    op.alter_column(
        "file_objects",
        "pixel_height",
        existing_type=sa.INTEGER(),
        nullable=True,
        existing_comment="成品正方形边长，与宽度相等",
    )
    op.alter_column(
        "file_objects",
        "content",
        existing_type=postgresql.BYTEA(),
        nullable=True,
        existing_comment="去元数据后的正方形JPEG，不记录原始文件",
    )
    op.create_index(
        "ix_file_objects_final_key_unique",
        "file_objects",
        ["bucket_name", "object_key"],
        unique=True,
        postgresql_where=sa.text("object_key IS NOT NULL"),
    )
    op.alter_column(
        "jobs",
        "credential_id",
        existing_type=sa.UUID(),
        nullable=True,
        comment="模型任务本人凭据；确定性材料任务为空",
        existing_comment="本人凭据引用",
    )
    op.alter_column(
        "jobs",
        "run_id",
        existing_type=sa.UUID(),
        nullable=True,
        comment="模型运行引用；确定性材料任务为空",
        existing_comment="运行引用",
    )
    op.add_column(
        "libraries",
        sa.Column(
            "notification_sequence",
            sa.BigInteger(),
            server_default=sa.text("0"),
            nullable=False,
            comment="本人通知在库根锁内分配的持久提交序号",
        ),
    )
    op.add_column(
        "material_revisions",
        sa.Column(
            "source_schema_version",
            sa.Integer(),
            server_default=sa.text("1"),
            nullable=False,
            comment="来源契约版本1",
        ),
    )
    op.add_column(
        "material_revisions",
        sa.Column(
            "processor_version",
            sa.String(length=80),
            server_default=sa.text("'legacy-novel-source-v1'"),
            nullable=False,
            comment="确定性源处理器版本；旧小说保留身份",
        ),
    )
    op.add_column(
        "material_revisions",
        sa.Column(
            "material_type",
            sa.String(length=16),
            server_default=sa.text("'novel'"),
            nullable=False,
            comment="固定类型，由所属材料派生",
        ),
    )
    op.add_column(
        "material_revisions",
        sa.Column(
            "origin_job_id", sa.UUID(), nullable=True, comment="新导入来源Job，旧受控小说无Job"
        ),
    )
    op.add_column(
        "material_revisions",
        sa.Column("parent_revision_id", sa.UUID(), nullable=True, comment="同材料上一源版本"),
    )
    op.add_column(
        "material_revisions",
        sa.Column(
            "content_digest", sa.LargeBinary(), nullable=True, comment="已发布源结构摘要；候选为空"
        ),
    )
    op.add_column(
        "material_revisions",
        sa.Column(
            "structure_published_at",
            sa.DateTime(timezone=True),
            nullable=True,
            comment="新结构首次可读发布时间，独立于源发布",
        ),
    )
    op.alter_column(
        "material_revisions",
        "structure_status",
        existing_type=sa.VARCHAR(length=24),
        nullable=True,
        comment="小说课本结构状态；试卷无通用结构",
        existing_comment="小说结构可读状态",
    )
    op.alter_column(
        "material_revisions",
        "published_at",
        existing_type=postgresql.TIMESTAMP(timezone=True),
        nullable=True,
        comment="来源实际发布UTC；building候选为空",
        existing_comment="来源与结构实际发布时间",
    )
    op.create_index(
        "ix_material_revisions_owner_material_status",
        "material_revisions",
        ["owner_user_id", "library_id", "material_id", "status", "id"],
        unique=False,
    )
    op.add_column(
        "materials",
        sa.Column(
            "title_origin",
            sa.String(length=24),
            server_default=sa.text("'user'"),
            nullable=False,
            comment="标题来自filename extracted或user",
        ),
    )
    op.add_column(
        "materials",
        sa.Column(
            "source_format",
            sa.String(length=32),
            nullable=True,
            comment="验证源格式，旧受控小说无文件为空",
        ),
    )
    op.add_column(
        "materials",
        sa.Column(
            "primary_file_object_id",
            sa.UUID(),
            nullable=True,
            comment="本人不可变主原件；旧受控小说为空",
        ),
    )
    op.add_column(
        "materials",
        sa.Column(
            "initial_job_id", sa.UUID(), nullable=True, comment="源受理无模型Job；旧来源为空"
        ),
    )
    op.add_column(
        "materials",
        sa.Column(
            "analysis_status",
            sa.String(length=32),
            server_default=sa.text("'not_requested'"),
            nullable=False,
            comment="额外分析状态独立于源可用性",
        ),
    )
    op.create_index(
        "ix_materials_owner_library_language_updated",
        "materials",
        ["owner_user_id", "library_id", "language", "updated_at", "id"],
        unique=False,
        postgresql_where=sa.text("deleted_at IS NULL"),
    )
    op.create_index(
        "ix_materials_owner_library_type_updated",
        "materials",
        ["owner_user_id", "library_id", "material_type", "updated_at", "id"],
        unique=False,
        postgresql_where=sa.text("deleted_at IS NULL"),
    )
    op.add_column(
        "upload_intents",
        sa.Column(
            "revision",
            sa.BigInteger(),
            server_default=sa.text("1"),
            nullable=False,
            comment="上传意图版本",
        ),
    )
    op.add_column(
        "upload_intents",
        sa.Column(
            "material_type", sa.String(length=16), nullable=True, comment="仅主文件为三类之一"
        ),
    )
    op.add_column(
        "upload_intents",
        sa.Column(
            "original_filename", sa.Text(), nullable=True, comment="仅显示原文件名，不作为对象路径"
        ),
    )
    op.add_column(
        "upload_intents",
        sa.Column("storage_reservation_id", sa.UUID(), nullable=True, comment="主文件本人容量预留"),
    )
    op.add_column(
        "upload_intents",
        sa.Column("staging_object_key", sa.Text(), nullable=True, comment="本人独占临时键"),
    )
    op.add_column(
        "upload_intents",
        sa.Column(
            "completion_generation",
            sa.BigInteger(),
            server_default=sa.text("0"),
            nullable=False,
            comment="完成领取代次",
        ),
    )
    op.add_column(
        "upload_intents",
        sa.Column("completion_lease_token", sa.UUID(), nullable=True, comment="完成租约fence"),
    )
    op.add_column(
        "upload_intents",
        sa.Column(
            "completion_lease_until_at",
            sa.DateTime(timezone=True),
            nullable=True,
            comment="完成租约UTC截止",
        ),
    )
    op.add_column(
        "upload_intents",
        sa.Column(
            "candidate_final_object_key",
            sa.Text(),
            nullable=True,
            comment="本代次服务端独占固定副本键",
        ),
    )
    op.create_index(
        "ix_upload_intents_final_candidate_unique",
        "upload_intents",
        ["candidate_final_object_key"],
        unique=True,
        postgresql_where=sa.text("candidate_final_object_key IS NOT NULL"),
    )
    op.create_index(
        "ix_upload_intents_staging_unique",
        "upload_intents",
        ["staging_object_key"],
        unique=True,
        postgresql_where=sa.text("staging_object_key IS NOT NULL"),
    )
    op.drop_constraint(op.f("ck_file_objects_square_pixels"), "file_objects", type_="check")
    op.drop_constraint(op.f("ck_file_objects_purpose"), "file_objects", type_="check")
    op.drop_constraint(op.f("ck_file_objects_content_digest"), "file_objects", type_="check")
    op.drop_constraint(op.f("ck_file_objects_media_type"), "file_objects", type_="check")
    op.drop_constraint(op.f("ck_file_objects_format_code"), "file_objects", type_="check")
    op.drop_constraint(op.f("ck_file_objects_processor"), "file_objects", type_="check")
    op.create_check_constraint(
        op.f("ck_file_objects_content_digest"),
        "file_objects",
        "octet_length(sha256) = 32 AND size_bytes > 0 AND ((purpose = 'avatar' AND content IS NOT NULL AND octet_length(content) = size_bytes AND size_bytes <= 1048576 AND bucket_name IS NULL AND object_key IS NULL) OR (purpose = 'primary_document' AND content IS NULL AND bucket_name IS NOT NULL AND object_key IS NOT NULL))",
    )
    op.create_check_constraint(
        op.f("ck_file_objects_format_code"),
        "file_objects",
        "(purpose = 'avatar' AND format_code = 'jpeg') OR (purpose = 'primary_document' AND format_code IN ('md','epub','pdf','png','jpeg','webp'))",
    )
    op.create_check_constraint(
        op.f("ck_file_objects_processor"),
        "file_objects",
        "(purpose = 'avatar' AND validation_profile = 'avatar-image-v1' AND processor_version = 'avatar-jpeg-square-v1') OR (purpose = 'primary_document' AND validation_profile = 'material-source-v1' AND processor_version = 'immutable-source-v1')",
    )
    op.create_check_constraint(
        op.f("ck_file_objects_square_pixels"),
        "file_objects",
        "purpose != 'avatar' OR (pixel_width IS NOT NULL AND pixel_height IS NOT NULL AND pixel_width = pixel_height AND pixel_width BETWEEN 1 AND 512)",
    )
    op.create_check_constraint(
        op.f("ck_file_objects_pixel_pair"),
        "file_objects",
        "(pixel_width IS NULL AND pixel_height IS NULL) OR (pixel_width IS NOT NULL AND pixel_height IS NOT NULL AND pixel_width > 0 AND pixel_height > 0)",
    )
    op.create_check_constraint(
        op.f("ck_file_objects_purpose"), "file_objects", "purpose IN ('avatar','primary_document')"
    )
    op.create_check_constraint(
        op.f("ck_file_objects_media_type"),
        "file_objects",
        "purpose != 'avatar' OR media_type = 'image/jpeg'",
    )
    op.drop_constraint(
        op.f("ck_idempotency_records_learning_committed_result"),
        "idempotency_records",
        type_="check",
    )
    op.create_check_constraint(
        op.f("ck_idempotency_records_learning_committed_result"),
        "idempotency_records",
        "safe_response IS NOT NULL AND ((audience = 'client' AND result_kind IN ('collection_item','material_import') AND result_id IS NOT NULL AND library_id IS NOT NULL) OR (audience = 'admin' AND result_kind = 'governance_result' AND result_id IS NULL AND library_id IS NULL))",
    )
    op.create_check_constraint(
        op.f("ck_jobs_operation_references"),
        "jobs",
        "(operation_kind = 'credential_test' AND credential_id IS NOT NULL AND run_id IS NOT NULL) OR (operation_kind = 'material_import' AND credential_id IS NULL AND run_id IS NULL)",
    )
    op.create_check_constraint(
        op.f("ck_libraries_notification_sequence"), "libraries", "notification_sequence >= 0"
    )
    op.drop_constraint(
        op.f("ck_material_revisions_learning_structure_status"), "material_revisions", type_="check"
    )
    op.drop_constraint(
        op.f("ck_material_revisions_learning_status"), "material_revisions", type_="check"
    )
    op.create_check_constraint(
        op.f("ck_material_revisions_learning_structure_status"),
        "material_revisions",
        "(material_type = 'exam' AND structure_status IS NULL AND structure_published_at IS NULL) OR (material_type IN ('novel','textbook') AND structure_status IS NOT NULL AND structure_status IN ('building','readable','degraded','failed'))",
    )
    op.create_check_constraint(
        op.f("ck_material_revisions_source_publication"),
        "material_revisions",
        "(origin_job_id IS NULL AND processor_version = 'legacy-novel-source-v1' AND material_type = 'novel' AND status IN ('published','sealed') AND published_at IS NOT NULL) OR (origin_job_id IS NOT NULL AND ((status IN ('building','failed') AND published_at IS NULL AND content_digest IS NULL) OR (status IN ('published','sealed') AND published_at IS NOT NULL AND content_digest IS NOT NULL)))",
    )
    op.create_check_constraint(
        op.f("ck_material_revisions_source_contract"),
        "material_revisions",
        "source_schema_version = 1 AND material_type IN ('novel','textbook','exam') AND (content_digest IS NULL OR octet_length(content_digest) = 32)",
    )
    op.create_check_constraint(
        op.f("ck_material_revisions_structure_publication"),
        "material_revisions",
        "origin_job_id IS NULL OR structure_status IS NULL OR (structure_status IN ('building','failed') AND structure_published_at IS NULL) OR (structure_status IN ('readable','degraded') AND structure_published_at IS NOT NULL)",
    )
    op.create_check_constraint(
        op.f("ck_material_revisions_learning_status"),
        "material_revisions",
        "status IN ('building','published','failed','sealed')",
    )
    op.drop_constraint(op.f("ck_materials_learning_source_status"), "materials", type_="check")
    op.drop_constraint(op.f("ck_materials_learning_material_type"), "materials", type_="check")
    op.create_check_constraint(
        op.f("ck_materials_source_file"),
        "materials",
        "(primary_file_object_id IS NULL AND source_format IS NULL AND material_type = 'novel' AND source_status IN ('published','sealed')) OR (primary_file_object_id IS NOT NULL AND source_format IS NOT NULL AND ((material_type IN ('novel','textbook') AND source_format IN ('md','epub','pdf')) OR (material_type = 'exam' AND source_format IN ('md','epub','pdf','png','jpeg','webp'))))",
    )
    op.create_check_constraint(
        op.f("ck_materials_learning_material_type"),
        "materials",
        "material_type IN ('novel','textbook','exam')",
    )
    op.create_check_constraint(
        op.f("ck_materials_learning_source_status"),
        "materials",
        "source_status IN ('published','sealed','parsing','readable','degraded','failed')",
    )
    op.create_check_constraint(
        op.f("ck_materials_source_metadata"),
        "materials",
        "title_origin IN ('filename','extracted','user') AND analysis_status IN ('not_requested','pending','ready','failed')",
    )
    op.drop_constraint(op.f("ck_upload_intents_purpose"), "upload_intents", type_="check")
    op.drop_constraint(op.f("ck_upload_intents_target_kind"), "upload_intents", type_="check")
    op.drop_constraint(op.f("ck_upload_intents_status"), "upload_intents", type_="check")
    op.drop_constraint(op.f("ck_upload_intents_expected_size"), "upload_intents", type_="check")
    op.drop_constraint(op.f("ck_upload_intents_target_owner"), "upload_intents", type_="check")
    op.drop_constraint(op.f("ck_upload_intents_completion"), "upload_intents", type_="check")
    op.drop_constraint(op.f("ck_upload_intents_declared_format"), "upload_intents", type_="check")
    op.create_check_constraint(
        op.f("ck_upload_intents_target_kind"),
        "upload_intents",
        "(purpose = 'avatar' AND target_kind = 'user_extension') OR (purpose = 'primary_document' AND target_kind = 'material_import')",
    )
    op.create_check_constraint(
        op.f("ck_upload_intents_versions"),
        "upload_intents",
        "revision >= 1 AND completion_generation >= 0",
    )
    op.create_check_constraint(
        op.f("ck_upload_intents_declared_format"),
        "upload_intents",
        "(purpose = 'avatar' AND declared_format IN ('jpeg','png','webp')) OR (purpose = 'primary_document' AND declared_format IN ('md','epub','pdf','png','jpeg','webp'))",
    )
    op.create_check_constraint(
        op.f("ck_upload_intents_status"),
        "upload_intents",
        "(purpose = 'avatar' AND status IN ('pending','completed','failed')) OR (purpose = 'primary_document' AND status IN ('awaiting_upload','verifying','completed','failed','cancelled','expired'))",
    )
    op.create_check_constraint(
        op.f("ck_upload_intents_purpose_source"),
        "upload_intents",
        "(purpose = 'avatar' AND material_type IS NULL AND storage_reservation_id IS NULL AND staging_object_key IS NULL) OR (purpose = 'primary_document' AND material_type IS NOT NULL AND material_type IN ('novel','textbook','exam') AND storage_reservation_id IS NOT NULL AND staging_object_key IS NOT NULL AND original_filename IS NOT NULL)",
    )
    op.create_check_constraint(
        op.f("ck_upload_intents_completion_lease"),
        "upload_intents",
        "((purpose = 'avatar' OR status != 'verifying') AND completion_lease_token IS NULL AND completion_lease_until_at IS NULL) OR (purpose = 'primary_document' AND status = 'verifying' AND completion_generation > 0 AND completion_lease_token IS NOT NULL AND completion_lease_until_at IS NOT NULL)",
    )
    op.create_check_constraint(
        op.f("ck_upload_intents_purpose"),
        "upload_intents",
        "purpose IN ('avatar','primary_document')",
    )
    op.create_check_constraint(
        op.f("ck_upload_intents_expected_size"),
        "upload_intents",
        "expected_size_bytes > 0 AND (purpose != 'avatar' OR expected_size_bytes <= 5242880)",
    )
    op.create_check_constraint(
        op.f("ck_upload_intents_completion"),
        "upload_intents",
        "(status = 'completed' AND file_object_id IS NOT NULL AND failure_code IS NULL) OR (status != 'completed' AND file_object_id IS NULL)",
    )
    op.create_check_constraint(
        op.f("ck_upload_intents_target_owner"),
        "upload_intents",
        "purpose != 'avatar' OR target_resource_id = user_id",
    )
    # ### end Alembic commands ###
    _grant_runtime()


def _grant_runtime() -> None:
    """Grant only new business tables; retain immutable audit and version protections."""
    bind = op.get_bind()
    database = bind.scalar(sa.text("SELECT current_database()"))
    schema = bind.scalar(sa.text("SELECT current_schema()"))
    if (
        database not in {"haruka_dev", "haruka_test"}
        or not isinstance(schema, str)
        or (schema != "public" and not re.fullmatch(r"haruka_migration_test_[a-f0-9]{32}", schema))
    ):
        raise RuntimeError("migration target is not an isolated Haruka schema")
    quoted_schema = bind.dialect.identifier_preparer.quote_schema(schema)
    role = f"{database}_runtime"
    for table_name in (
        "material_imports",
        "user_storage_states",
        "user_storage_reservations",
        "material_source_assets",
        "material_import_issues",
        "user_notifications",
    ):
        op.execute(
            f"GRANT SELECT, INSERT, UPDATE, DELETE ON {quoted_schema}.{table_name} TO {role}"
        )


def downgrade() -> None:
    raise RuntimeError("restore or forward-repair instead of dropping private source history")
