// Mocks generated by Mockito from annotations
// in haruka/test/features/collections/cached_collection_catalog_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes

import 'dart:async' as _i3;

import 'package:dio/dio.dart' as _i6;
import 'package:haruka/core/cache/cache_models.dart' as _i4;
import 'package:haruka/features/collections/data/collection_catalog.dart'
    as _i2;
import 'package:haruka/features/collections/domain/collection_entry.dart'
    as _i5;
import 'package:haruka/features/collections/domain/notebook_record.dart' as _i8;
import 'package:haruka/features/collections/domain/vocabulary_csv.dart' as _i9;
import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i7;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: experimental_member_use
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

/// A class which mocks [CollectionSource].
///
/// See the documentation for Mockito's code generation for more information.
class MockCollectionSource extends _i1.Mock implements _i2.CollectionSource {
  @override
  _i3.Future<_i4.CachePayload<List<_i5.CollectionEntry>>> fetchCollections(
    _i4.CacheResource? resource,
    _i6.CancelToken? cancel,
  ) => (super.noSuchMethod(
    Invocation.method(#fetchCollections, [resource, cancel]),
    returnValue: _i3.Future<_i4.CachePayload<List<_i5.CollectionEntry>>>.value(
      _i7.dummyValue<_i4.CachePayload<List<_i5.CollectionEntry>>>(
        this,
        Invocation.method(#fetchCollections, [resource, cancel]),
      ),
    ),
    returnValueForMissingStub:
        _i3.Future<_i4.CachePayload<List<_i5.CollectionEntry>>>.value(
          _i7.dummyValue<_i4.CachePayload<List<_i5.CollectionEntry>>>(
            this,
            Invocation.method(#fetchCollections, [resource, cancel]),
          ),
        ),
  ) as _i3.Future<_i4.CachePayload<List<_i5.CollectionEntry>>>);

  @override
  _i3.Future<_i4.CachePayload<_i2.NotebookListSnapshot>> fetchNotebooks(
    _i4.CacheResource? resource,
    _i6.CancelToken? cancel,
  ) => (super.noSuchMethod(
    Invocation.method(#fetchNotebooks, [resource, cancel]),
    returnValue: _i3.Future<_i4.CachePayload<_i2.NotebookListSnapshot>>.value(
      _i7.dummyValue<_i4.CachePayload<_i2.NotebookListSnapshot>>(
        this,
        Invocation.method(#fetchNotebooks, [resource, cancel]),
      ),
    ),
    returnValueForMissingStub:
        _i3.Future<_i4.CachePayload<_i2.NotebookListSnapshot>>.value(
          _i7.dummyValue<_i4.CachePayload<_i2.NotebookListSnapshot>>(
            this,
            Invocation.method(#fetchNotebooks, [resource, cancel]),
          ),
        ),
  ) as _i3.Future<_i4.CachePayload<_i2.NotebookListSnapshot>>);

  @override
  _i3.Future<_i8.NotebookRecord> createNotebook(
    String? name,
    String? language,
    String? description,
  ) => (super.noSuchMethod(
    Invocation.method(#createNotebook, [name, language, description]),
    returnValue: _i3.Future<_i8.NotebookRecord>.value(
      _i7.dummyValue<_i8.NotebookRecord>(
        this,
        Invocation.method(#createNotebook, [name, language, description]),
      ),
    ),
    returnValueForMissingStub: _i3.Future<_i8.NotebookRecord>.value(
      _i7.dummyValue<_i8.NotebookRecord>(
        this,
        Invocation.method(#createNotebook, [name, language, description]),
      ),
    ),
  ) as _i3.Future<_i8.NotebookRecord>);

  @override
  _i3.Future<void> updateNotebook(
    String? id, {
    String? name,
    String? description,
  }) => (super.noSuchMethod(
    Invocation.method(
      #updateNotebook,
      [id],
      {#name: name, #description: description},
    ),
    returnValue: _i3.Future<void>.value(),
    returnValueForMissingStub: _i3.Future<void>.value(),
  ) as _i3.Future<void>);

  @override
  _i3.Future<void> deleteNotebook(String? id) => (super.noSuchMethod(
    Invocation.method(#deleteNotebook, [id]),
    returnValue: _i3.Future<void>.value(),
    returnValueForMissingStub: _i3.Future<void>.value(),
  ) as _i3.Future<void>);

  @override
  _i3.Future<void> setCollectionNotebooks(
    String? id,
    Set<String>? notebookIds,
  ) => (super.noSuchMethod(
    Invocation.method(#setCollectionNotebooks, [id, notebookIds]),
    returnValue: _i3.Future<void>.value(),
    returnValueForMissingStub: _i3.Future<void>.value(),
  ) as _i3.Future<void>);

  @override
  _i3.Future<void> addCollection(_i5.CollectionEntry? item) =>
      (super.noSuchMethod(
        Invocation.method(#addCollection, [item]),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);

  @override
  _i3.Future<void> updateCollection(
    String? id, {
    required String? displayText,
    required String? meaning,
    required String? notes,
  }) => (super.noSuchMethod(
    Invocation.method(
      #updateCollection,
      [id],
      {#displayText: displayText, #meaning: meaning, #notes: notes},
    ),
    returnValue: _i3.Future<void>.value(),
    returnValueForMissingStub: _i3.Future<void>.value(),
  ) as _i3.Future<void>);

  @override
  _i3.Future<void> saveCollectionNotes(String? id, String? notes) =>
      (super.noSuchMethod(
        Invocation.method(#saveCollectionNotes, [id, notes]),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);

  @override
  _i3.Future<_i9.VocabularyCsvImportOutcome> importVocabularyCsv(
    _i9.VocabularyCsvPreview? preview, {
    required _i9.CsvDuplicateAction? duplicateAction,
    required bool? excludeErrors,
  }) => (super.noSuchMethod(
    Invocation.method(
      #importVocabularyCsv,
      [preview],
      {#duplicateAction: duplicateAction, #excludeErrors: excludeErrors},
    ),
    returnValue: _i3.Future<_i9.VocabularyCsvImportOutcome>.value(
      _i7.dummyValue<_i9.VocabularyCsvImportOutcome>(
        this,
        Invocation.method(
          #importVocabularyCsv,
          [preview],
          {#duplicateAction: duplicateAction, #excludeErrors: excludeErrors},
        ),
      ),
    ),
    returnValueForMissingStub: _i3.Future<_i9.VocabularyCsvImportOutcome>.value(
      _i7.dummyValue<_i9.VocabularyCsvImportOutcome>(
        this,
        Invocation.method(
          #importVocabularyCsv,
          [preview],
          {#duplicateAction: duplicateAction, #excludeErrors: excludeErrors},
        ),
      ),
    ),
  ) as _i3.Future<_i9.VocabularyCsvImportOutcome>);
}
