import 'dart:io';

import 'package:path/path.dart' as path;
import 'package:path_provider/path_provider.dart';

import 'audio_blob_store.dart';
import 'audio_process_lock.dart';

Future<AudioByteBackend> openAudioByteBackend(String partition) async {
  if (!RegExp(r'^[a-f0-9]{64}$').hasMatch(partition)) {
    throw ArgumentError.value(partition, 'partition', 'Expected a cache scope digest');
  }
  final support = await getApplicationSupportDirectory();
  final directory = Directory(path.join(support.path, 'haruka-cache', partition, 'audio'));
  await directory.create(recursive: true);
  return NativeAudioByteBackend(directory);
}

/// The cache scope is the parent directory. Reference names are generated by
/// AudioBlobStore and are checked again before any filesystem operation.
final class NativeAudioByteBackend implements AudioByteBackend {
  NativeAudioByteBackend(this.directory);

  final Directory directory;
  static final RegExp _reference = RegExp(r'^(stage|ready)-[a-f0-9]{64}$');

  File _file(String reference) {
    if (!_reference.hasMatch(reference)) throw ArgumentError.value(reference, 'reference');
    return File(path.join(directory.path, reference));
  }

  File _lockFile(String reference) => File(path.join(directory.path, '$reference.lock'));

  @override
  Future<AudioStageWriter> beginStage(String reference) async {
    if (!reference.startsWith('stage-')) throw ArgumentError.value(reference, 'reference');
    final file = _file(reference);
    final process = (await AudioProcessLock.acquire(_lockFile(reference).path))!;
    RandomAccessFile? lock;
    var acquired = false;
    try {
      lock = await _lockFile(reference).open(mode: FileMode.append);
      await lock.lock(FileLock.exclusive);
      acquired = true;
      await file.create(exclusive: true);
      final writer = await file.open(mode: FileMode.writeOnlyAppend);
      return _NativeStageWriter(file, writer, lock, process);
    } catch (_) {
      try {
        if (acquired) await lock?.unlock();
      } finally {
        try {
          await lock?.close();
        } finally {
          process.release();
        }
      }
      rethrow;
    }
  }

  @override
  Future<void> promote(String stagingReference, String readyReference) async {
    if (!stagingReference.startsWith('stage-') || !readyReference.startsWith('ready-')) {
      throw ArgumentError('Expected stage and ready audio references');
    }
    final source = _file(stagingReference);
    final destination = _file(readyReference);
    if (await destination.exists()) throw StateError('Ready audio reference already exists');
    await source.rename(destination.path);
  }

  @override
  Future<Stream<List<int>>?> open(String reference) async {
    final file = _file(reference);
    if (!await file.exists()) return null;
    return file.openRead();
  }

  @override
  Future<bool> tryDelete(String reference) async {
    final file = _file(reference);
    final process = await AudioProcessLock.acquire(_lockFile(reference).path, ifAvailable: true);
    if (process == null) return false;
    RandomAccessFile? lock;
    var acquired = false;
    try {
      lock = await _lockFile(reference).open(mode: FileMode.append);
      try {
        await lock.lock(FileLock.exclusive);
        acquired = true;
      } on FileSystemException {
        return false;
      }
      if (await file.exists()) await file.delete();
      return true;
    } finally {
      try {
        if (acquired) await lock?.unlock();
      } finally {
        try {
          await lock?.close();
        } finally {
          process.release();
        }
      }
    }
  }

  @override
  Future<Set<String>> references() async {
    if (!await directory.exists()) return {};
    return directory
        .list(followLinks: false)
        .where((item) => item is File)
        .map((item) => path.basename(item.path))
        .where(_reference.hasMatch)
        .toSet();
  }

  Future<T> _locked<T>(String name, FileLock mode, Future<T> Function() action) async {
    final process = (await AudioProcessLock.acquire(
      _lockFile(name).path,
      shared: mode == FileLock.blockingShared,
    ))!;
    RandomAccessFile? lock;
    var acquired = false;
    try {
      lock = await _lockFile(name).open(mode: FileMode.append);
      await lock.lock(mode);
      acquired = true;
      return await action();
    } finally {
      try {
        if (acquired) await lock?.unlock();
      } finally {
        try {
          await lock?.close();
        } finally {
          process.release();
        }
      }
    }
  }

  @override
  Future<T> withPublishLock<T>(Future<T> Function() action) =>
      _locked('publish', FileLock.blockingExclusive, action);

  @override
  Future<T?> withOperationLock<T>(
    String operationId,
    Future<T> Function() action, {
    bool ifAvailable = false,
  }) async {
    if (!RegExp(r'^[A-Za-z0-9-]{1,80}$').hasMatch(operationId)) {
      throw ArgumentError.value(operationId, 'operationId');
    }
    final process = await AudioProcessLock.acquire(
      _lockFile('operation-$operationId').path,
      ifAvailable: ifAvailable,
    );
    if (process == null) return null;
    RandomAccessFile? lock;
    var acquired = false;
    try {
      lock = await _lockFile('operation-$operationId').open(mode: FileMode.append);
      try {
        await lock.lock(ifAvailable ? FileLock.exclusive : FileLock.blockingExclusive);
        acquired = true;
      } on FileSystemException {
        if (ifAvailable) return null;
        rethrow;
      }
      return await action();
    } finally {
      try {
        if (acquired) await lock?.unlock();
      } finally {
        try {
          await lock?.close();
        } finally {
          process.release();
        }
      }
    }
  }

  @override
  Future<T> withReadLock<T>(String reference, Future<T> Function() action) {
    _file(reference);
    return _locked(reference, FileLock.blockingShared, action);
  }

  @override
  Future<void> close() async {}
}

final class _NativeStageWriter implements AudioStageWriter {
  _NativeStageWriter(this.file, this.writer, this.lock, this.process);

  final File file;
  final RandomAccessFile writer;
  final RandomAccessFile lock;
  final AudioProcessLease process;
  bool _closed = false;

  @override
  Future<void> add(List<int> bytes) async {
    if (_closed) throw StateError('Audio stage is closed');
    await writer.writeFrom(bytes);
  }

  @override
  Future<void> close() async {
    if (_closed) return;
    _closed = true;
    try {
      await writer.flush();
    } finally {
      try {
        await writer.close();
      } finally {
        try {
          await lock.unlock();
        } finally {
          try {
            await lock.close();
          } finally {
            process.release();
          }
        }
      }
    }
  }

  @override
  Future<void> abort() async {
    await close();
    if (await file.exists()) await file.delete();
  }
}
