from casbin.model import Model

class Enforcer:
    def __init__(self, model: Model | None = ...) -> None: ...
    def add_grouping_policy(self, *params: str) -> bool: ...
    def add_policy(self, *params: str) -> bool: ...
    def build_role_links(self) -> None: ...
    def enforce(self, *rvals: str) -> bool: ...
