// Mocks generated by Mockito from annotations
// in haruka/test/features/agent/query_repository_history_widget_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes

import 'dart:async' as _i4;

import 'package:haruka/features/agent/data/query_result_repository.dart' as _i2;
import 'package:haruka/features/agent/domain/learning_card.dart' as _i5;
import 'package:haruka/features/agent/domain/query_history_entry.dart' as _i3;
import 'package:haruka/features/agent/domain/query_request.dart' as _i6;
import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i7;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: experimental_member_use
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

/// A class which mocks [QueryResultRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockQueryResultRepository extends _i1.Mock implements _i2.QueryResultRepository {
  @override
  List<_i3.QueryHistoryEntry> get history => (super.noSuchMethod(
    Invocation.getter(#history),
    returnValue: <_i3.QueryHistoryEntry>[],
    returnValueForMissingStub: <_i3.QueryHistoryEntry>[],
  ) as List<_i3.QueryHistoryEntry>);

  @override
  _i4.Future<_i5.LearningCard> submit(_i6.QueryRequest? request) => (super.noSuchMethod(
    Invocation.method(#submit, [request]),
    returnValue: _i4.Future<_i5.LearningCard>.value(
      _i7.dummyValue<_i5.LearningCard>(this, Invocation.method(#submit, [request])),
    ),
    returnValueForMissingStub: _i4.Future<_i5.LearningCard>.value(
      _i7.dummyValue<_i5.LearningCard>(this, Invocation.method(#submit, [request])),
    ),
  ) as _i4.Future<_i5.LearningCard>);

  @override
  _i4.Future<_i5.LearningCard> readSaved(String? id) => (super.noSuchMethod(
    Invocation.method(#readSaved, [id]),
    returnValue: _i4.Future<_i5.LearningCard>.value(
      _i7.dummyValue<_i5.LearningCard>(this, Invocation.method(#readSaved, [id])),
    ),
    returnValueForMissingStub: _i4.Future<_i5.LearningCard>.value(
      _i7.dummyValue<_i5.LearningCard>(this, Invocation.method(#readSaved, [id])),
    ),
  ) as _i4.Future<_i5.LearningCard>);
}
