(() => {
  const { data, escape: e, icon: I, initialState, typeLabel, visibleMaterials } = window.HarukaCore;
  const s = initialState();
  const root = document.getElementById('desktop-app');
  const adminRoutes = ['adminOverview', 'adminUsers', 'adminRoles', 'adminMenus', 'adminPolicy', 'adminJobs', 'adminAudit', 'adminUsage', 'adminSecurity'];
  const names = { library: '材料库', material: '材料详情', import: '导入材料', novel: '小说阅读', textbook: '课本学习', examPrep: '试卷准备', examRun: '整卷作答', examResult: '成绩复盘', notebooks: '单词本', notebook: '词本详情', word: '词条详情', csv: '单词 CSV', exercise: 'AI 习题', practice: '逐题练习', mistakes: '错题库', mistake: '错题详情', agent: '学习 Agent', report: '学习诊断', notifications: '站内消息', jobs: '任务进度', settings: '设置', profile: '个人资料', languages: '语言档案', appearance: '外观与无障碍', readingPrefs: '阅读偏好', model: '个人模型', speech: '朗读与声音', usage: '模型用量', cache: '本机缓存', security: '账号安全', connection: '服务连接', states: '状态样例', login: '登录', register: '注册', recovery: '找回密码', onboarding: '首次设置', adminLogin: '管理端登录', adminOverview: '运维概览', adminUsers: '用户与会话', adminRoles: '角色与权限', adminMenus: '菜单与页面', adminPolicy: '注册策略', adminJobs: '任务与资源', adminAudit: '审计诊断', adminUsage: '模型用量', adminSecurity: '管理账号与安全' };
  const go = route => { s.previousRoute = s.route; s.route = route; s.modal = ''; history.replaceState(null, '', `#${route}`); render(); window.scrollTo(0, 0); };
  const toast = message => { s.toast = message; render(); clearTimeout(toast.timer); toast.timer = setTimeout(() => { s.toast = ''; render(); }, 3500); };
  const btn = (label, route, cls = 'secondary', icon = '') => `<button type="button" class="${cls}" data-go="${route}">${icon ? I(icon) : ''}${label}</button>`;
  const tag = (label, kind = '') => `<span class="tag ${kind}">${e(label)}</span>`;
  const cover = m => `<span class="cover ${m.tone}" aria-hidden="true">${e(m.cover)}</span>`;
  const head = (eyebrow, title, subtitle = '') => `<div class="eyebrow"><span class="signal"></span>${eyebrow}</div><h1 class="title">${title}</h1>${subtitle ? `<p class="subtitle">${subtitle}</p>` : ''}`;
  function sidebar() {
    const admin = s.adminArea;
    const navItems = admin ? [
      ['adminOverview', '运维概览', 'grid'], ['adminUsers', '用户与会话', 'user'], ['adminRoles', '角色与权限', 'shield'], ['adminMenus', '页面与菜单', 'layers'], ['adminPolicy', '注册策略', 'settings'], ['adminJobs', '任务与资源', 'clock'], ['adminAudit', '审计诊断', 'book'], ['adminUsage', '模型用量', 'spark']
    ] : [
      ['library', '材料库', 'library'], ['notebooks', '单词本', 'layers'], ['exercise', 'AI 习题', 'spark'], ['mistakes', '错题库', 'warning'], ['agent', '学习 Agent', 'message']
    ];
    const lower = admin ? [['adminSecurity', '管理账号与退出', 'shield'], ['login', '切换用户端', 'back']] : [['notifications', '站内消息', 'bell'], ['jobs', '任务进度', 'clock'], ['settings', '设置', 'settings'], ['adminLogin', '管理端预览', 'shield']];
    return `<aside class="sidebar ${admin ? 'admin-sidebar' : ''}"><div class="brand"><span class="brand-mark">h</span><span>haruka</span></div>${admin ? '<div class="admin-ribbon">ADMIN / DEMO</div>' : ''}<div><div class="side-label">${admin ? '运维空间' : '学习空间'}</div><nav class="side-nav" aria-label="${admin ? '管理导航' : '学习导航'}">${navItems.map(([route, label, icon]) => `<button type="button" data-go="${route}" class="${s.route === route ? 'active' : ''}" ${s.route === route ? 'aria-current="page"' : ''}>${I(icon)}<span>${label}</span></button>`).join('')}</nav></div><div class="side-spacer"></div><div><div class="side-label">${admin ? '切换' : '个人与系统'}</div><nav class="side-nav" aria-label="${admin ? '管理切换' : '个人与系统'}">${lower.map(([route, label, icon]) => `<button type="button" data-go="${route}" class="${s.route === route ? 'active' : ''}">${I(icon)}<span>${label}</span></button>`).join('')}</nav></div><div class="side-account"><span class="avatar">遥</span><span><strong>${e(s.profile.displayName)}</strong><small>${admin ? '管理端演示会话' : '个人学习空间'}</small></span><button type="button" data-go="${admin ? 'adminSecurity' : 'profile'}" aria-label="${admin ? '管理账号与安全' : '个人资料'}">${I('chevron')}</button></div></aside>`;
  }
  function topbar() { const unread = s.notifications.some(n => n.unread); return `<header class="topbar ${s.adminArea ? 'admin-top' : ''}"><div class="top-path">Haruka <span style="margin:0 8px">/</span> <strong>${e(names[s.route] || '页面')}</strong></div><div class="top-actions"><span class="small muted">${s.adminArea ? '管理端 · 在线示例' : `${e(s.activeLanguage || '未选择语言')} · 个人学习空间`}</span>${s.adminArea ? '' : `<button type="button" class="icon-btn ${unread ? 'unread-dot' : ''}" data-go="notifications" aria-label="站内消息">${I('bell')}</button><button type="button" class="user-chip" data-go="profile"><span class="avatar">遥</span>${e(s.profile.displayName)}</button>`}</div></header>`; }
  function library() {
    const items = visibleMaterials(s);
    return `<div class="hero-grid"><div class="hero-copy">${head('YOUR WORLD, NEW WORDS', '喜欢的内容，<br>就是你的<em>起点。</em>', '从一页故事，到一个属于你的新表达。')}${btn('添加材料', 'import', 'primary', 'plus')}</div><article class="feature"><div><small>你的小说 · 日本語</small><h2 lang="ja">夏の手紙</h2><small>第 03 章 · 窓の向こう</small></div><button type="button" data-go="novel">打开章节 ${I('arrow')}</button></article></div><div class="section-head"><h2>我的材料 <span>${items.length} 份</span></h2><div class="button-row"><label class="search">${I('search')}<input type="search" data-input="search" aria-label="搜索我的材料" placeholder="搜索标题或语言" value="${e(s.search)}"></label><div class="filters" aria-label="材料类型">${[['all', '全部'], ['novel', '小说'], ['textbook', '课本'], ['exam', '试卷']].map(([key, label]) => `<button type="button" data-filter="${key}" aria-pressed="${s.filter === key}">${label}</button>`).join('')}</div></div></div>${items.length ? `<div class="material-list">${items.map(m => `<button type="button" class="material-row" data-material="${m.id}">${cover(m)}<span class="row-copy"><span class="row-title">${e(m.title)}</span><small>${e(m.subtitle)}</small></span>${tag(m.status, m.type === 'exam' ? 'warn' : 'good')}<small class="muted">${e(m.updated)}</small>${I('chevron')}</button>`).join('')}</div>` : `<div class="empty"><strong>没有找到材料</strong><p>换个标题，或者清除类型筛选。</p><button class="secondary" type="button" data-action="clearSearch">清除筛选</button></div>`}<div class="section-head"><h2>查看任务与结果</h2></div><button type="button" class="surface" style="display:flex;align-items:center;gap:13px;text-align:left;width:100%;border:0;color:var(--ink)" data-go="jobs">${I('clock')}<span class="row-copy"><strong>导入与生成任务</strong><small>区分已完成、待确认与失败</small></span>${I('chevron')}</button>`;
  }
  function importPage() {
    const stage = Math.min(2, s.importStep);
    let main = '';
    if (stage === 0) main = `<div class="grid-3">${[['novel', '小说', '章节与连续阅读', 'book'], ['textbook', '课本', '单元内容与课后题', 'layers'], ['exam', '试卷', '校对与整卷作答', 'edit']].map(([key, label, description, icon]) => `<button type="button" class="tile" data-import-type="${key}" aria-pressed="${s.importType === key}">${I(icon)}<strong>${label}</strong><small>${description}</small></button>`).join('')}</div><div class="button-row" style="margin-top:23px"><button class="primary" type="button" data-action="importNext">继续 ${I('arrow')}</button></div>`;
    if (stage === 1) main = `<div class="grid-aside"><div class="surface form-grid"><label class="field">选择示例文件<input type="file" data-file="material"><small>${s.importFile ? `已选择：${e(s.importFile)}` : '原型只记录文件名，不读取或上传内容。格式范围以各类型正式发布为准；试卷首版格式仍待决策。'}</small></label><label class="check-row"><input type="checkbox" data-toggle="importAnalyze" ${s.importAnalyze ? 'checked' : ''}><span>进一步 AI 结构建议（模拟）</span></label><div class="button-row"><button class="secondary" type="button" data-action="importBack">返回</button><button class="primary" type="button" data-action="importNext">继续</button></div></div><div class="callout">${I('warning')}<span>直接文本提取与视觉 OCR 是独立步骤；扫描区域需要明确范围、本人 Key 与上限。本演示不调用模型。</span></div></div>`;
    if (stage === 2) main = `<div class="grid-aside"><div class="surface stack"><div><span class="small muted">材料类型</span><h2>${typeLabel[s.importType]}</h2></div><div><span class="small muted">文件</span><h2>${e(s.importFile)}</h2></div><div><span class="small muted">本次处理</span><h2>直接提取${s.importAnalyze ? ' · AI 建议（模拟）' : ''}</h2></div><div class="button-row"><button class="secondary" type="button" data-action="importBack">返回</button><button class="primary" type="button" data-action="importConfirm">确认导入</button></div></div><div class="callout">${I('shield')}<span>确认只创建本地示例任务。正式导入会校验不可变文件、类型、权限与质量门槛。</span></div></div>`;
    return `${head(`IMPORT / ${stage + 1} OF 3`, ['选择材料类型', '文件与处理范围', '确认导入'][stage], '三类材料拥有不同的处理流程与专属学习页面。')}<div class="stepper">${[0, 1, 2].map(i => `<span class="${i <= stage ? 'on' : ''}"></span>`).join('')}</div>${main}<p class="note" style="margin-top:17px">类型建立后不可原地修改。若选错类型，需创建另一份材料重新处理，原材料保留。</p>`;
  }
  function material() {
    const m = data.materials.find(x => x.id === s.chosenMaterial) || data.materials[0];
    const target = m.type === 'novel' ? 'novel' : m.type === 'textbook' ? 'textbook' : 'examPrep';
    return `${head('MATERIAL / DETAIL', e(m.title), e(m.subtitle))}<div class="grid-aside" style="margin-top:22px"><div class="surface"><div class="button-row">${cover({ ...m, cover: m.cover })}<div class="row-copy"><strong>${e(m.title)}</strong><small>${e(m.detail)}</small></div>${tag(m.status, m.type === 'exam' ? 'warn' : 'good')}</div><div class="divider"></div><p>${e(m.detail)}</p><p class="note" style="margin-top:13px">最近更新：${e(m.updated)}</p><div class="button-row" style="margin-top:21px">${btn(m.type === 'novel' ? '打开阅读' : m.type === 'textbook' ? '进入单元' : '继续试卷准备', target, 'primary', 'arrow')}<button type="button" class="secondary" data-modal="quality">解析与来源状态</button></div></div><aside class="panel"><h2 style="font-size:18px">专属流程</h2><p style="margin-top:10px">${m.type === 'exam' ? '完成题号、分值、答案依据和听力匹配校对后，冻结版本才能开考。' : m.type === 'textbook' ? '按 Unit 保留课文、对话、词表、语法与原生练习的关系。' : '保留原文章节与段落；语言标注失败仍可阅读可靠正文。'}</p></aside></div>`;
  }
  function novel() {
    const term = data.novel.terms[s.selectedTerm];
    const readerPaper = s.readingTheme === 'sepia' ? '#f7ead4' : s.readingTheme === 'dark' ? '#192535' : '#ffffff';
    const readerInk = s.readingTheme === 'dark' ? '#edf3ff' : '#152b42';
    const readerFont = s.readingFont === 'serif' ? "'Yu Mincho','Noto Serif JP',serif" : "'Segoe UI','Microsoft YaHei',sans-serif";
    const paragraphs = data.novel.paragraphs.map((p, i) => { const key = i === 0 ? 'soft' : i === 1 ? 'smile' : ''; const word = key === 'soft' ? 'そっと' : '微笑んだ'; return `<p>${key ? e(p).replace(word, `<button type="button" class="term" data-term="${key}" aria-pressed="${s.selectedTerm === key}">${word}</button>`) : e(p)}</p>`; }).join('');
    return `<div class="section-head" style="margin-top:0"><div>${head('NOVEL / CHAPTER 03', '夏の手紙', '第 03 章 · 窓の向こう')}</div><div class="button-row"><button type="button" class="secondary" data-action="bookmark">${I('bookmark')} 书签</button><button type="button" class="secondary" data-action="toggleSpeech">${I(s.playing ? 'pause' : 'headphones')} ${s.playing ? '暂停朗读' : '章节朗读'}</button>${btn('阅读偏好', 'readingPrefs', 'secondary', 'settings')}</div></div><div class="reader-shell"><aside class="chapter-nav"><h2>章节目录</h2>${data.novel.chapters.map((chapter, i) => `<button type="button" class="${i === 2 ? 'active' : ''}" data-action="chapter" data-index="${i}">${String(i + 1).padStart(2, '0')} &nbsp; ${e(chapter)}</button>`).join('')}</aside><article class="reading-paper" style="--reader-paper:${readerPaper};--reader-ink:${readerInk};--reader-font:${readerFont}"><div class="eyebrow"><span class="signal"></span>CHAPTER 03</div><h1 lang="ja">窓の向こう</h1><div class="prose" lang="ja" style="--reader-size:${s.readingSize}px;--reader-line:${s.lineHeight}">${paragraphs}</div><div class="reading-footer"><span>第 03 章 / 共 12 章</span><span>点选高亮词，查看语境与出处</span></div></article><aside class="insight"><div class="eyebrow"><span class="signal"></span>语境解释 · 示例</div><div class="word" lang="ja">${term.word}</div><p class="small muted">${term.reading}</p><p style="margin-top:16px">${term.meaning}</p><div class="sentence"><strong lang="ja">${term.sentence}</strong><p class="small" style="margin-top:5px">${term.translation}</p></div><p class="note">出处：夏の手紙 · ${term.source}</p><div class="stack" style="margin-top:17px"><button type="button" class="secondary full" data-action="collectTerm">${I('bookmark')} ${s.collected.includes(s.selectedTerm) ? '已收藏' : '收藏词条'}</button>${btn('继续问 Agent', 'agent', 'secondary full', 'message')}</div></aside></div>`;
  }
  function textbook() {
    const unit = data.textbook.units.find(x => x.id === s.textbookUnit) || data.textbook.units[0]; const q = data.textbook.question;
    return `${head('TEXTBOOK / 日本語', '日语的日常表达', '单元、内容角色和课后题保持原教材的关系。')}<div class="grid-sidebar" style="margin-top:24px"><aside class="setting-menu">${data.textbook.units.map(x => `<button type="button" class="${x.id === s.textbookUnit ? 'active' : ''}" data-unit="${x.id}">${I('book')}${e(x.title)}</button>`).join('')}</aside><div class="stack-lg"><div class="panel"><div class="eyebrow"><span class="signal"></span>UNIT CONTENT</div><h2 style="font-size:24px;margin:11px 0 3px">${e(unit.title)}</h2><p class="subtitle">课文、词汇、语法和习题按教学次序呈现。</p><div class="grid-2" style="margin-top:20px">${unit.items.map((item, i) => `<button class="tile" type="button" data-modal="textbookItem" data-index="${i}">${I(['book', 'library', 'spark', 'edit'][i])}<strong>${e(item)}</strong><small>${i === 3 ? '可逐题作答' : '来自 Unit 原文'}</small></button>`).join('')}</div></div><div class="surface stack"><div class="eyebrow"><span class="signal"></span>逐题练习 · 示例</div><h2 style="font-size:19px">${e(q.prompt)}</h2><div class="answer-list">${q.options.map((answer, i) => `<button class="answer ${s.textbookSubmitted ? i === q.correct ? 'correct' : i === s.textbookAnswer ? 'wrong' : '' : ''}" type="button" data-textbook-answer="${i}" aria-pressed="${s.textbookAnswer === i}" ${s.textbookSubmitted ? 'disabled' : ''}><span>${String.fromCharCode(65 + i)}</span>${e(answer)}</button>`).join('')}</div>${s.textbookSubmitted ? `<div class="feedback ${s.textbookAnswer === q.correct ? 'correct' : 'wrong'}"><strong>${s.textbookAnswer === q.correct ? '回答正确' : '这题选 A'}</strong><p>「へ」标示移动的方向。这是普通教材练习的逐题反馈。</p></div><button class="secondary" type="button" data-action="textbookReset">重新体验</button>` : `<button class="primary" type="button" data-action="textbookSubmit" ${s.textbookAnswer < 0 ? 'disabled' : ''}>确认答案</button>`}</div></div></div>`;
  }
  function examPrep() {
    return `${head('EXAM / PREPARE', 'N2 模拟试卷', '校对题目结构、听力文字稿与答案依据，冻结版本后进入整卷作答。')}<div class="grid-3" style="margin-top:23px"><div class="stat"><strong>38</strong><span>示例小题</span></div><div class="stat"><strong>60</strong><span>分钟 · 示例时限</span></div><div class="stat"><strong>${s.examReady ? '已冻结' : '待校对'}</strong><span>试卷状态</span></div></div><div class="grid-aside" style="margin-top:23px"><div class="surface stack"><h2 style="font-size:19px">准备清单</h2><div class="check-row">${I('check')}<span>题号、题组与分值</span>${tag('待人工校对', 'warn')}</div><div class="check-row">${I('book')}<span>听力脚本与题组候选</span>${tag(s.examScriptMatched ? '已确认' : '待校对', s.examScriptMatched ? 'good' : 'warn')}</div><div class="check-row">${I('headphones')}<span>私有 TTS 音频</span>${tag(s.examAudioReady ? '示例就绪' : '未生成', s.examAudioReady ? 'good' : 'warn')}</div><div class="button-row"><button class="secondary" type="button" data-modal="examScript">校对听力候选</button><button class="secondary" type="button" data-action="examTts" ${s.examScriptMatched ? '' : 'disabled'}>生成音频（模拟）</button><button class="primary" type="button" data-action="examFreeze" ${s.examScriptMatched && s.examAudioReady ? '' : 'disabled'}>${s.examReady ? '查看考前说明' : '确认并冻结版本'}</button></div></div><aside class="callout warn">${I('warning')}<span>原始音频上传暂不支持。整卷作答期间没有解释、Agent、答案与即时评分入口；交卷后才能复盘。</span></aside></div>`;
  }
  function examRun() {
    const q = data.exam.questions[s.examQuestion]; const count = Object.keys(s.examAnswers).length;
    return `<div class="section-head" style="margin-top:0"><div>${head('EXAM / IN PROGRESS', '整卷作答', '当前场次示例：60 分钟 · 原型计时和保存均为本地演示。')}</div>${tag('剩余 42:18', 'warn')}</div><div class="grid-aside" style="margin-top:22px"><div class="surface stack-lg"><div class="eyebrow"><span class="signal"></span>${e(q.group)} · 第 ${s.examQuestion + 1} 题</div><h2 style="font-size:20px">${e(q.text)}</h2>${q.group === '听力' ? `<div class="callout">${I('headphones')}<span>正式听力按在线场次记录次数；此原型不生成音频。</span></div><button class="secondary" type="button" data-action="examPlay">播放听力（界面示意）</button>` : ''}<div class="answer-list">${q.options.map((answer, i) => `<button type="button" class="answer" data-exam-answer="${i}" aria-pressed="${s.examAnswers[q.id] === i}"><span>${String.fromCharCode(65 + i)}</span>${e(answer)}</button>`).join('')}</div><div class="button-row"><button class="secondary" type="button" data-action="examMark">${I('bookmark')} ${s.examMarked.includes(q.id) ? '取消标记' : '标记此题'}</button><button class="secondary" type="button" data-action="examSave">保存草稿</button><button class="secondary" type="button" data-action="examPrev" ${s.examQuestion === 0 ? 'disabled' : ''}>上一题</button><button class="secondary" type="button" data-action="examNext" ${s.examQuestion === data.exam.questions.length - 1 ? 'disabled' : ''}>下一题</button></div></div><aside class="stack"><div class="panel"><h2 style="font-size:18px">答题卡</h2><p class="small muted" style="margin:6px 0 15px">已答 ${count} / ${data.exam.questions.length} 个示例题 · ${e(s.examDraft)}</p><div class="button-row">${data.exam.questions.map((item, i) => `<button type="button" class="${s.examQuestion === i ? 'primary' : 'secondary'}" data-exam-question="${i}">${s.examMarked.includes(item.id) ? '★ ' : ''}${i + 1}${s.examAnswers[item.id] !== undefined ? ' ·' : ''}</button>`).join('')}</div></div><button class="danger-btn full" type="button" data-modal="examSubmit">交卷</button><div class="callout">${I('shield')}<span>题面不返回答案与解析；服务端负责实际时限、草稿和幂等交卷。</span></div></aside></div>`;
  }
  function examResult() {
    const score = data.exam.questions.filter(q => s.examAnswers[q.id] === q.correct).length;
    return `${head('EXAM / RESULT', '交卷后的复盘。', '以下分数仅由虚构示例答案计算；正式成绩以服务端有效评分为准。')}<div class="grid-3" style="margin-top:23px"><div class="stat"><strong>${score} / ${data.exam.questions.length}</strong><span>示例客观题</span></div><div class="stat"><strong>${data.exam.questions.length - score}</strong><span>需要回看的示例题</span></div><div class="stat"><strong>已交卷</strong><span>示例答卷状态</span></div></div><div class="section-head"><h2>逐题复盘</h2>${btn('查看错题库', 'mistakes', 'secondary')}</div><div class="table-wrap"><table class="table"><thead><tr><th>题号</th><th>部分</th><th>你的选择</th><th>参考答案</th></tr></thead><tbody>${data.exam.questions.map((q, i) => `<tr><td>${i + 1}</td><td>${e(q.group)}</td><td>${s.examAnswers[q.id] === undefined ? '未作答' : e(q.options[s.examAnswers[q.id]])}</td><td>${e(q.options[q.correct])}</td></tr>`).join('')}</tbody></table></div>`;
  }
  function notebooks() {
    return `${head('WORDS / ORGANIZE', '你的词，按自己的方式安放。', '多个词本可以共享词条与学习状态；掌握由有效习题证据计算。')}<div class="section-head"><h2>我的词本</h2><button class="primary" type="button" data-modal="newNotebook">${I('plus')} 新建词本</button></div><div class="grid-3">${s.notebooks.map(book => `<button class="panel" type="button" data-book="${book.id}" style="border:0;text-align:left;color:var(--ink);min-height:165px"><span class="signal"></span><p class="small muted" style="margin:13px 0 5px">${e(book.language)} · ${book.count} 词</p><h2 style="font-size:21px">${e(book.title)}</h2><p class="subtitle">${e(book.description)}</p></button>`).join('')}</div><div class="section-head"><h2>整理与迁移</h2></div><div class="grid-2"><button class="surface" type="button" data-go="csv" style="display:flex;gap:14px;text-align:left;border:0;color:var(--ink)">${I('upload')}<span class="row-copy"><strong>单词 CSV</strong><small>导入预览、词本归属和示例导出</small></span>${I('chevron')}</button><button class="surface" type="button" data-go="mistakes" style="display:flex;gap:14px;text-align:left;border:0;color:var(--ink)">${I('warning')}<span class="row-copy"><strong>错题库</strong><small>可靠错误、当前状态与独立收藏</small></span>${I('chevron')}</button></div>`;
  }
  function notebook() {
    const book = s.notebooks.find(b => b.id === s.selectedBook) || s.notebooks[0];
    const words = s.words.filter(w => w.book === book.id || w.books?.includes(book.id));
    return `${head(`NOTEBOOK / ${e(book.language)}`, e(book.title), e(book.description))}<div class="section-head"><h2>词条 <span>${words.length} 个示例</span></h2><div class="button-row"><button class="secondary" type="button" data-modal="bookActions">管理词本</button><button class="secondary" type="button" data-modal="newWord">${I('plus')} 添加词条</button><button class="primary" type="button" data-action="useNotebook">${I('spark')} 作为习题来源</button></div></div><div class="table-wrap"><table class="table"><thead><tr><th>词形</th><th>释义</th><th>出处</th><th>掌握</th><th></th></tr></thead><tbody>${words.map(w => `<tr><td><strong lang="ja">${e(w.word)}</strong><br><small class="muted">${e(w.reading)}</small></td><td>${e(w.meaning)}</td><td>${e(w.source)}</td><td>${tag(w.mastery)}</td><td><button type="button" data-word="${w.id}">查看 ${I('arrow')}</button></td></tr>`).join('') || '<tr><td colspan="5">这个词本还没有词条，可手动添加或在阅读时收藏。</td></tr>'}</tbody></table></div><div class="callout" style="margin-top:17px">${I('shield')}<span>掌握列只读。删本仅移除组织关系，不删除词条或学习历史。</span></div>`;
  }
  function word() {
    const w = s.words.find(x => x.id === s.selectedWord) || s.words[0];
    return `${head('WORD / CONTEXT', e(w.word), `${e(w.reading)} · ${e(w.meaning)}`)}<div class="grid-aside" style="margin-top:21px"><article class="panel"><div class="eyebrow"><span class="signal"></span>回到原句</div><p lang="ja" style="font-family:'Yu Mincho',serif;font-size:24px;line-height:1.9;margin:15px 0">${e(w.sentence)}</p><p class="small muted">${e(w.source)}</p><div class="divider"></div><div class="button-row">${btn('回到材料', 'novel', 'secondary', 'arrow')}<button type="button" class="secondary" data-modal="moveWord">整理词本</button></div></article><aside class="surface stack"><h2 style="font-size:18px">学习记录</h2><div>${tag(w.mastery)}</div><p class="small muted">这个状态由有效习题证据计算，不能在详情中手动修改。</p><div class="divider"></div><div><strong>个人笔记</strong><p class="small muted" style="margin-top:7px">${e(w.note || '还没有写笔记。')}</p></div><button type="button" class="secondary" data-modal="editWord">编辑词条与笔记</button></aside></div>`;
  }
  function csv() {
    return `${head('WORDS / CSV', '整理好，也带得走。', '单词 CSV 可以导出和导入；作答、错题、AI 历史与可信掌握证据不随 CSV 恢复。')}<div class="grid-2" style="margin-top:24px"><div class="surface stack"><h2 style="font-size:20px">导出单词</h2><p class="subtitle">包含词形、读音、释义和词本归属的虚构样本。</p><button type="button" class="secondary" data-action="csvExport">${I('download')} 下载示例 CSV</button></div><div class="surface stack"><h2 style="font-size:20px">导入预览</h2><label class="field">选择 UTF-8 CSV<input type="file" data-file="csv" accept=".csv,text/csv"><small>${s.csvFile ? `已选择：${e(s.csvFile)}` : '本原型不读取所选文件内容。'}</small></label><button type="button" class="secondary" data-action="csvPreview" ${s.csvFile ? '' : 'disabled'}>打开示例预览</button></div></div>${s.csvStep ? `<div class="surface stack" style="margin-top:20px"><div class="eyebrow"><span class="signal"></span>示例预览 · 与所选文件内容无关</div><h2 style="font-size:20px">2 行新词 · 1 行重复</h2><div class="table-wrap"><table class="table"><thead><tr><th>词形</th><th>释义</th><th>词本</th><th>处理</th></tr></thead><tbody><tr><td>そっと</td><td>轻轻地</td><td>日常的细节</td><td>重复：跳过</td></tr><tr><td>微笑む</td><td>微笑</td><td>阅读时遇见</td><td>补空字段</td></tr></tbody></table></div><div class="button-row"><button class="secondary" type="button">重复跳过</button><button class="secondary" type="button">仅补空字段</button><button class="primary" type="button" data-action="csvConfirm">确认演示导入</button></div><p class="note">本原型不会读取或写入你所选的文件。掌握快照不是有效学习证据。</p></div>` : ''}`;
  }
  function practiceCandidateCount() {
    let count = 0;
    if (s.practiceSources.includes('notebook')) { const ids = s.notebooks.filter(b => b.language === s.activeLanguage && (s.practiceAllWords || s.practiceBookIds.includes(b.id))).map(b => b.id); count += s.words.filter(w => ids.includes(w.book) || w.books?.some(id => ids.includes(id))).length; }
    if (s.activeLanguage === '日语') {
      if (s.practiceSources.includes('collection')) count += s.collected.length;
      if (s.practiceSources.includes('textbook')) count += (data.textbook.units.find(x => x.id === s.practiceTextbookUnit) || data.textbook.units[0]).items.length;
      if (s.practiceSources.includes('mistake')) count += s.mistakes.filter(m => s.practiceMistakeScope === 'all' || (s.practiceMistakeScope === 'current' && m.state === '当前待纠正') || (s.practiceMistakeScope === 'favorite' && m.favorite)).length;
      if (s.practiceSources.includes('report')) count += 1;
    }
    return count;
  }
  function practiceSelectionSummary() {
    const parts = [];
    if (s.practiceSources.includes('notebook')) parts.push(s.practiceAllWords ? `全部本人${s.activeLanguage}单词` : `词本：${s.notebooks.filter(b => s.practiceBookIds.includes(b.id)).map(b => b.title).join('、') || '未选词本'}`);
    if (s.practiceSources.includes('collection')) parts.push(`手选收藏 ${s.collected.length} 项`);
    if (s.practiceSources.includes('textbook')) parts.push(`教材：${(data.textbook.units.find(x => x.id === s.practiceTextbookUnit) || data.textbook.units[0]).title}`);
    if (s.practiceSources.includes('mistake')) parts.push(`错题：${({ all: '全部历史', current: '当前待纠正', favorite: '已收藏' })[s.practiceMistakeScope]}`);
    if (s.practiceSources.includes('report')) parts.push('诊断：方向助词');
    return parts.join(' · ');
  }
  function exerciseDetails() {
    return `<div class="surface stack" style="margin-top:17px"><h2 style="font-size:19px">具体来源范围</h2>${s.practiceSources.includes('notebook') ? `<div class="soft-panel stack"><strong>单词范围</strong><label class="check-row"><input type="radio" name="wordScope" data-practice-all="true" ${s.practiceAllWords ? 'checked' : ''}><span>全部本人单词</span></label><label class="check-row"><input type="radio" name="wordScope" data-practice-all="false" ${s.practiceAllWords ? '' : 'checked'}><span>选择词本</span></label>${s.practiceAllWords ? '' : `<div class="grid-2">${s.notebooks.map(book => `<label class="check-row"><input type="checkbox" data-practice-book="${book.id}" ${s.practiceBookIds.includes(book.id) ? 'checked' : ''}><span>${e(book.title)} · ${e(book.language)}</span></label>`).join('')}</div>`}</div>` : ''}${s.practiceSources.includes('collection') ? `<div class="soft-panel"><strong>手选收藏 ${s.collected.length} 项</strong><p class="small">已保存的词句，只演示本人范围。</p></div>` : ''}${s.practiceSources.includes('textbook') ? `<label class="field">教材单元<select data-practice-unit>${data.textbook.units.map(unit => `<option value="${unit.id}" ${s.practiceTextbookUnit === unit.id ? 'selected' : ''}>${e(unit.title)}</option>`).join('')}</select></label>` : ''}${s.practiceSources.includes('mistake') ? `<label class="field">错题范围<select data-practice-mistakes><option value="current" ${s.practiceMistakeScope === 'current' ? 'selected' : ''}>当前待纠正</option><option value="favorite" ${s.practiceMistakeScope === 'favorite' ? 'selected' : ''}>已收藏历史</option><option value="all" ${s.practiceMistakeScope === 'all' ? 'selected' : ''}>全部历史</option></select><small>正式生成仍按有效评分与当前权限过滤。</small></label>` : ''}${s.practiceSources.includes('report') ? `<div class="soft-panel"><strong>诊断薄弱点：方向助词</strong><p class="small">仅使用有证据的学习线索。</p></div>` : ''}</div>`;
  }
  function exercise() {
    const sources = [['notebook', '我的词本', '多个本人词本可去重选源', 'layers'], ['collection', '收藏内容', '选择已保存的词句', 'bookmark'], ['textbook', '教材内容', '来自课文与原生题', 'book'], ['mistake', '当前错题', '仅可靠且有权的错误事实', 'warning'], ['report', '诊断薄弱点', '有学习证据的考察点', 'spark']];
    return `${head('PRACTICE / MAKE IT YOURS', '让表达，变成自己的。', '明确选择来源、预览候选、确认后才使用本人 Key 生成。')}<div class="grid-aside" style="margin-top:24px"><div class="surface stack"><h2 style="font-size:19px">1 · 选择来源</h2><div class="grid-2">${sources.map(([key, label, detail, icon]) => `<label class="tile" style="cursor:pointer;min-height:112px;display:flex;align-items:flex-start;gap:11px"><input type="checkbox" data-source="${key}" ${s.practiceSources.includes(key) ? 'checked' : ''} style="margin-top:3px;accent-color:var(--blue)">${I(icon)}<span><strong style="margin:0">${label}</strong><small>${detail}</small></span></label>`).join('')}</div>${exerciseDetails()}<h2 style="font-size:19px">2 · 设置条件</h2><div class="grid-3"><label class="field">学习语言<select data-setting="activeLanguage"><option ${s.activeLanguage === '日语' ? 'selected' : ''}>日语</option><option ${s.activeLanguage === '英语' ? 'selected' : ''}>英语</option></select></label><label class="field">题型<select data-practice-type>${['语境填空', '词义选择', '翻译判断'].map(x => `<option ${s.practiceQuestionType === x ? 'selected' : ''}>${x}</option>`).join('')}</select></label><label class="field">题量<select data-practice-count>${['5 题', '10 题'].map(x => `<option ${s.practiceCount === x ? 'selected' : ''}>${x}</option>`).join('')}</select></label></div><button class="primary" type="button" data-action="practicePreview" ${s.practiceSources.length && practiceCandidateCount() ? '' : 'disabled'}>预览候选范围</button>${s.practicePreview ? `<div class="soft-panel stack"><strong>示例候选来源 ${practiceCandidateCount()} 项</strong><p class="small">来源：${e(practiceSelectionSummary())}；${e(s.activeLanguage)} · ${e(s.practiceQuestionType)} · ${e(s.practiceCount)}。预览仅读取，不调用模型；正式服务仍需去重、鉴权与版本校验。</p><button class="primary" type="button" data-modal="generateConfirm">确认生成示例习题</button></div>` : ''}</div><aside class="stack"><div class="panel stack"><h2 style="font-size:20px">已有示例题</h2><p class="subtitle">在没有新模型调用的情况下，查看完整逐题流程。</p>${btn('开始逐题练习', 'practice', 'primary', 'arrow')}</div><div class="surface stack"><h2 style="font-size:18px">错题库</h2><p class="subtitle">可靠错误留档，当前状态与收藏分别管理。</p>${btn('打开错题库', 'mistakes', 'secondary')}</div></aside></div>`;
  }
  function practice() {
    const p = s.activeLanguage === '英语' ? data.practiceEnglish : data.practice;
    return `${head('PRACTICE / 01', '让语气落在对的地方。', '内置${e(s.activeLanguage)}示例题 · 语境填空')}<div class="grid-aside" style="margin-top:24px"><div class="surface stack-lg"><p class="small muted">${e(p.translation)}</p><h2 lang="${s.activeLanguage === '英语' ? 'en' : 'ja'}" style="font-family:${s.activeLanguage === '英语' ? "'Segoe UI',sans-serif" : "'Yu Mincho',serif"};font-size:27px;line-height:1.75;font-weight:500">${e(p.prompt)}</h2><div class="answer-list">${p.options.map((answer, i) => `<button class="answer ${s.practiceSubmitted ? i === p.correct ? 'correct' : i === s.practiceAnswer ? 'wrong' : '' : ''}" type="button" data-practice-answer="${i}" aria-pressed="${s.practiceAnswer === i}" ${s.practiceSubmitted ? 'disabled' : ''}><span>${String.fromCharCode(65 + i)}</span>${e(answer)}</button>`).join('')}</div>${s.practiceSubmitted ? `<div class="feedback ${s.practiceAnswer === p.correct ? 'correct' : 'wrong'}"><strong>${s.practiceAnswer === p.correct ? '答对了。' : '这次应该选 ${String.fromCharCode(65 + p.correct)}。'}</strong><p>${e(p.explanation)}示例反馈不写入学习证据。</p></div><button class="secondary" type="button" data-action="practiceReset">重新体验</button>` : `<button class="primary" type="button" data-action="practiceSubmit" ${s.practiceAnswer < 0 ? 'disabled' : ''}>确认答案</button>`}</div><aside class="panel stack"><div class="eyebrow"><span class="signal"></span>题目来源</div><h2 style="font-size:20px">${e(s.activeLanguage)}内置示例</h2><p class="subtitle">这道现成题独立于刚才的候选预览；正式生成会冻结用户选择的来源与版本。</p><div class="divider"></div>${btn('查看词本', 'notebooks', 'secondary')}</aside></div>`;
  }
  function mistakes() {
    return `${head('MISTAKES / HISTORY', '错题，也是路标。', '可靠错误留档；当前有效状态与个人收藏分别维护。')}<div class="grid-3" style="margin-top:23px"><div class="stat"><strong>${s.mistakes.length}</strong><span>历史示例</span></div><div class="stat"><strong>${s.mistakes.filter(m => m.state === '当前待纠正').length}</strong><span>当前待纠正</span></div><div class="stat"><strong>${s.mistakes.filter(m => m.favorite).length}</strong><span>已收藏</span></div></div><div class="section-head"><h2>错题记录</h2>${btn('以错题出题', 'exercise', 'secondary', 'spark')}</div><div class="table-wrap"><table class="table"><thead><tr><th>考察点</th><th>来源</th><th>当前状态</th><th>收藏</th><th></th></tr></thead><tbody>${s.mistakes.map(m => `<tr><td><strong>${e(m.title)}</strong></td><td>${e(m.source)}</td><td>${tag(m.state, m.state === '已经改进' ? 'good' : 'warn')}</td><td>${m.favorite ? '已收藏' : '—'}</td><td><button type="button" data-mistake="${m.id}">查看 ${I('arrow')}</button></td></tr>`).join('')}</tbody></table></div>`;
  }
  function mistake() {
    const m = s.mistakes.find(x => x.id === s.selectedMistake) || s.mistakes[0];
    return `${head('MISTAKE / DETAIL', e(m.title), e(m.source))}<div class="grid-aside" style="margin-top:22px"><div class="panel stack"><div>${tag(m.state, m.state === '已经改进' ? 'good' : 'warn')}</div><h2 style="font-size:19px">当时的作答</h2><p>${e(m.answer)}</p><div class="callout">${I('shield')}<span>收藏不会修改评分事实或当前错误状态。重评和作废会保留历史并更新有效投影。</span></div></div><aside class="surface stack"><h2 style="font-size:18px">下一步</h2><button type="button" class="secondary" data-action="favoriteMistake">${I('bookmark')} ${m.favorite ? '取消收藏' : '收藏错题'}</button>${btn('从当前错题出题', 'exercise', 'primary', 'spark')}</aside></div>`;
  }
  function agent() {
    return `${head('AGENT / CONTEXT', '从真实语境里，继续想。', '对话使用有权内容和本人模型；本页只演示对话布局与来源卡片。')}<div class="grid-aside" style="margin-top:23px"><div class="stack">${s.messages.map(m => `<article class="${m.from === 'agent' ? 'panel' : 'soft-panel'}"><div class="eyebrow">${m.from === 'agent' ? '<span class="signal"></span>HARUKA' : '你'}</div><p style="margin-top:10px;line-height:1.85">${e(m.text)}</p>${m.source ? `<button class="text-btn" type="button" data-go="novel">出处：${e(m.source)} ${I('arrow')}</button>` : ''}</article>`).join('')}<form class="surface form-grid" data-form="chat"><label class="field">继续提问<textarea name="message" required placeholder="关于这句话，你还想知道什么？"></textarea></label><button class="primary" type="submit">发送模拟问题</button></form></div><aside class="stack"><div class="panel stack"><h2 style="font-size:18px">当前上下文</h2><p>夏の手紙 · 第 03 章<br>句子：夏の風がそっと頬に触れた。</p>${btn('回到原文', 'novel', 'secondary')}</div><div class="surface stack"><h2 style="font-size:18px">诊断</h2><p class="small muted">依据可靠作答形成有证据的观察。</p>${btn('查看诊断示例', 'report', 'secondary')}</div><p class="note">演示回复不调用模型或记录用量。</p></aside></div>`;
  }
  function report() {
    return `${head('AGENT / SIGNALS', '看见学习线索。', '虚构示例报告。正式诊断依据有权材料、有效作答与可追溯证据。')}<div class="grid-3" style="margin-top:22px"><div class="panel"><div class="eyebrow"><span class="signal"></span>薄弱点</div><h2 style="margin:13px 0 8px;font-size:21px">方向助词</h2><p>Unit 02 的有效作答显示「に / へ」容易混淆。</p>${btn('回到教材', 'textbook', 'text-btn')}</div><div class="surface"><div class="eyebrow"><span class="signal"></span>亮点</div><h2 style="margin:13px 0 8px;font-size:21px">语境词义</h2><p>能留意句子的情绪和动作方式。</p></div><div class="surface"><div class="eyebrow"><span class="signal"></span>下一步</div><h2 style="margin:13px 0 8px;font-size:21px">选源练习</h2><p>从教材或当前错题预览候选，再明确确认生成。</p>${btn('选择来源', 'exercise', 'text-btn')}</div></div>`;
  }
  function notifications() {
    return `${head('IN-APP / UPDATES', '学习中的每一步，都有回音。', '站内提示来自任务与结果状态；本原型没有系统推送或邮件发送。')}<div class="section-head"><h2>消息 <span>${s.notifications.filter(n => n.unread).length} 条未读</span></h2><button class="text-btn" type="button" data-action="readAll">全部标为已读</button></div><div class="material-list">${s.notifications.map(n => `<button type="button" class="material-row" data-notification="${n.id}"><span class="signal" style="opacity:${n.unread ? 1 : .25}"></span><span class="row-copy"><span class="row-title">${e(n.title)}</span><small>${e(n.detail)}</small></span><small class="muted">${e(n.time)}</small>${I('chevron')}</button>`).join('')}</div>`;
  }
  function jobs() {
    return `${head('ACTIVITY / TASKS', '进度与结果，清楚可见。', '任务完成以真实服务提交为准；以下仅为内存中的示例状态。')}<div class="section-head"><h2>本人任务</h2></div><div class="table-wrap"><table class="table"><thead><tr><th>任务</th><th>阶段</th><th>状态</th><th>相关入口</th></tr></thead><tbody><tr><td>夏の手紙</td><td>文本解析</td><td>${tag('已完成', 'good')}</td><td><button type="button" data-go="novel">打开小说</button></td></tr><tr><td>N2 模拟试卷</td><td>听力校对</td><td>${tag(s.examAudioReady ? '示例就绪' : '待人工确认', 'warn')}</td><td><button type="button" data-go="examPrep">继续准备</button></td></tr>${s.importComplete ? `<tr><td>${e(s.importFile)}</td><td>${e(typeLabel[s.importType])} · 本地演示</td><td>${tag('演示已完成', 'good')}</td><td>未上传文件</td></tr>` : ''}</tbody></table></div>`;
  }
  const settingNav = [['profile', '个人资料', 'user'], ['languages', '语言档案', 'globe'], ['appearance', '外观与无障碍', 'sun'], ['readingPrefs', '阅读偏好', 'book'], ['model', '个人模型', 'spark'], ['speech', '朗读与声音', 'headphones'], ['usage', '模型用量', 'grid'], ['cache', '本机缓存', 'database'], ['connection', '服务连接', 'globe'], ['states', '状态样例', 'warning'], ['security', '安全与账号', 'shield']];
  function settings() { return `${head('PREFERENCES / YOUR SPACE', '按自己的方式，学习世界。', '个人资料、语言、模型和阅读偏好独立保存。')}<div class="grid-3" style="margin-top:25px">${settingNav.map(([route, label, icon]) => `<button type="button" class="tile" data-go="${route}">${I(icon)}<strong>${label}</strong><small>${({ profile: '私有资料', languages: '四种语言角色', appearance: '主题与无障碍', readingPrefs: '字体与行距', model: '本人 Key 与能力', speech: 'TTS 与播放', usage: 'Token 与缓存用量', cache: '当前账号副本', connection: '实例与连接方式', states: '离线、失权与失败', security: '会话与改密' })[route]}</small></button>`).join('')}</div><div class="button-row" style="margin-top:18px">${btn('单词 CSV', 'csv', 'secondary', 'download')}</div><p class="note" style="margin-top:18px">演示资料只存在当前页面内存。此原型不会接收真实 Key 或账号密码。</p>`; }
  function settingContentCore(route) {
    if (route === 'profile') return `<h2>个人资料</h2><p class="subtitle">均为可选信息，默认只对本人可见。</p><form class="form-grid" data-form="profile"><label class="field">显示名<input name="displayName" maxlength="40" value="${e(s.profile.displayName)}"><small>留空时显示“学习者”，不作为登录标识。</small></label><label class="field">出生年份（可选）<input type="number" name="birthYear" min="1900" max="2026" value="${e(s.profile.birthYear)}"></label><label class="field">性别（可选）<select name="gender">${['未填写', '女', '男', '非二元', '自我描述', '不愿说明'].map(x => `<option ${s.profile.gender === x ? 'selected' : ''}>${x}</option>`).join('')}</select></label><label class="field">时区<select name="timezone"><option value="Asia/Tokyo" ${s.profile.timezone === 'Asia/Tokyo' ? 'selected' : ''}>东京 / Asia/Tokyo</option><option value="Asia/Shanghai" ${s.profile.timezone === 'Asia/Shanghai' ? 'selected' : ''}>上海 / Asia/Shanghai</option><option value="UTC" ${s.profile.timezone === 'UTC' ? 'selected' : ''}>UTC</option></select></label><div class="callout">${I('shield')}<span>可选人口字段默认不进入 AI。头像正式流程需受限解码与去元数据；此原型不接收图片。</span></div><button class="primary" type="submit">保存演示资料</button></form>`;
    if (route === 'languages') return `<h2>语言档案</h2><p class="subtitle">界面语言、母语、解释语言和学习语言分别设置。</p><div class="form-grid"><label class="field">界面语言<select disabled><option>简体中文 · 当前支持</option></select><small>其他 UI 语言未开放，不由目标学习语言自动决定。</small></label><div class="field">母语（可多选）${['简体中文', '英语', '日语'].map(x => `<label class="check-row"><input type="checkbox" data-native="${x}" ${s.nativeLanguages.includes(x) ? 'checked' : ''}><span>${x}</span></label>`).join('')}</div><label class="field">解释语言<select data-setting="explanationLanguage">${['简体中文', '英语', '日语'].map(x => `<option ${s.explanationLanguage === x ? 'selected' : ''}>${x}</option>`).join('')}</select></label><div class="field">学习语言（可多选）${['日语', '英语'].map(x => `<label class="check-row"><input type="checkbox" data-target="${x}" ${s.targetLanguages.includes(x) ? 'checked' : ''}><span>${x}</span>${s.activeLanguage === x ? tag('当前') : ''}</label>`).join('')}</div><label class="field">当前学习语言<select data-setting="activeLanguage">${s.targetLanguages.map(x => `<option ${s.activeLanguage === x ? 'selected' : ''}>${x}</option>`).join('')}</select></label><label class="field">自评水平<select data-setting="level">${['未填写', '初学', '基础', '中级', '进阶'].map(x => `<option ${s.level === x ? 'selected' : ''}>${x}</option>`).join('')}</select></label><button class="primary" type="button" data-action="saveSettings">保存语言档案</button></div>`;
    if (route === 'appearance') return `<h2>外观与无障碍</h2><p class="subtitle">即时预览只调整显示，不改变学习记录。</p><div class="form-grid"><label class="field">应用主题<select data-setting="theme"><option value="system" ${s.theme === 'system' ? 'selected' : ''}>跟随系统</option><option value="light" ${s.theme === 'light' ? 'selected' : ''}>浅色</option><option value="dark" ${s.theme === 'dark' ? 'selected' : ''}>深色</option></select></label><label class="check-row"><input type="checkbox" data-toggle="reduceMotion" ${s.reduceMotion ? 'checked' : ''}><span>减少动态</span></label><label class="check-row"><input type="checkbox" data-toggle="highContrast" ${s.highContrast ? 'checked' : ''}><span>高对比显示</span></label><div class="soft-panel"><div class="eyebrow"><span class="signal"></span>LIVE PREVIEW</div><h2 style="margin:13px 0 6px">一页故事，一点新发现。</h2><p>页面按照当前主题演示色彩和文字层次。</p></div><p class="note">正式应用遵守系统文字缩放下限；减少动态时取消大幅位移。</p></div>`;
    if (route === 'readingPrefs') return `<h2>阅读偏好</h2><p class="subtitle">调整小说正文的字体、字号、行距与独立阅读主题。</p><div class="form-grid"><label class="field">字体风格<select data-setting="readingFont"><option value="serif" ${s.readingFont === 'serif' ? 'selected' : ''}>有书感的衬线体</option><option value="sans" ${s.readingFont === 'sans' ? 'selected' : ''}>清晰的无衬线体</option></select></label><label class="field">字号：${s.readingSize}px<input type="range" min="16" max="24" value="${s.readingSize}" data-range="readingSize"></label><label class="field">行距：${s.lineHeight.toFixed(1)}<input type="range" min="1.6" max="2.4" step="0.1" value="${s.lineHeight}" data-range="lineHeight"></label><label class="field">阅读主题<select data-setting="readingTheme"><option value="light" ${s.readingTheme === 'light' ? 'selected' : ''}>浅色</option><option value="dark" ${s.readingTheme === 'dark' ? 'selected' : ''}>深色</option><option value="sepia" ${s.readingTheme === 'sepia' ? 'selected' : ''}>暖纸色</option></select></label><div class="soft-panel" style="background:${s.readingTheme === 'sepia' ? '#f7ead4' : s.readingTheme === 'dark' ? '#192535' : 'var(--blue-soft)'};color:${s.readingTheme === 'dark' ? '#edf3ff' : '#152b42'};font-family:${s.readingFont === 'serif' ? "'Yu Mincho',serif" : "'Segoe UI',sans-serif"};font-size:${s.readingSize}px;line-height:${s.lineHeight}">朝の光が、白いカーテンを通して部屋に広がった。</div><button class="primary" type="button" data-action="saveSettings">保存演示偏好</button></div>`;
    if (route === 'model') return `<h2>个人模型</h2><p class="subtitle">使用本人 Key。文本、视觉和 TTS 能力独立选择与验证。</p><div class="form-grid"><label class="field">供应商<select data-setting="modelProvider"><option ${s.modelProvider === 'OpenRouter' ? 'selected' : ''}>OpenRouter</option><option ${s.modelProvider === 'Gemini' ? 'selected' : ''}>Gemini</option></select></label><label class="field">个人 API Key<input type="password" value="••••••••••••" disabled><small>本原型不接收真实 Key；正式应用加密保存并按本人隔离。</small></label><div class="grid-3"><div class="tile"><strong>文本解释</strong><small>需要文本模型能力</small></div><div class="tile"><strong>视觉识别</strong><small>扫描需明确范围和上限</small></div><div class="tile"><strong>云端朗读</strong><small>需 TTS 能力</small></div></div><button class="secondary" type="button" data-action="modelTest">模拟测试文本能力</button><p class="note">示例状态：${e(s.modelStatus)}。测试不发送任何请求。</p></div>`;
    if (route === 'speech') return `<h2>朗读与声音</h2><p class="subtitle">Gemini 或 OpenRouter TTS。播放倍速改变不重新合成音频。</p><div class="form-grid"><label class="field">TTS 供应商<select data-setting="speechProvider"><option ${s.speechProvider === 'Gemini TTS' ? 'selected' : ''}>Gemini TTS</option><option ${s.speechProvider === 'OpenRouter TTS' ? 'selected' : ''}>OpenRouter TTS</option></select></label><label class="field">默认声音<select><option>日语 · 清晰自然（示例）</option><option>英语 · 清晰自然（示例）</option></select></label><label class="field">播放倍速：${s.speechSpeed.toFixed(1)}×<input type="range" min="0.7" max="1.5" step="0.1" value="${s.speechSpeed}" data-range="speechSpeed"></label><div class="callout">${I('headphones')}<span>试听为控件演示，不生成或播放实际音频。有限播放次数的考试听力走在线场次账本。</span></div><div class="button-row"><button type="button" class="secondary" data-action="speechPreview">试听界面状态</button><button type="button" class="primary" data-action="saveSettings">保存演示偏好</button></div></div>`;
    if (route === 'usage') return `<h2>模型用量</h2><p class="subtitle">虚构示例数据。每个真实供应商 attempt 的用量由服务端保存。</p><div class="tabs" style="margin-bottom:17px">${['7 天', '30 天', '90 天'].map(x => `<button type="button" data-usage-range="${x}" aria-pressed="${s.usageRange === x}">${x}</button>`).join('')}</div><div class="grid-3"><div class="stat"><strong>12</strong><span>示例调用</span></div><div class="stat"><strong>2</strong><span>结果复用事件</span></div><div class="stat"><strong>未提供</strong><span>部分音频用量</span></div></div><div class="table-wrap" style="margin-top:17px"><table class="table"><thead><tr><th>能力</th><th>示例调用</th><th>输入</th><th>输出</th><th>缓存读取</th></tr></thead><tbody><tr><td>文本解释</td><td>8</td><td>12,480</td><td>3,240</td><td>1,800</td></tr><tr><td>TTS</td><td>3</td><td>未提供</td><td>未提供</td><td>未提供</td></tr><tr><td>视觉识别</td><td>1</td><td>1,520</td><td>480</td><td>未提供</td></tr></tbody></table></div><div class="callout" style="margin-top:16px">${I('shield')}<span>未知不写成 0，应用结果复用不产生一条零 Token 模型调用。</span></div>`;
    if (route === 'cache') return `<h2>本机缓存</h2><p class="subtitle">当前账号的阅读、已查解释和允许离线的音频副本。</p><div class="grid-2"><div class="stat"><strong>${s.cacheCleared ? '已清理' : '42 MB'}</strong><span>示例本机副本</span></div><div class="surface"><strong>服务端成果</strong><p class="small muted" style="margin-top:8px">完整解释与 TTS 持久保存；清理本机不删除服务端结果。</p></div></div><div class="callout" style="margin:18px 0">${I('shield')}<span>试卷有限播放次数的听力不进入通用持久离线音频缓存。联网撤权、过期或换账号时旧副本不可继续读取。</span></div><button class="danger-btn" type="button" data-modal="clearCache">${I('trash')} 清除此账号本机缓存</button>`;
    return `<h2>安全与账号</h2><p class="subtitle">用户端与管理端为不同受众会话。</p><div class="stack"><div class="surface"><strong>当前设备会话</strong><p class="small muted" style="margin-top:6px">演示账号 · 用户端</p></div><div class="callout">${I('shield')}<span>正式改密会验证旧密码与当前会话，成功后撤销两端旧会话并要求重新登录。</span></div><div class="button-row"><button class="secondary" type="button" data-modal="password">查看改密流程</button><button class="danger-btn" type="button" data-action="logout">退出演示账号</button></div><p class="note">此原型不接收真实密码、邮箱或 API Key。</p></div>`;
  }
  function settingContent(route) {
    if (route === 'connection') return `<h2>服务连接</h2><p class="subtitle">Windows 可在登录前确认 HTTPS 实例；Web 固定连接当前同源部署。</p><div class="grid-2"><div class="surface stack"><strong>当前 Web 原型</strong><p class="small muted">当前页面仅运行本地演示，不连接业务服务。</p><p class="note">正式 Web 不在运行中任意更改 API origin。</p></div><form class="surface form-grid" data-form="connection"><label class="field">Windows 服务地址示例<input type="url" name="address" required value="${e(s.serviceAddress)}" placeholder="https://your-haruka.example"><small>只接受无用户名、密码、query 和 fragment 的 HTTPS 地址。</small></label><button class="primary" type="submit">模拟无凭据探测</button></form></div>${s.serviceProbe ? `<div class="callout" style="margin-top:17px">${I('shield')}<span>本地预览：未实际联网。正式探测返回实例标识、版本与兼容性；切换实例会退出并清理旧账号副本。</span></div>` : ''}`;
    if (route === 'states') return `<h2>状态样例</h2><p class="subtitle">供设计检查的虚构状态，不代表当前账号真的离线或失权。</p><div class="grid-2"><div class="surface stack"><strong>没有材料</strong><p>添加小说、课本或试卷，材料会出现在本人书库。</p>${btn('添加材料', 'import', 'secondary')}</div><div class="surface stack"><strong>暂时离线</strong><p>有效权限租期内可以读已缓存章节与解释；新的生成、设置保存和考试场次需联网。</p>${btn('查看缓存', 'cache', 'secondary')}</div><div class="surface stack"><strong>没有访问权限</strong><p>这份内容目前不可读取。返回材料库或联系有权管理员。</p>${btn('返回材料库', 'library', 'secondary')}</div><div class="surface stack"><strong>任务未完成</strong><p>示例：网络故障导致结果未知。先查看任务状态，再决定是否重试。</p>${btn('查看任务', 'jobs', 'secondary')}</div><div class="surface stack"><strong>正在载入</strong><p>保留页面结构，不用动画推算业务完成。</p><div class="stepper"><span class="on"></span><span></span><span></span></div></div></div>`;
    const content = settingContentCore(route);
    if (route === 'profile') return `${content}<div class="surface stack" style="margin-top:20px"><h2>头像与隐私</h2><div class="button-row"><span class="avatar">遥</span><span>默认头像 · 仅本人可见</span></div><button type="button" class="secondary" data-action="avatarInfo">查看安全头像流程</button><label class="check-row"><input type="checkbox" data-toggle="useDemographics" ${s.useDemographics ? 'checked' : ''}><span>允许在适用 AI 功能中使用可选人口信息（默认关闭）</span></label><p class="note">头像、出生年份原值和自定义性别说明不发送给模型。</p></div>`;
    if (route === 'languages') return `${content}<div class="surface stack" style="margin-top:20px"><h2>${e(s.activeLanguage || '当前语言')}学习目标</h2><p class="small muted">目标只影响默认建议，不会修改历史或掌握状态。</p><div class="grid-2">${['阅读', '教材', '考试', '听力', '口语', '写作', '词汇', '语法'].map(goal => `<label class="check-row"><input type="checkbox" data-goal="${goal}" ${s.learningGoals.includes(goal) ? 'checked' : ''}><span>${goal}</span></label>`).join('')}</div><button type="button" class="primary" data-action="saveSettings">保存学习目标</button></div>`;
    if (route === 'model') return `${content}<div class="surface stack" style="margin-top:20px"><h2>凭据管理</h2><p>当前凭据：未配置。保存、测试、轮换与停用在正式服务中是独立动作。</p><div class="button-row">${['文本', '视觉', 'TTS'].map(cap => `<button type="button" class="secondary" data-action="modelCapability" data-capability="${cap}">模拟${cap}能力检查</button>`).join('')}</div><button type="button" class="text-btn" data-modal="credential">查看凭据管理流程 ${I('arrow')}</button></div>`;
    return content;
  }
  function settingPage(route) {
    return `${head('PREFERENCES / YOUR SPACE', names[route], '当前账号的资料、学习档案与设备体验。')}<div class="grid-sidebar" style="margin-top:23px"><nav class="setting-menu" aria-label="设置分类">${settingNav.map(([key, label, icon]) => `<button type="button" data-go="${key}" class="${route === key ? 'active' : ''}">${I(icon)}${label}</button>`).join('')}</nav><section class="setting-body">${settingContent(route)}</section></div>`;
  }
  function auth(route) {
    const admin = route === 'adminLogin';
    const title = admin ? '管理端，独立登录。' : route === 'register' ? '从这里开始。' : route === 'recovery' ? '找回访问方式。' : '欢迎回来。';
    return `<div class="auth-wrap"><div class="auth-graphic"><div class="brand"><span class="brand-mark">h</span><span>haruka</span></div><div><div class="eyebrow" style="color:#d8f36a"><span class="signal"></span>${admin ? 'ADMIN / DEMO' : 'CLEAR SIGNAL'}</div><h1>${title}</h1><p style="margin-top:18px">${admin ? '管理布局只展示获准的运维元数据与操作范围。' : '把自己的小说、课本与试卷，变成可阅读、理解和练习的语言学习空间。'}</p></div><p class="small">原型只有本地演示状态，不验证真实账号或权限。</p></div><div class="auth-form"><div><div class="eyebrow"><span class="signal"></span>${admin ? '管理端示例入口' : '个人学习空间'}</div><h2 style="font-size:28px;margin:13px 0 7px">${admin ? '进入管理端演示' : route === 'recovery' ? '找回账号' : route === 'register' ? '提交演示注册' : '登录演示账号'}</h2><p class="subtitle">请使用虚构内容。输入不会发送到服务端。</p><form data-form="${route}" class="form-grid" style="margin-top:26px"><label class="field">登录邮箱<input type="email" name="email" placeholder="example@demo.test" required></label>${route !== 'recovery' ? `<label class="field">密码<input type="password" name="password" placeholder="仅填写演示内容" required minlength="6"></label>` : `<div class="callout">${I('shield')}<span>真实恢复方式尚待确认，演示仅展示统一受理结果。</span></div>`}${route === 'register' ? '<label class="field">确认密码<input type="password" name="confirmPassword" placeholder="再次输入演示密码" required minlength="6"></label>' : ''}<button class="primary full" type="submit">${admin ? '进入管理端演示' : route === 'register' ? '提交演示注册' : route === 'recovery' ? '查看受理结果' : '进入学习空间'}</button></form><div class="button-row" style="margin-top:16px">${admin ? btn('返回用户端登录', 'login', 'text-btn') : route === 'login' ? `${btn('创建账号', 'register', 'text-btn')}${btn('忘记密码', 'recovery', 'text-btn')}` : btn('返回登录', 'login', 'text-btn')}</div><p class="note" style="margin-top:19px">注册只需身份字段；语言、资料和模型配置可之后选择。</p></div></div></div>`;
  }
  function onboarding() { return `<div class="auth-wrap"><div class="auth-graphic"><div class="brand"><span class="brand-mark">h</span><span>haruka</span></div><div><div class="eyebrow" style="color:#d8f36a"><span class="signal"></span>WELCOME</div><h1>按自己的节奏，开始学习。</h1><p style="margin-top:17px">学习语言、解释语言和模型 Key 都可以之后设置。</p></div></div><div class="auth-form"><div><h2 style="font-size:27px;margin-bottom:8px">先选一个方向</h2><p class="subtitle">这一步可以跳过，不影响登录与基础阅读。</p><div class="form-grid" style="margin-top:24px"><label class="field">当前学习语言<select data-setting="activeLanguage"><option>日语</option><option>英语</option></select></label><label class="field">解释语言<select data-setting="explanationLanguage"><option>简体中文</option><option>英语</option><option>日语</option></select></label><button class="primary" type="button" data-action="finishOnboarding">开始体验</button><button class="secondary" type="button" data-action="finishOnboarding">暂时跳过</button></div></div></div></div>`; }
  function registrationStatus() {
    return `<div class="auth-wrap"><div class="auth-graphic"><div class="brand"><span class="brand-mark">h</span><span>haruka</span></div><div><div class="eyebrow" style="color:#d8f36a"><span class="signal"></span>REGISTRATION / DEMO</div><h1>注册请求，已模拟受理。</h1><p style="margin-top:18px">正式注册的验证与审批取决于发布策略。</p></div></div><div class="auth-form"><div class="stack"><h2 style="font-size:27px">下一步</h2><p class="subtitle">本原型没有创建账号或发送邮件。真实注册可能需要邮箱验证或管理员审批；满足激活条件后仍需单独登录。</p><div class="callout">${I('shield')}<span>不要把受理结果当作账号已经激活。</span></div>${btn('返回登录演示', 'login', 'primary')}</div></div></div>`;
  }
  function adminOverview() {
    return `${head('ADMIN / OVERVIEW', '让运维状态清楚可见。', '仅显示获准的运行元数据。此页不提供用户私有材料旁路。')}<div class="grid-3" style="margin-top:25px"><div class="stat"><strong>128</strong><span>示例账号数</span></div><div class="stat"><strong>4</strong><span>待处理任务</span></div><div class="stat"><strong>99.2%</strong><span>示例请求成功率</span></div></div><div class="grid-2" style="margin-top:20px"><div class="panel"><div class="eyebrow"><span class="signal"></span>待关注</div><h2 style="font-size:21px;margin:13px 0 8px">任务队列有 2 项等待重试</h2><p class="subtitle">查看失败原因、归属和允许的操作范围。</p>${btn('查看任务', 'adminJobs', 'secondary')}</div><div class="surface"><div class="eyebrow"><span class="signal"></span>授权变化</div><h2 style="font-size:21px;margin:13px 0 8px">角色更新待核对</h2><p class="subtitle">预览授予范围与受保护角色边界。</p>${btn('查看角色', 'adminRoles', 'secondary')}</div></div>`;
  }
  function adminUsers() {
    const users = [
      ['学习者 A', 'learner-a@example.test', '正常', '用户端'],
      ['学习者 B', 'learner-b@example.test', '待审批', '未启用'],
      ['运维示例', 'operator@example.test', '正常', '管理端']
    ];
    return `${head('ADMIN / USERS', '账号与会话。', '本页只展示虚构运维字段：显示名、邮箱、账号状态及登录受众。')}<div class="section-head"><h2>用户列表</h2><label class="search">${I('search')}<input type="search" data-input="adminSearch" value="${e(s.adminSearch || '')}" placeholder="搜索虚构账号" aria-label="搜索虚构账号"></label></div><div class="table-wrap"><table class="table"><thead><tr><th>用户</th><th>登录邮箱</th><th>状态</th><th>受众</th><th>操作</th></tr></thead><tbody>${users.filter(row => row.join(' ').toLowerCase().includes((s.adminSearch || '').toLowerCase())).map(row => `<tr><td><strong>${e(row[0])}</strong></td><td>${e(row[1])}</td><td>${tag(row[2], row[2] === '正常' ? 'good' : 'warn')}</td><td>${e(row[3])}</td><td><button type="button" data-admin-item="${e(row[0])}">查看运维摘要</button></td></tr>`).join('')}</tbody></table></div><div class="callout" style="margin-top:18px">${I('shield')}<span>管理端不会默认显示头像原图、人口资料、个人 Key、私有材料或学习内容。</span></div>`;
  }
  function adminRoles() {
    return `${head('ADMIN / RBAC', '角色与权限。', '显式拒绝优先；授予范围、继承关系和最后一名可登录超级管理员都需受保护。')}<div class="grid-aside" style="margin-top:23px"><div class="table-wrap"><table class="table"><thead><tr><th>角色</th><th>受众</th><th>成员</th><th>状态</th><th></th></tr></thead><tbody><tr><td>学习者</td><td>用户端</td><td>126</td><td>${tag('默认')}</td><td><button type="button" data-admin-item="学习者角色">预览</button></td></tr><tr><td>支持人员</td><td>管理端</td><td>2</td><td>${tag('受限')}</td><td><button type="button" data-admin-item="支持人员角色">预览</button></td></tr><tr><td>超级管理员</td><td>管理端</td><td>1</td><td>${tag('受保护', 'warn')}</td><td><button type="button" data-admin-item="超级管理员角色">预览</button></td></tr></tbody></table></div><aside class="callout">${I('shield')}<span>界面隐藏、菜单授权和 API/数据范围是不同层次。此演示不会真正修改角色或放宽权限。</span></aside></div>`;
  }
  function adminMenus() {
    return `${head('ADMIN / NAVIGATION', '页面、菜单与操作。', '用户端和管理端的可见入口分别由授权结果控制。')}<div class="grid-2" style="margin-top:23px"><div class="surface stack"><h2 style="font-size:19px">用户端导航</h2>${['材料库', '单词本', 'AI 习题', '错题库', '学习 Agent', '设置'].map(x => `<div class="check-row">${I('check')}<span>${x}</span>${tag('授权后显示')}</div>`).join('')}</div><div class="surface stack"><h2 style="font-size:19px">管理端导航</h2>${['用户与会话', '角色与权限', '注册策略', '任务与资源', '审计诊断'].map(x => `<div class="check-row">${I('check')}<span>${x}</span>${tag('授权后显示')}</div>`).join('')}</div></div><div class="callout" style="margin-top:18px">${I('shield')}<span>导航预览不代替接口授权。深链、按钮和直接 API 仍需要同一动作权限及数据范围校验。</span></div>`;
  }
  function adminPolicy() {
    return `${head('ADMIN / REGISTRATION', '注册策略。', '当前状态仅为示例，正式开放与恢复方式须按已确认部署策略发布。')}<div class="grid-aside" style="margin-top:22px"><div class="surface form-grid"><label class="field">注册方式<select><option>需审批（示例）</option><option>关闭新注册（示例）</option></select></label><label class="field">邮箱验证<select><option>待选择</option><option>启用后校验</option></select></label><label class="field">账号恢复<select><option>待选择</option><option>邮件恢复</option><option>人工恢复</option></select></label><button class="primary" type="button" data-action="adminPreview">预览策略变化（演示）</button></div><aside class="callout warn">${I('warning')}<span>本原型不发布策略，也不承诺未选定的邮件服务已经可用。默认注册角色受保护。</span></aside></div>`;
  }
  function adminJobs() {
    return `${head('ADMIN / JOBS', '任务与资源。', '只展示获准的运维元数据和受控操作，不读取用户私有正文。')}<div class="section-head"><h2>任务摘要</h2></div><div class="table-wrap"><table class="table"><thead><tr><th>任务引用</th><th>类型</th><th>阶段</th><th>状态</th><th></th></tr></thead><tbody><tr><td>JOB-D100</td><td>材料解析</td><td>验证后发布</td><td>${tag('已完成', 'good')}</td><td><button type="button" data-admin-item="JOB-D100">查看摘要</button></td></tr><tr><td>JOB-D101</td><td>模型调用</td><td>等待本人凭据</td><td>${tag('待配置', 'warn')}</td><td><button type="button" data-admin-item="JOB-D101">查看摘要</button></td></tr><tr><td>JOB-D102</td><td>音频生成</td><td>重试检查</td><td>${tag('需处理', 'warn')}</td><td><button type="button" data-admin-item="JOB-D102">查看摘要</button></td></tr></tbody></table></div>`;
  }
  function adminAudit() {
    return `${head('ADMIN / AUDIT', '变更有据可查。', '审计来自受控业务提交，不从前端埋点推断授权成功。')}<div class="table-wrap" style="margin-top:23px"><table class="table"><thead><tr><th>时间</th><th>操作类别</th><th>目标范围</th><th>结果</th></tr></thead><tbody><tr><td>09:42</td><td>角色授权预览</td><td>管理权限</td><td>待提交</td></tr><tr><td>09:16</td><td>会话撤销</td><td>本人设备</td><td>已提交示例</td></tr><tr><td>昨天</td><td>注册策略读取</td><td>注册入口</td><td>已读取示例</td></tr></tbody></table></div><div class="callout" style="margin-top:17px">${I('shield')}<span>审计不展示密码、Token、Key、原始 Prompt 或用户私有材料正文。</span></div>`;
  }
  function adminUsage() {
    return `${head('ADMIN / USAGE', '模型调用概览。', '管理端只看授权范围内的聚合运维数据，不进入个人私有内容。')}<div class="grid-3" style="margin-top:23px"><div class="stat"><strong>284</strong><span>虚构供应商 attempts</span></div><div class="stat"><strong>12</strong><span>用量未提供的 attempts</span></div><div class="stat"><strong>3</strong><span>可见供应商类别</span></div></div><div class="table-wrap" style="margin-top:20px"><table class="table"><thead><tr><th>能力</th><th>真实调用数（示例）</th><th>已知用量</th><th>未知用量</th></tr></thead><tbody><tr><td>文本模型</td><td>210</td><td>1,284,000 Token</td><td>8 attempts</td></tr><tr><td>视觉模型</td><td>38</td><td>184,000 Token</td><td>3 attempts</td></tr><tr><td>TTS</td><td>36</td><td>部分音频秒数</td><td>1 attempt</td></tr></tbody></table></div>`;
  }
  function adminSecurity() {
    return `${head('ADMIN / ACCOUNT', '管理账号与安全。', '管理端与用户端分别登录；这里仅演示当前管理受众的本人安全入口。')}<div class="grid-aside" style="margin-top:22px"><div class="surface stack"><h2 style="font-size:19px">当前管理端会话</h2><p>运维示例 · 在线演示会话</p><div class="callout">${I('shield')}<span>正式改密、本人会话撤销与退出由当前管理受众的身份流程处理，不依赖学习资料权限。</span></div><div class="button-row"><button class="secondary" type="button" data-modal="password">查看改密流程</button><button class="danger-btn" type="button" data-action="adminLogout">退出管理端演示</button></div></div><aside class="panel stack"><h2 style="font-size:18px">切换到用户端</h2><p>切换受众须重新登录，不能静默沿用管理会话。</p><button class="secondary" type="button" data-action="switchClient">进入用户端登录</button></aside></div>`;
  }
  function modal() {
    if (!s.modal) return '';
    let title = '演示提示'; let content = '';
    if (s.modal === 'credential') {
      title = '个人凭据管理';
      content = `<div class="stack"><p>正式流程会分别提供保存、单项能力测试、轮换和停用。测试前展示最小样本、能力、次数及可能消耗的用量。</p><div class="callout warn">${I('shield')}<span>本原型不收集 API Key；停用 Key 不会自动删除已有解释与音频。</span></div></div>`;
    } else if (s.modal === 'quality') {
      const m = data.materials.find(x => x.id === s.chosenMaterial) || data.materials[0];
      title = '解析与来源状态';
      content = `<div class="stack"><p><strong>${e(m.title)}</strong> · ${e(m.status)}</p><div class="callout">${I('shield')}<span>${m.type === 'exam' ? '试卷的题目、分值、答案依据与听力候选仍需校对；原文可用不等于可以开考。' : m.type === 'textbook' ? '可靠单元可学习，未分类内容与缺少答案的题目分别提示。' : '可靠正文可阅读；语言标注与 AI 分析独立呈现状态。'}</span></div><p class="note">文件版本、源锚点与质量门槛由正式服务校验。本页仅是演示。</p></div>`;
    } else if (s.modal === 'textbookItem') {
      const unit = data.textbook.units.find(x => x.id === s.textbookUnit) || data.textbook.units[0];
      title = unit.items[s.textbookItemIndex || 0] || '单元内容';
      content = `<div class="stack"><div class="eyebrow"><span class="signal"></span>UNIT CONTENT</div><p lang="ja" style="font-size:21px">駅まで一緒に行きましょう。</p><p>我们一起去车站吧。</p><div class="callout">${I('book')}<span>示例内容保留在当前单元中，不修改教材原文。</span></div></div>`;
    } else if (s.modal === 'examScript') {
      title = '校对听力候选';
      content = `<div class="stack"><p>题组：听力 · 第 03 题</p><div class="soft-panel"><strong>文字稿候选</strong><p lang="ja" style="margin-top:8px">次の角を右に曲がってください。</p></div><p class="small muted">依据：试卷正文中的听力文字稿示例。实际匹配需要确认题组、小题与脚本来源。</p><label class="check-row"><input id="exam-script-confirm" type="checkbox"><span>我已核对脚本与题组、小题的对应关系</span></label><button class="primary" type="button" data-action="confirmScript">确认示例匹配</button></div>`;
    } else if (s.modal === 'examIntro') {
      title = '考前说明';
      content = `<div class="stack"><div class="stat"><strong>60 分钟</strong><span>示例整卷时间</span></div><p>开始后可以保存草稿、标记题目和切换题号。交卷会锁定答案；评分与解析只在交卷后显示。</p><div class="callout warn">${I('warning')}<span>真实考试的时间与听力播放次数由服务端管理，本原型仅演示界面。</span></div><button class="primary" type="button" data-action="examStart">开始模拟考试</button></div>`;
    } else if (s.modal === 'examSubmit') {
      title = '确认交卷？';
      content = `<div class="stack"><p>已答 ${Object.keys(s.examAnswers).length} / ${data.exam.questions.length} 个示例题。交卷后答案锁定，再查看复盘。</p><div class="button-row"><button class="secondary" type="button" data-action="closeModal">继续作答</button><button class="danger-btn" type="button" data-action="examSubmitConfirm">确认交卷</button></div></div>`;
    } else if (s.modal === 'generateConfirm') {
      title = '确认生成示例习题';
      content = `<div class="stack"><p>候选来源已预览。正式生成需本人有效 Key、当前授权和调用上限。</p><div class="callout">${I('spark')}<span>本原型将打开内置示例题，不调用模型或记录用量。</span></div><button class="primary" type="button" data-action="generateDemo">打开示例习题</button></div>`;
    } else if (s.modal === 'newNotebook') {
      title = '新建词本';
      content = `<form class="form-grid" data-form="newNotebook"><label class="field">名称<input name="name" maxlength="40" required placeholder="例如：故事里的风景"></label><label class="field">学习语言<select name="language"><option>日语</option><option>英语</option></select></label><label class="field">简介<textarea name="description" placeholder="想把哪些词收在这里？"></textarea></label><button type="submit" class="primary">创建演示词本</button></form>`;
    } else if (s.modal === 'newWord') {
      title = '添加词条';
      content = `<form class="form-grid" data-form="newWord"><label class="field">词形<input name="word" required></label><label class="field">释义<input name="meaning" required></label><label class="field">个人例句（可选）<textarea name="sentence"></textarea></label><button type="submit" class="primary">添加到当前词本</button></form>`;
    } else if (s.modal === 'bookActions') {
      title = '整理词本';
      content = `<div class="stack"><button type="button" class="secondary" data-action="renameBook">${I('edit')} 重命名示例词本</button><button type="button" class="danger-btn" data-action="deleteBook">${I('trash')} 删除示例词本</button><p class="note">删本只移除归类，不删除词条或学习历史。</p></div>`;
    } else if (s.modal === 'moveWord') {
      title = '整理词条归属';
      const w = s.words.find(x => x.id === s.selectedWord);
      content = `<div class="stack"><p class="small muted">同一词条可以归入多个词本，共用学习状态。</p>${s.notebooks.map(book => `<label class="check-row"><input type="checkbox" data-word-book="${book.id}" ${w?.book === book.id || w?.books?.includes(book.id) ? 'checked' : ''}><span>${e(book.title)}</span></label>`).join('')}<button type="button" class="primary" data-action="saveWordBooks">保存归属</button></div>`;
    } else if (s.modal === 'editWord') {
      title = '编辑词条与笔记';
      const w = s.words.find(x => x.id === s.selectedWord) || s.words[0];
      content = `<form class="form-grid" data-form="wordEdit"><label class="field">词形<input name="word" required value="${e(w.word)}"></label><label class="field">释义<input name="meaning" required value="${e(w.meaning)}"></label><label class="field">个人笔记<textarea name="note">${e(w.note || '')}</textarea></label><div class="callout">${I('shield')}<span>掌握状态由有效作答证据计算，不能手动编辑。</span></div><button type="submit" class="primary">保存示例词条</button></form>`;
    } else if (s.modal === 'clearCache') {
      title = '清理本机副本？';
      content = `<div class="stack"><p>只清理演示账号的本机状态。正式服务已保存的解释和音频不受影响。</p><div class="button-row"><button class="secondary" type="button" data-action="closeModal">返回</button><button class="danger-btn" type="button" data-action="clearCacheConfirm">确认清理</button></div></div>`;
    } else if (s.modal === 'password') {
      title = '修改密码流程';
      content = `<div class="stack"><p>正式应用会验证旧密码与当前会话，成功后撤销两端旧会话并要求重新登录。</p><div class="callout warn">${I('shield')}<span>本原型不收集真实密码，也不假装完成安全变更。</span></div></div>`;
    } else if (s.modal === 'adminItem') {
      title = '运维摘要';
      content = `<div class="stack"><strong>${e(s.adminItem || '示例对象')}</strong><p>仅演示获准的状态、任务引用和审计入口。正式系统会对当前管理者的操作、目标范围和受保护资源重新鉴权。</p><div class="callout">${I('shield')}<span>私有材料、个人 Key 与学习内容不在此处显示。</span></div></div>`;
    }
    return `<div class="modal-backdrop" data-action="closeModal"><section class="dialog" role="dialog" aria-modal="true" aria-label="${e(title)}" data-stop="true"><div class="dialog-head"><h2>${e(title)}</h2><button type="button" class="icon-btn" data-action="closeModal" aria-label="关闭">${I('close')}</button></div>${content}</section></div>`;
  }
  const views = { library, import: importPage, material, novel, textbook, examPrep, examRun, examResult, notebooks, notebook, word, csv, exercise, practice, mistakes, mistake, agent, report, notifications, jobs, settings, profile: settingPage, languages: settingPage, appearance: settingPage, readingPrefs: settingPage, model: settingPage, speech: settingPage, usage: settingPage, cache: settingPage, security: settingPage, connection: settingPage, states: settingPage, login: auth, register: auth, registrationStatus, recovery: auth, onboarding, adminLogin: auth, adminOverview, adminUsers, adminRoles, adminMenus, adminPolicy, adminJobs, adminAudit, adminUsage, adminSecurity };
  function render() {
    if (!views[s.route]) s.route = 'library';
    if (s.route === 'registrationStatus' && !s.registrationAccepted) { s.route = 'register'; history.replaceState(null, '', '#register'); }
    if (s.route === 'onboarding' && !s.signedIn) { s.route = 'login'; history.replaceState(null, '', '#login'); }
    if (adminRoutes.includes(s.route) && !s.adminSignedIn) { s.route = 'adminLogin'; history.replaceState(null, '', '#adminLogin'); }
    if (!s.signedIn && !adminRoutes.includes(s.route) && !['login', 'register', 'registrationStatus', 'recovery', 'onboarding', 'adminLogin'].includes(s.route)) { s.route = 'login'; history.replaceState(null, '', '#login'); }
    if (s.route === 'examRun' && s.examFinished) { s.route = 'examResult'; history.replaceState(null, '', '#examResult'); }
    if (s.route === 'examRun' && !s.examRunning && !s.examFinished) { s.route = 'examPrep'; history.replaceState(null, '', '#examPrep'); }
    if (s.route === 'examResult' && !s.examFinished) { s.route = 'examPrep'; history.replaceState(null, '', '#examPrep'); }
    s.adminArea = adminRoutes.includes(s.route);
    document.body.dataset.theme = s.theme === 'system' ? 'light' : s.theme;
    document.body.dataset.contrast = s.highContrast ? 'on' : 'off';
    document.body.dataset.reduceMotion = s.reduceMotion ? 'on' : 'off';
    const authScreen = ['login', 'register', 'registrationStatus', 'recovery', 'onboarding', 'adminLogin'].includes(s.route);
    root.innerHTML = authScreen ? `${views[s.route](s.route)}${s.toast ? `<div class="toast" role="status">${e(s.toast)}</div>` : ''}` : `<div class="workspace">${sidebar()}<div class="app-main">${topbar()}<main class="desktop-screen" id="main-content">${views[s.route](s.route)}</main></div></div>${modal()}${s.toast ? `<div class="toast" role="status">${e(s.toast)}</div>` : ''}`;
  }
  window.addEventListener('hashchange', () => { const route = decodeURIComponent(location.hash.slice(1)); if (views[route]) { s.route = route; render(); } });
  root.addEventListener('click', event => {
    const target = event.target.closest('[data-action],[data-go],[data-modal],[data-filter],[data-material],[data-import-type],[data-term],[data-unit],[data-book],[data-word],[data-mistake],[data-notification],[data-practice-answer],[data-textbook-answer],[data-exam-question],[data-exam-answer],[data-usage-range],[data-admin-item]');
    if (!target || target.disabled) return;
    if (event.target.closest('[data-stop]') && target.classList.contains('modal-backdrop')) return;
    if (target.dataset.modal) { s.modal = target.dataset.modal; if (target.dataset.index) s.textbookItemIndex = Number(target.dataset.index); render(); return; }
    if (target.dataset.go) { if (target.dataset.go === 'adminLogin' && !s.adminArea) s.signedIn = false; if (target.dataset.go === 'login' && s.adminArea) { s.adminSignedIn = false; s.signedIn = false; } go(target.dataset.go); return; }
    if (target.dataset.filter) { s.filter = target.dataset.filter; render(); return; }
    if (target.dataset.material) { s.chosenMaterial = target.dataset.material; go('material'); return; }
    if (target.dataset.importType) { s.importType = target.dataset.importType; render(); return; }
    if (target.dataset.term) { s.selectedTerm = target.dataset.term; render(); return; }
    if (target.dataset.unit) { s.textbookUnit = target.dataset.unit; s.textbookAnswer = -1; s.textbookSubmitted = false; render(); return; }
    if (target.dataset.book) { s.selectedBook = target.dataset.book; go('notebook'); return; }
    if (target.dataset.word) { s.selectedWord = target.dataset.word; go('word'); return; }
    if (target.dataset.mistake) { s.selectedMistake = target.dataset.mistake; go('mistake'); return; }
    if (target.dataset.notification) { const n = s.notifications.find(x => x.id === target.dataset.notification); if (n) { n.unread = false; go(n.route); } return; }
    if (target.dataset.adminItem) { s.adminItem = target.dataset.adminItem; s.modal = 'adminItem'; render(); return; }
    if (target.dataset.practiceAnswer !== undefined) { s.practiceAnswer = Number(target.dataset.practiceAnswer); render(); return; }
    if (target.dataset.textbookAnswer !== undefined) { s.textbookAnswer = Number(target.dataset.textbookAnswer); render(); return; }
    if (target.dataset.examQuestion !== undefined) { s.examQuestion = Number(target.dataset.examQuestion); render(); return; }
    if (target.dataset.examAnswer !== undefined) { if (s.examFinished || !s.examRunning) return; s.examAnswers[data.exam.questions[s.examQuestion].id] = Number(target.dataset.examAnswer); s.examDraft = '未保存的演示选择'; render(); return; }
    if (target.dataset.usageRange) { s.usageRange = target.dataset.usageRange; render(); return; }
    const action = target.dataset.action;
    if (action === 'closeModal') { s.modal = ''; render(); return; }
    if (action === 'clearSearch') { s.search = ''; s.filter = 'all'; render(); return; }
    if (action === 'importBack') { s.importStep = Math.max(0, s.importStep - 1); render(); return; }
    if (action === 'importNext') { if (s.importStep === 0 && !s.importType) return toast('请先选择小说、课本或试卷。'); if (s.importStep === 1 && !s.importFile) return toast('请先选择一个示例文件。'); s.importStep = Math.min(2, s.importStep + 1); render(); return; }
    if (action === 'importConfirm') { s.importComplete = true; s.notifications.unshift({ id: `local-${Date.now()}`, title: `${s.importFile} · 示例任务已受理`, detail: '仅本地演示，文件未读取或上传。', time: '刚刚', route: 'jobs', unread: true }); s.importStep = 0; go('jobs'); toast('本地演示任务已创建；文件没有上传。'); return; }
    if (action === 'toggleSpeech') { s.playing = !s.playing; toast(s.playing ? '朗读控件处于播放状态；没有实际音频。' : '朗读控件已暂停。'); return; }
    if (action === 'bookmark') return toast('示例书签已加入本地阅读状态。');
    if (action === 'chapter') return toast(`第 ${Number(target.dataset.index) + 1} 章为目录示例；当前正文仍是第 03 章。`);
    if (action === 'collectTerm') { s.collected = s.collected.includes(s.selectedTerm) ? s.collected.filter(x => x !== s.selectedTerm) : [...s.collected, s.selectedTerm]; render(); return; }
    if (action === 'textbookSubmit') { s.textbookSubmitted = true; render(); return; }
    if (action === 'textbookReset') { s.textbookSubmitted = false; s.textbookAnswer = -1; render(); return; }
    if (action === 'confirmScript') { if (!root.querySelector('#exam-script-confirm')?.checked) return toast('请先核对并勾选确认。'); s.examScriptMatched = true; s.modal = ''; toast('候选匹配已确认（本地演示）。'); return; }
    if (action === 'examTts') { s.examAudioReady = true; toast('私有 TTS 状态已就绪（模拟），没有生成音频。'); return; }
    if (action === 'examFreeze') { if (s.examFinished) return go('examResult'); s.examReady = true; s.modal = 'examIntro'; render(); return; }
    if (action === 'examStart') { if (s.examFinished) return go('examResult'); s.modal = ''; s.examRunning = true; go('examRun'); return; }
    if (action === 'examPlay') return toast('听力按钮仅演示界面；没有播放或消耗次数。');
    if (action === 'examMark') { const id = data.exam.questions[s.examQuestion].id; s.examMarked = s.examMarked.includes(id) ? s.examMarked.filter(x => x !== id) : [...s.examMarked, id]; render(); return; }
    if (action === 'examSave') { s.examDraft = '本地演示草稿已保存'; toast('演示草稿保留在当前页面内存。'); return; }
    if (action === 'examPrev' || action === 'examNext') { s.examQuestion += action === 'examPrev' ? -1 : 1; render(); return; }
    if (action === 'examSubmitConfirm') { if (s.examFinished || !s.examRunning) return; s.examFinished = true; s.examRunning = false; s.modal = ''; go('examResult'); return; }
    if (action === 'useNotebook') { s.practiceSources = [...new Set([...s.practiceSources, 'notebook'])]; s.practiceAllWords = false; s.practiceBookIds = [s.selectedBook]; s.activeLanguage = s.notebooks.find(b => b.id === s.selectedBook)?.language || s.activeLanguage; s.practicePreview = false; go('exercise'); return; }
    if (action === 'practicePreview') { if (!practiceCandidateCount()) return toast('当前范围没有示例候选，请调整来源。'); s.practicePreview = true; render(); return; }
    if (action === 'generateDemo') { s.practiceGenerated = true; s.modal = ''; go('practice'); return; }
    if (action === 'practiceSubmit') { s.practiceSubmitted = true; render(); return; }
    if (action === 'practiceReset') { s.practiceSubmitted = false; s.practiceAnswer = -1; render(); return; }
    if (action === 'favoriteMistake') { const m = s.mistakes.find(x => x.id === s.selectedMistake); if (m) m.favorite = !m.favorite; render(); return; }
    if (action === 'readAll') { s.notifications.forEach(n => { n.unread = false; }); render(); return; }
    if (['saveLanguages', 'saveReading', 'saveSpeech'].includes(action)) return toast('演示偏好已保存在当前页面内存。');
    if (action === 'modelTest') { s.modelStatus = '文本能力模拟测试已完成'; toast('模拟测试完成，没有调用供应商。'); return; }
    if (action === 'modelCapability') { s.modelStatus = `${target.dataset.capability}能力模拟检查已完成`; toast(`${target.dataset.capability}能力只完成本地界面演示，没有调用供应商。`); return; }
    if (action === 'avatarInfo') return toast('头像需要本人临时上传、安全解码、去元数据与发布；原型不接收图片。');
    if (action === 'saveSettings') return toast('演示偏好已保存在当前页面内存。');
    if (action === 'speechPreview') return toast('试听状态已演示，没有合成或播放音频。');
    if (action === 'csvPreview') { s.csvStep = 1; render(); return; }
    if (action === 'csvConfirm') { s.csvStep = 0; toast('示例预览已确认；未读取或导入真实 CSV。'); return; }
    if (action === 'csvExport') { const content = '\uFEFFword,reading,meaning,notebook\r\nそっと,sotto,轻轻地,日常的细节\r\n微笑む,ほほえむ,微笑,阅读时遇见\r\n'; const link = document.createElement('a'); link.href = URL.createObjectURL(new Blob([content], { type: 'text/csv;charset=utf-8' })); link.download = 'haruka-demo-words.csv'; link.click(); setTimeout(() => URL.revokeObjectURL(link.href), 1000); toast('已生成虚构样本 CSV。'); return; }
    if (action === 'clearCacheConfirm') { s.cacheCleared = true; s.modal = ''; toast('本地演示缓存状态已清理。'); return; }
    if (action === 'logout') { s.signedIn = false; go('login'); return; }
    if (action === 'adminLogout') { s.adminSignedIn = false; go('adminLogin'); return; }
    if (action === 'switchClient') { s.adminSignedIn = false; s.signedIn = false; go('login'); return; }
    if (action === 'finishOnboarding') { s.signedIn = true; go('library'); return; }
    if (action === 'renameBook') { const book = s.notebooks.find(x => x.id === s.selectedBook); if (book) book.title += ' · 整理中'; s.modal = ''; toast('示例词本已重命名。'); return; }
    if (action === 'deleteBook') { s.notebooks = s.notebooks.filter(x => x.id !== s.selectedBook); s.modal = ''; go('notebooks'); toast('词本已删除；词条和历史仍保留。'); return; }
    if (action === 'saveWordBooks') { const word = s.words.find(x => x.id === s.selectedWord); if (word) { const selected = [...root.querySelectorAll('[data-word-book]:checked')].map(x => x.dataset.wordBook); word.book = selected[0] || ''; word.books = selected.slice(1); } s.modal = ''; toast('示例归属已更新。'); return; }
    if (action === 'adminPreview') return toast('只展示演示状态；没有发布管理策略。');
  });
  root.addEventListener('change', event => {
    const t = event.target;
    if (t.dataset.file === 'material') { s.importFile = t.files?.[0]?.name || ''; render(); return; }
    if (t.dataset.file === 'csv') { s.csvFile = t.files?.[0]?.name || ''; s.csvStep = 0; render(); return; }
    if (t.dataset.source) { s.practiceSources = t.checked ? [...s.practiceSources, t.dataset.source] : s.practiceSources.filter(x => x !== t.dataset.source); s.practicePreview = false; render(); return; }
    if (t.dataset.practiceAll !== undefined) { s.practiceAllWords = t.dataset.practiceAll === 'true'; s.practicePreview = false; render(); return; }
    if (t.dataset.practiceBook) { s.practiceBookIds = t.checked ? [...s.practiceBookIds, t.dataset.practiceBook] : s.practiceBookIds.filter(id => id !== t.dataset.practiceBook); s.practicePreview = false; render(); return; }
    if (t.dataset.practiceUnit !== undefined) { s.practiceTextbookUnit = t.value; s.practicePreview = false; render(); return; }
    if (t.dataset.practiceMistakes !== undefined) { s.practiceMistakeScope = t.value; s.practicePreview = false; render(); return; }
    if (t.dataset.practiceType !== undefined) { s.practiceQuestionType = t.value; s.practicePreview = false; render(); return; }
    if (t.dataset.practiceCount !== undefined) { s.practiceCount = t.value; s.practicePreview = false; render(); return; }
    if (t.dataset.native) { s.nativeLanguages = t.checked ? [...s.nativeLanguages, t.dataset.native] : s.nativeLanguages.filter(x => x !== t.dataset.native); render(); return; }
    if (t.dataset.target) { s.targetLanguages = t.checked ? [...s.targetLanguages, t.dataset.target] : s.targetLanguages.filter(x => x !== t.dataset.target); if (!s.targetLanguages.includes(s.activeLanguage)) s.activeLanguage = s.targetLanguages[0] || ''; render(); return; }
    if (t.dataset.goal) { s.learningGoals = t.checked ? [...s.learningGoals, t.dataset.goal] : s.learningGoals.filter(x => x !== t.dataset.goal); render(); return; }
    if (t.dataset.toggle) { s[t.dataset.toggle] = t.checked; render(); return; }
    if (t.dataset.range) { s[t.dataset.range] = Number(t.value); render(); return; }
    if (t.dataset.setting) { s[t.dataset.setting] = t.value; if (s.route === 'exercise') { s.practicePreview = false; if (t.dataset.setting === 'activeLanguage') { s.practiceBookIds = s.practiceBookIds.filter(id => s.notebooks.some(b => b.id === id && b.language === s.activeLanguage)); if (!s.practiceBookIds.length) { const first = s.notebooks.find(b => b.language === s.activeLanguage); if (first) s.practiceBookIds = [first.id]; } } } render(); }
  });
  root.addEventListener('input', event => {
    const t = event.target;
    if (t.name === 'password' || t.name === 'confirmPassword') root.querySelector('[name="confirmPassword"]')?.setCustomValidity('');
    if (t.dataset.input === 'search' || t.dataset.input === 'adminSearch') { const key = t.dataset.input; const pos = t.selectionStart; s[key] = t.value; render(); const next = root.querySelector(`[data-input="${key}"]`); next?.focus(); next?.setSelectionRange(pos, pos); }
  });
  root.addEventListener('submit', event => {
    const form = event.target.closest('[data-form]'); if (!form) return; event.preventDefault();
    const values = Object.fromEntries(new FormData(form));
    if (form.dataset.form === 'profile') { s.profile = { displayName: String(values.displayName || '').trim() || '学习者', birthYear: values.birthYear || '', gender: values.gender || '未填写', timezone: values.timezone || 'Asia/Tokyo' }; toast('演示资料已保存在当前页面内存。'); return; }
    if (form.dataset.form === 'connection') { s.serviceAddress = String(values.address || ''); try { const url = new URL(s.serviceAddress); if (url.protocol !== 'https:' || url.username || url.password || url.search || url.hash) throw new Error('invalid'); s.serviceAddress = url.origin + url.pathname.replace(/\/$/, ''); s.serviceProbe = true; toast('已生成探测预览，没有实际联网。'); } catch { toast('请输入无账号密码、查询参数或片段的 HTTPS 地址。'); } return; }
    if (form.dataset.form === 'newNotebook') { const name = String(values.name || '').trim(); if (!name) return; const id = `book-${Date.now()}`; s.notebooks.push({ id, title: name, language: values.language, count: 0, tone: 'blue', description: String(values.description || '') }); s.selectedBook = id; s.modal = ''; go('notebook'); return; }
    if (form.dataset.form === 'newWord') { const word = String(values.word || '').trim(); if (!word) return; const id = `word-${Date.now()}`; s.words.push({ id, word, reading: '个人录入', meaning: String(values.meaning || '').trim(), source: '手动添加 · 本人词条', book: s.selectedBook, mastery: '尚无有效证据', sentence: String(values.sentence || '') || '暂无个人例句' }); s.selectedWord = id; s.modal = ''; go('word'); return; }
    if (form.dataset.form === 'wordEdit') { const w = s.words.find(x => x.id === s.selectedWord); if (w) { w.word = String(values.word || '').trim(); w.meaning = String(values.meaning || '').trim(); w.note = String(values.note || ''); } s.modal = ''; go('word'); toast('示例词条已更新。'); return; }
    if (form.dataset.form === 'chat') { const message = String(values.message || '').trim(); if (!message) return; s.messages.push({ from: 'user', text: message }, { from: 'agent', text: '这是本地演示回复。正式 Agent 会先检查材料权限、本人 Key 和调用上限，再给出带来源的解释。', source: '演示内容' }); render(); return; }
    if (['login', 'register', 'recovery', 'adminLogin'].includes(form.dataset.form)) { if (form.dataset.form === 'recovery') return toast('演示受理结果：若账号可用，将按正式配置的恢复方式处理。'); if (form.dataset.form === 'register') { if (String(values.password) !== String(values.confirmPassword)) { const input = form.querySelector('[name="confirmPassword"]'); input.setCustomValidity('两次输入的密码不一致'); input.reportValidity(); return; } s.registrationAccepted = true; s.signedIn = false; go('registrationStatus'); return; } if (form.dataset.form === 'adminLogin') { s.adminSignedIn = true; go('adminOverview'); return; } s.signedIn = true; if (s.registrationAccepted) { s.registrationAccepted = false; go('onboarding'); } else go('library'); }
  });
  const hash = decodeURIComponent(location.hash.slice(1)); if (views[hash]) s.route = hash;
  render();
})();
