// Mocks generated by Mockito from annotations
// in haruka/test/features/settings/cached_settings_repository_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes

import 'dart:async' as _i3;

import 'package:dio/dio.dart' as _i5;
import 'package:haruka/features/settings/data/settings_source.dart' as _i2;
import 'package:haruka/features/settings/domain/settings_snapshot.dart' as _i4;
import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i6;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: experimental_member_use
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

/// A class which mocks [SettingsSource].
///
/// See the documentation for Mockito's code generation for more information.
class MockSettingsSource extends _i1.Mock implements _i2.SettingsSource {
  @override
  _i3.Future<_i4.SettingsSnapshot> fetch(
    _i4.SettingsGroup? group,
    _i5.CancelToken? cancel,
  ) => (super.noSuchMethod(
    Invocation.method(#fetch, [group, cancel]),
    returnValue: _i3.Future<_i4.SettingsSnapshot>.value(
      _i6.dummyValue<_i4.SettingsSnapshot>(
        this,
        Invocation.method(#fetch, [group, cancel]),
      ),
    ),
    returnValueForMissingStub: _i3.Future<_i4.SettingsSnapshot>.value(
      _i6.dummyValue<_i4.SettingsSnapshot>(
        this,
        Invocation.method(#fetch, [group, cancel]),
      ),
    ),
  ) as _i3.Future<_i4.SettingsSnapshot>);

  @override
  _i3.Future<_i4.SettingsSnapshot> patch(
    _i4.SettingsGroup? group,
    _i4.SettingsPatch? patch,
  ) => (super.noSuchMethod(
    Invocation.method(#patch, [group, patch]),
    returnValue: _i3.Future<_i4.SettingsSnapshot>.value(
      _i6.dummyValue<_i4.SettingsSnapshot>(
        this,
        Invocation.method(#patch, [group, patch]),
      ),
    ),
    returnValueForMissingStub: _i3.Future<_i4.SettingsSnapshot>.value(
      _i6.dummyValue<_i4.SettingsSnapshot>(
        this,
        Invocation.method(#patch, [group, patch]),
      ),
    ),
  ) as _i3.Future<_i4.SettingsSnapshot>);
}
